### ISSUE TITLE
Reaper fails to deploy with some cluster names overrides

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#1002]
**What happened?**
When using deploying Reaper with a cluster name override which doesn't comply with k8s naming conventions such as "First Cluster", the reconcile will fail with the following error:

```
2023-06-19T11:54:44.929Z	ERROR	controllers.CassandraDatacenter	CassandraDatacenter resource is invalid	{"cassandradatacenter": "k8ssandra-operator/dc1", "requestNamespace": "k8ssandra-operator", "requestName": "dc1", "loopID": "2e217515-3137-4253-a88b-8a5686609f05", "error": "Validation of user secret failed due to an error: Secret \"First Cluster-reaper\" not found"}
github.com/k8ssandra/cass-operator/controllers/cassandra.(*CassandraDatacenterReconciler).Reconcile
	/workspace/controllers/cassandra/cassandradatacenter_controller.go:120
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234
```

Indeed in the cassdc manifest, we can see the following:

```
  users:
    - secretName: First Cluster-reaper
      superuser: true
```

**Did you expect to see something different?**
This secret should be sanitized to match k8s naming requirements.

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster with the following manifest:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test-3
  namespace: k8ssandra-operator
spec:
  auth: true
  cassandra:
    clusterName: "First Cluster"
    config:
      jvmOptions:
        gc: G1GC
        heapSize: 512Mi
    datacenters:
      - metadata:
          name: dc1
        size: 2
        stopped: false
    serverType: cassandra
    serverVersion: 4.0.5
    storageConfig:
      cassandraDataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard
  secretsProvider: internal
  reaper: {}
```

**Environment**

* K8ssandra Operator version:

    `v1.7.0`
