### ISSUE TITLE
Memeory limits for server-config-init doesn't get modified

### ISSUE THREAD

**Issue by poleszcz** [k8ssandra/k8ssandra-operator#1006]
**What did you do?**

I've encountered issue similar to the one here https://github.com/k8ssandra/k8ssandra-operator/issues/723 and want to set higher memory limit for the init container server-config-init.

To achieve that I've already upgraded helm chart to version 1.5.1.

I've already new values in K8ssandraCluster object....

```
   - config:
        jvmOptions:
          gc: G1GC
          heapSize: 16G
      initContainers:
      - name: server-config-init
        resources:
          limits:
            cpu: 1
            memory: 1G
          requests:
            cpu: 1
            memory: 1G
      jmxInitContainerImage:
        name: busybox
        registry: docker.io
        tag: 1.34.1
      metadata:
        name: myname
```
but when I delete STS it gets recreated with default limits.

```
  server-config-init:
    Container ID:   containerd://17433e9a9e770f757ba225308ed3715cb65196432eb329ecd38cf486aba0c9bd
    Image:          datastax/cass-config-builder:1.0-ubi7
    Image ID:       docker.io/datastax/cass-config-builder@sha256:e1d2154f93034d670586049534c6281f59a26d39c25885a6eba1737677ad6319
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Fri, 23 Jun 2023 18:50:37 +0200
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Fri, 23 Jun 2023 18:50:33 +0200
      Finished:     Fri, 23 Jun 2023 18:50:37 +0200
    Ready:          False
    Restart Count:  1
    Limits:
      cpu:     1
      memory:  256M
    Requests:
      cpu:     1
      memory:  256M
```
Maybe I wrongly understood how the fix was implemented and I should set these limits somehow differently ? Please advice.

**Did you expect to see some different?**

My understanding is that sts should get recreated with modified limits.

**Environment**

* K8ssandra Operator version:
Image:         docker.io/k8ssandra/k8ssandra-operator:v1.5.1

* Kubernetes version information:
1.25

* Kubernetes cluster kind:
AKS
