### ISSUE TITLE
Restore mapping seems to shuffle the pods during in place restores

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#1060]
When creating a MedusaRestoreJob, the restore mapping is computed by the operator and stored in the object status. It is then use by each node to figure out which backup node it should restore from.

In case of an in place restore (we're restoring a backup that was taken on the same cluster), each node should map to itself.
It doesn't seem to be the case and I can see nodes being shuffled in the restore mapping:

```
  restoreMapping:
    host_map:
      dogfood-mc-dc1-r1-sts-0:
        seed: false
        source:
          - dogfood-mc-dc1-r1-sts-1
      dogfood-mc-dc1-r1-sts-1:
        seed: false
        source:
          - dogfood-mc-dc1-r1-sts-0
      dogfood-mc-dc1-r1-sts-2:
        seed: false
        source:
          - dogfood-mc-dc1-r1-sts-2
    in_place: false
```

Also the in place nature of the backup isn't correctly identified.
In order to ensure restore safety, we need to make sure in place restored are correctly detected and restore mappings are consistent.

```[tasklist]
### Definition of Done
- [ ] when a node exists in both the source and the target clusters, it restores itself in the mapping
- [ ] in place restores are detected correctly
```
