### ISSUE TITLE
Datacenter name collision leads to data loss

### ISSUE THREAD

**Issue by ClusterJan** [k8ssandra/k8ssandra-operator#1093]
**What happened?**

We wanted to create a second K8ssandraCluster in a namespace, but only changed the cluster name. The datacenter name were the same in these two clusters. Then we noticed, that because the datacenter name has to be unique in a namespace, we changed the name of the new datacenter and then the cass-operator redeployed all PVCs, which led to complete data loss. 

**Did you expect to see something different?**

We expected that a datacenter only had to be unique in a single K8ssandraCluster not in the namespace. Furthermore, the operator should detect the collision and notice, that the configuration belongs to another installation and mustn't modify the existing cluster.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy cluster with version 3.11.16.
2. Deploy a second cluster with different cluster name and server version (4.1.2), but same datacenter name.
3. Rename the datacenter name and update the new cluster.
4. PVCs of old datacenter were reinitialized and second cluster starts along the first cluster.

**Environment**

* K8ssandra Operator version:

    `v1.9.1`
    
    

* Kubernetes version information:

    ```
      Client Version: v1.28.3
      Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
      Server Version: v1.21.12
    ```

* Kubernetes cluster kind:

    Rancher

* Manifests:

__Old cluster__
```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo-k8ssandra
spec:
  auth: false
  cassandra:
    clusterName: demo-cluster
    datacenters:
    - config:
        cassandraYaml:
          compaction_throughput_mb_per_sec: 200
          concurrent_compactors: 6
        jvmOptions:
          gc: G1GC
          heap_initial_size: 16G
          heap_max_size: 16G
      metadata:
        name: kubernetes-1
      size: 6
      stopped: false
      storageConfig:
        cassandraDataVolumeClaimSpec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1.5Ti
          storageClassName: ebs
      tolerations:
      - effect: NoSchedule
        key: cassandra
        operator: Equal
        value: "true"
    networking:
      hostNetwork: false
    perNodeConfigInitContainerImage: mikefarah/yq:4
    racks:
    - name: eu-central-1a
      nodeAffinityLabels:
        topology.kubernetes.io/zone: eu-central-1a
    resources:
      limits:
        cpu: 6
        memory: 21Gi
      requests:
        cpu: 6
        memory: 21Gi
    serverType: cassandra
    serverVersion: 3.11.16
```

- new cluster with same configuration but cluster-name "demo-cluster-4" and server version 4.1.2

* K8ssandra Operator Logs:

*Not able to access the old logs.*

**Anything else we need to know?**:

**Comment by burmanm** [comment]
Hi,

Two different things here. The operation of "rename Datacenter" is not something Cassandra supports, so what you essentially did was to delete the existing DC and create a new DC. Since you had no other DCs in the system, this will lead to data loss as you noticed. Renaming itself would have been prevented, but what the `datacenters.metadata.name` does is not configure the actual name of the Datacenter, but the created `CassandraDatacenter` instance. So, what cass-operator saw in this case is that one CassandraDatacenter was deleted and a new CassandraDatacenter was created - with no link between these instances.

This is probably something that should be prevented in the validation that the only existing Datacenter can't be deleted. Instead, the operation should be `create new dc -> rebuild from old dc -> delete old dc`. Alternatively we just change the process order, but that would have its own complications with potentially no available resources.

In case of conflicting Datacenter names, it is possible to configure the actual naming of the resource and the DatacenterName. So, if you wanted to have same datacenter name twice in the same namespace, you have to use override in the DatacenterTemplate.

So, do this for 4.1.2 cluster:

```yaml
    datacenters:
      metadata:
        name: kubernetes-1-4
      datacenterName: kubernetes-1
```

And for 3.11.16:

```yaml
    datacenters:
      metadata:
        name: kubernetes-1-3
      datacenterName: kubernetes-1
```

That way the actual Datacenter is called `kubernetes-1` in both instances in Cassandra, but the resource names do not overlap anymore. We can't do this automatically due to backwards compatibility reasons for now (unless we find a good method to detect old and new versions and adjust accordingly the existing and new datacenter names).
