### ISSUE TITLE
Make use of aggregated ClusterRoles

### ISSUE THREAD

**Issue by ClusterJan** [k8ssandra/k8ssandra-operator#1111]
**What is missing?**

The editor and viewer cluster roles manged by the Helm chart and the k8ssandra-operator are missing RBAC labels, which would allow an automatic aggregation to cluster wide roles.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregate-to-edit
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true""
```

See: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles

**Why do we need it?**

These cluster roles, e.g., `edit` can be used by GitLab runners in the Kubernetes cluster to automatically modify the state of the resources watched by the k8ssandra-operator. With this, the necessity of creating additional cluster role binding is then no longer necessary.
