### ISSUE TITLE
k8ssandra cluster upgrade fails between 3.x and 4.x versions

### ISSUE THREAD

**Issue by cnvergence** [k8ssandra/k8ssandra-operator#1119]
**What happened?**
K8ssandra cluster version upgrade is blocked because of changed defaults of `num_tokens` between cassandra versions 3.x and 4.x.
k8ssandra-operator are blocking changes to this parameter, therefore whole upgrade process is being blocked.
validation of cassandraDatacenter fails with
```
ERROR	Reconciler error	{"controller": "k8ssandracluster", "controllerGroup": "k8ssandra.io", "controllerKind": "K8ssandraCluster", "K8ssandraCluster": {"name":"demo","namespace":"k8ssandra-operator"}, "namespace": "k8ssandra-operator", "name": "demo", "reconcileID": "454e7078-e7b2-4397-9f6d-0fe0962604d7", "error": "invalid Cassandra config: tried to change num_tokens in an existing datacenter"}
k8ssandra-operator-587c474d8f-mngqm k8ssandra-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
k8ssandra-operator-587c474d8f-mngqm k8ssandra-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329
k8ssandra-operator-587c474d8f-mngqm k8ssandra-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
k8ssandra-operator-587c474d8f-mngqm k8ssandra-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274
k8ssandra-operator-587c474d8f-mngqm k8ssandra-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
k8ssandra-operator-587c474d8f-mngqm k8ssandra-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235
```

When trying to explicitly set the value of num_tokens: 16 to k8ssandraCluster, the whole process is blocked because of the validation webhook, that disallows any changes to num_tokens configuration.
```
admission webhook "vk8ssandracluster.kb.io" denied the request: num_tokens value can't be
changed
```

**Did you expect to see something different?**
Unblock version upgrade process

**Environment**

* K8ssandra Operator version:
1.10.2

* Kubernetes version information:
1.27.2

* Manifests:
```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
spec:
  cassandra:
    serverVersion: "3.11.10"
    datacenters:
      - metadata:
          name: dc1
        size: 1
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: hostpath
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
        config:
          jvmOptions:
            heapSize: 512M
        stargate:
          size: 1
          heapSize: 256M
```
```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
spec:
  cassandra:
    serverVersion: "4.1.3"
    datacenters:
      - metadata:
          name: dc1
        size: 1
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: hostpath
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
        config:
          jvmOptions:
            heapSize: 512M
        stargate:
          size: 1
          heapSize: 256M

```

* K8ssandra Operator Logs:

```
ERROR	Reconciler error	{"controller": "k8ssandracluster", "controllerGroup": "k8ssandra.io", "controllerKind": "K8ssandraCluster", "K8ssandraCluster": {"name":"demo","namespace":"k8ssandra-operator"}, "namespace": "k8ssandra-operator", "name": "demo", "reconcileID": "454e7078-e7b2-4397-9f6d-0fe0962604d7", "error": "invalid Cassandra config: tried to change num_tokens in an existing datacenter"}
k8ssandra-operator-587c474d8f-mngqm k8ssandra-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
k8ssandra-operator-587c474d8f-mngqm k8ssandra-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:329
k8ssandra-operator-587c474d8f-mngqm k8ssandra-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
k8ssandra-operator-587c474d8f-mngqm k8ssandra-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274
k8ssandra-operator-587c474d8f-mngqm k8ssandra-operator sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
k8ssandra-operator-587c474d8f-mngqm k8ssandra-operator 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235
```

**Anything else we need to know?**:
See also: https://github.com/k8ssandra/k8ssandra/issues/1029
