### ISSUE TITLE
Medusa purge task not running 

### ISSUE THREAD

**Issue by ClusterJan** [k8ssandra/k8ssandra-operator#1121]
**What happened?**

When creating a medusa purge task, the task get's started by the k8ssandra-operator, but nothing further happens.

**Did you expect to see something different?**

The obsolete medusa backups should get deleted. 

**How to reproduce it (as minimally and precisely as possible)**:

Have a running K8ssandra cluster with backups that are out of the rotation and run a Purge task:

```yaml
apiVersion: medusa.k8ssandra.io/v1alpha1
kind: MedusaTask
metadata:
  name: purge-backups-1
spec:
  cassandraDatacenter: kubernetes-1
  operation: purge
```
`

**Environment**

* K8ssandra Operator version: 1.10.3
* Cassandra version: 4.1.3
* Medusa version: 0.16.3
* Kubernetes version: 1.24.17

**Anything else we need to know?**:
Discussed in Discord.
