### ISSUE TITLE
Helm Chart v1.10.3: template for k8ssandraclusters CustomResourceDefinition has uninterpolated strings / missing Helm templating

### ISSUE THREAD

**Issue by frimik** [k8ssandra/k8ssandra-operator#1135]
<!--

Feel free to ask questions on Discord at https://discord.com/invite/y4s64xC9 or in the forum at https://forum.k8ssandra.io/. 
-->

**What happened?**

After  helm install of k8ssandra-operator v1.10.3, the k8ssandraclusters CRD contains the following annotation:
`cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE_K8S)/$(CERTIFICATE_NAME_K8S)`

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE_K8S)/$(CERTIFICATE_NAME_K8S)
    controller-gen.kubebuilder.io/version: v0.12.0
```

**How to reproduce it (as minimally and precisely as possible)**:

```sh
helm install --version 1.10.3 k8ssandra-operator k8ssandra/k8ssandra-operator -n k8ssandra-operator --set global.clusterScoped=true --create-namespace

kubectl get crd k8ssandraclusters.k8ssandra.io -o jsonpath='{.metadata.annotations}'
# {"cert-manager.io/inject-ca-from":"$(CERTIFICATE_NAMESPACE_K8S)/$(CERTIFICATE_NAME_K8S)","controller-gen.kubebuilder.io/version":"v0.12.0"}%                                                                                                                                                                                                                                           
```
