### ISSUE TITLE
DC names are not properly sanitized

### ISSUE THREAD

**Issue by olim7t** [k8ssandra/k8ssandra-operator#1141]
If a cluster declares a datacenter with invalid characters:
```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  namespace: k8ssandra-operator
  name: demo
spec:
  cassandra:
    serverVersion: 4.1.0
    datacenters:
      - metadata:
          name: dc_1   # <<< invalid Kubernetes name
        size: 1
        racks:
          - name: rack1
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Mi
```

The name is not properly sanitized, which leads to this error:
```
ConfigMap "demo-dc_1-metrics-agent-config" is invalid: metadata.name: Invalid value: "demo-dc_1-metrics-agent-config": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

The problem is not limited to that ConfigMap: even after fixing it ([here](https://github.com/k8ssandra/k8ssandra-operator/blob/20398713516abf74912f6d4226d683a3f8c3def5/pkg/telemetry/cassandra_agent/cassandra_agent_config.go#L138)), the invalid name causes another error when the operator tries to create the `CassandraDatacenter`.

We should either reject invalid DC names in the validation webhook, or sanitize them and maybe use the original value as the `datacenterName`.
