### ISSUE TITLE
Should image config customisations be handled atomically?

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#1142]
**What happened?**

A user asked a question on the discord server, where he'd put a custom image configuration in the spec and received an unexpected result. 

https://discord.com/channels/836217371453685760/836217371453685763/1184189918457639035

```
spec:
  reaper:
    containerImage:
      registry: 'docker.mirrors.local'


Result:
  reaper:
    ServiceAccountName: default
    containerImage:
      registry: docker.mirrors.local
      tag: latest


expected:
  reaper:
    containerImage:
      name: cassandra-reaper
      registry: docker.mirrors.local
      repository: thelastpickle
      tag: 3.4.0
```

I think this is happening because  any override of the image configuration overrides the entirety of the default image configuration, and `latest` is the default value for the image tag (so filled in by the API server) when left unspecified.

If this behaviour is unexpected (and I think it is) it might be advantageous to merge the user and default specs using goalesce so that OUR defaults are propagated instead of the k8s API server defaults.

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/K8OP-57) by [Unito](https://www.unito.io)
┆Issue Number: K8OP-57
