### ISSUE TITLE
Schedule purges on clusters that have Medusa configured

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#1154]
Each cluster with Medusa enabled should have purges scheduled automatically once per day.
This can be done by creating a CronJob which will create a MedusaTask for a purge operation. The CronJobs should be created by the K8ssandraCluster controller and use a finalizer for cleanup as such resources may live in the dataplanes. The MedusaTask resources need to be in the same cluster and namespace as the datacenter they relate to.

Here's a base for the CronJob spec:

```
spec:
  schedule: 0 0 * * *
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          name: k8ssandra-purge-backups
        spec:
          containers:
            - name: medusa-purge-cronjob
              image: bitnami/kubectl:1.17.3
              command:
                - bin/bash
                - '-c'
                - >-
                  printf "apiVersion: medusa.k8ssandra.io/v1alpha1\nkind:
                  MedusaTask\nmetadata:\n  name: purge-backups-timestamp\n 
                  namespace: k8ssandra-operator\nspec:\n  cassandraDatacenter:
                  dc2\n  operation: purge" | sed "s/timestamp/$(date
                  +%Y%m%d%H%M%S)/g" | kubectl apply -f -
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
```

```[tasklist]
### Definition of Done
- [ ] A CronJob is created for each DC where Medusa is configured, each creating a new purge MedusaTask on a daily basis at midnight
- [ ] The CronJobs need to have a finalizer with a cleanup operation being performed in the K8ssandraCluster controller
```
