### ISSUE TITLE
Add a field to reference a MedusaConfiguration resource in the K8ssandraCluster API

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#1158]
The Medusa spec would contain an additional [ObjectReference](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-reference/) field to set the reference to the MedusaConfiguration object:

```yaml
  medusa:
    medusaConfigurationRef:
      name: medusa-storage1
      namespace: ns1
      api: v1alpha1
      kind: MedusaConfiguration
    storageProperties:
      prefix: my-cluster
      transferMaxBandwidth: 150MB/s
```

The above would generate Medusa storage settings [here](https://github.com/k8ssandra/k8ssandra-operator/blob/main/pkg/medusa/reconcile.go#L56), with the data stored in the medusa-storage-bucket1 object, and override the prefix and transfer max bandwidth with the provided values.
Merging of both structures would be done with Goalesce, prioritizing the values from storageProperties.
The CreateMedusaIni() function would be refactored to take a MedusaSpec object instead of a K8ssandraCluster one, which would be the result of the above merge.

An additional check would make sure the prefix is explicitly set in storageProperties when a medusaConfigurationRef is set. This will reduce the odds of putting backups from multiple clusters in the same folder.

```[tasklist]
### Definition of Done
- [x] The K8ssandraCluster spec has a new optional `medusa.medusaConfigurationRef` field which can point to an existing MedusaConfiguration resource
- [x] During the reconcile, the controller will merge the MedusaConfiguration object fields with the storageProperties ones, using Goalesce and prioritizing the latter
- [x] The prefix is mandatory in the storageProperties when using a MedusaConfiguration ref
```
