### ISSUE TITLE
Local backup not working in Medusa

### ISSUE THREAD

**Issue by mritunjaysharma394** [k8ssandra/k8ssandra-operator#1185]
**What happened?**
I was trying to use medusa backup with local storage, however it fails with error:
```
The K8ssandraCluster "demo" is invalid: spec.medusa.storageProperties.storageProvider: 
Unsupported value: "local": supported values: "google_storage", "azure_blobs", "s3", 
"s3_compatible", "s3_rgw", "ibm_storage


```
**Did you expect to see something different?**
This should not have thrown this error as the base CRD supposedly supports `-local` https://github.com/k8ssandra/k8ssandra-operator/blob/ff37de8258c761d3c1eaa234be098002e7732b86/config/crd/bases/medusa.k8ssandra.io_medusas.yaml#L280

I this is happening because we have probably missed to define it here https://github.com/k8ssandra/k8ssandra-operator/blob/ff37de8258c761d3c1eaa234be098002e7732b86/apis/medusa/v1alpha1/medusa_types.go#L30

**How to reproduce it (as minimally and precisely as possible)**:

Apply this manifest once you have k8ssandra operator installed:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
spec:
  cassandra:
    serverVersion: "4.0.1"
    datacenters:
      - metadata:
          name: dc1
        size: 3
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 512M
        stargate:
          size: 1
          heapSize: 256M
  medusa:
    storageProperties:
      storageProvider: local # Use local storage for Medusa backups
      # Can be either of google_storage, azure_blobs, s3, s3_compatible, s3_rgw or ibm_storage 
      podStorage:
        size: 5Gi
      storageSecretRef:
        name: medusa-bucket-key
      # Name of the storage bucket
      bucketName: k8ssandra-medusa
      # Whether or not to use SSL to connect to the storage backend
      secure: false 
  ```
**Environment**

* K8ssandra Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* K8ssandra Operator Logs:

```
insert K8ssandra Operator logs relevant to the issue here
```

**Anything else we need to know?**:
