### ISSUE TITLE
K8ssandraCluster status should report status of CassandraDatacenter and Stargate objects

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#12]
The K8ssandraCluster status should include info on all of the CassandraDatacenters. At a bare minimum it should indicate whether they are ready. CassandraDatacenter has a number of status conditions including,

* Ready
* Updating
* ScalingUp
* ScalingDown
* RollingRestart
* ReplacingNodes

We may just want to surface these conditions in the K8ssandraCluster status.

We also need to incorporate Stargate in the K8ssandraCluster status. 

I think it makes sense to surface the status of each component object in the K8ssandraCluster status. This way we get a status of the entire data plane centralized in one place.

I had something like this in mind:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  k8sContextsSecret: k8s-contexts
  cassandra:
    cluster: test
    datacenters:
      - metadata:
          name: dc1
        k8sContext: kind-k8ssandra-0
        size: 3
        serverVersion: "3.11.10"
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        stargate:
          size: 1
      - metadata:
          name: dc2
        k8sContext: kind-k8ssandra-1
        size: 3
        serverVersion: "3.11.10"
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        stargate:
          size: 1
status:
  dc1:
    cassandra:
      cassandraOperatorProgress: Ready
      conditions:
        - lastTransitionTime: "2021-08-03T13:46:00Z"
           message: ""
           reason: ""
           status: "False"
           type: ScalingUp
      lastServerNodeStarted: "2021-08-03T13:45:24Z"
      nodeStatuses:
        test-dc1-default-sts-0:
          hostID: 5a530a24-d72d-412f-82c9-a304e0c03c37
      observedGeneration: 1
      quietPeriod: "2021-08-03T13:46:10Z"
      superUserUpserted: "2021-08-03T13:46:05Z"
      usersUpserted: "2021-08-03T13:46:05Z"
    stargate:
      availableReplicas: 1
      conditions:
        - lastTransitionTime: "2021-08-03T13:47:00Z"
          status: "True"
          type: Ready
      deploymentRef: test-dc1-stargate-deployment
      progress: Running
      readyReplicas: 1
      readyReplicasRatio: 1/1
      replicas: 1
      serviceRef: test-dc1-stargate-service
      updatedReplicas: 1
```

Only a subset of the status fields are included in the example, but it is enough to illustrate how things look and are organized. The K8ssandraStatus cluster status includes an inlined map that is keyed off of the CassandraDatacenter names. The map value is an object that includes that includes two keys - `cassandra` and `stargate`. The CassandraDatacenter status comes under `cassandra` and the Stargate status comes under `stargate`. When we migrate the Reaper controller, we would add a `reaper` key for the Reaper status.

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-587) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-587
┆Priority: Medium
