### ISSUE TITLE
K8SSAND-880 ⁃ Implement merge semantics for Cassandra configs

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#122]
This is a follow up to https://github.com/k8ssandra/k8ssandra-operator/pull/94#discussion_r703695051.  When #94 is merged that will give you the ability to declare Cassandra configs at the cluster and/or DC levels. For example, we could have something like this:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  cassandra:
    cluster: test
    serverVersion: "3.11.10"
    serverImage: emerkle826/cass-mgmtapi:3.11.11-v0.1.28
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      cassandraYaml:
        auto_snapshot: false
        memtable_flush_writers: 1
        commitlog_segment_size_in_mb: 2
        concurrent_compactors: 1
        compaction_throughput_mb_per_sec: 0
        sstable_preemptive_open_interval_in_mb: 0
        key_cache_size_in_mb: 0
        thrift_prepared_statements_cache_size_mb: 1
        prepared_statements_cache_size_mb: 1
        start_rpc: false
        slow_query_log_timeout_in_ms: 0
        counter_cache_size_in_mb: 0
        concurrent_reads: 2
        concurrent_writes: 2
        concurrent_counter_writes: 2
      jvmOptions:
        heapSize: "512M"
    datacenters:
      - metadata:
          name: dc1
        k8sContext: kind-k8ssandra-0
        size: 3
      - metadata:
          name: dc2
        k8sContext: kind-k8ssandra-1
        size: 3
```

No configs are defined at the DC level for dc1 or dc2, so they will both get the settings declared at the cluster level. Now let's say we have this:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  cassandra:
    cluster: test
    serverVersion: "3.11.10"
    serverImage: emerkle826/cass-mgmtapi:3.11.11-v0.1.28
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      cassandraYaml:
        auto_snapshot: false
        memtable_flush_writers: 1
        commitlog_segment_size_in_mb: 2
        concurrent_compactors: 1
        compaction_throughput_mb_per_sec: 0
        sstable_preemptive_open_interval_in_mb: 0
        key_cache_size_in_mb: 0
        thrift_prepared_statements_cache_size_mb: 1
        prepared_statements_cache_size_mb: 1
        start_rpc: false
        slow_query_log_timeout_in_ms: 0
        counter_cache_size_in_mb: 0
        concurrent_reads: 2
        concurrent_writes: 2
        concurrent_counter_writes: 2
      jvmOptions:
        heapSize: "512M"
    datacenters:
      - metadata:
          name: dc1
        k8sContext: kind-k8ssandra-0
        config:
          cassandraYaml:
            concurrent_reads: 4
            concurrent_writes: 10
            concurrent_counter_writes: 2
        size: 3
      - metadata:
          name: dc2
        k8sContext: kind-k8ssandra-1
        size: 3
```

dc1 overrides the cluster-level settings while dc2 still inherits them. We should provide merge semantics instead of it being mutually exclusive as it is here. With merge semantics dc1 would inherit all of the C* configs declared at the cluster level except for the ones that it overrides.

We need to decide whether we want to do this for all CassandraDatacenter properties that are exposed. Note that with Stargate CRD, we are using override semantics currently. We may want to be consistent across the board.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-880) by [Unito](https://www.unito.io)
┆epic: Passthrough Cassandra Configuration
┆fixVersions: k8ssandra-operator-v1.1.0
┆friendlyId: K8SSAND-880
┆priority: Medium
