### ISSUE TITLE
Validating webhook rejects updates if the server version is declared at the DC level

### ISSUE THREAD

**Issue by olim7t** [k8ssandra/k8ssandra-operator#1222]
The fix for #1119 parses the Cassandra version during a cluster update: 
```golang
cassVersion, err := semver.NewVersion(oldCluster.Spec.Cassandra.ServerVersion)
```
([source](https://github.com/k8ssandra/k8ssandra-operator/commit/554225264dd328aaf70b55666f71fd5187ba20ad#diff-b45565c4bbd47954036865bbbb5d48b9fb5adba73a07d68945196335fe65c3f0R123))

However, our CRD allows that version to be omitted, if it is declared at the DC level:
```yaml
spec:
  cassandra:
    # no serverVersion here
    datacenters:
      - metadata:
          name: dc1
        serverVersion: 4.1.0
```

If a cluster is created in that manner, and one later tries to update it, the validating webhook rejects the update:
```
DEBUG controller-runtime.webhook.webhooks wrote response {
  "webhook": "/validate-k8ssandra-io-v1alpha1-k8ssandracluster",
  "code": 403,
  "reason": "Invalid Semantic Version",
  [...]
```

The code should consider the DC-level version if necessary. I'm not sure of the exact semantics used by the operator (can both be present? can DCs declare different versions?), so this will require a preliminary analysis.
