### ISSUE TITLE
Non-ASCII characters in DC name are not handled correctly

### ISSUE THREAD

**Issue by olim7t** [k8ssandra/k8ssandra-operator#1258]
(this assumes that #1252 is fixed first)

DC names can contain non-ASCII unicode characters, for example `Cql_DåtåCenter1`. But a `K8ssandraCluster` with such a DC name gets stuck waiting for the DC to update:
```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  namespace: test
  name: k8s-cluster
spec:
  cassandra:
    serverVersion: 4.1.0
    clusterName: Cql_Cluster
    datacenters:
      - metadata:
          name: k8s-dc1
        datacenterName: Cql_DåtåCenter1
        size: 1
        racks:
          - name: Cql_Rack1
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Mi
```
The following error shows up in the cass-operator logs:
```
ERROR	incorrect status code when calling Node Management Endpoint { ... "name": "k8s-dc1", "statusCode": 500,
    "error": "incorrect status code of 500 when calling endpoint"}
github.com/k8ssandra/cass-operator/pkg/httphelper.callNodeMgmtEndpoint
	/workspace/pkg/httphelper/client.go:1183
github.com/k8ssandra/cass-operator/pkg/httphelper.(*NodeMgmtClient).CallCreateRoleEndpoint
	/workspace/pkg/httphelper/client.go:318
github.com/k8ssandra/cass-operator/pkg/reconciliation.(*ReconciliationContext).upsertUser
	/workspace/pkg/reconciliation/reconcile_racks.go:838
github.com/k8ssandra/cass-operator/pkg/reconciliation.(*ReconciliationContext).CreateUsers
	/workspace/pkg/reconciliation/reconcile_racks.go:902
github.com/k8ssandra/cass-operator/pkg/reconciliation.(*ReconciliationContext).ReconcileAllRacks
	/workspace/pkg/reconciliation/reconcile_racks.go:2424
github.com/k8ssandra/cass-operator/pkg/reconciliation.(*ReconciliationContext).CalculateReconciliationActions
	/workspace/pkg/reconciliation/handler.go:68
github.com/k8ssandra/cass-operator/internal/controllers/cassandra.(*CassandraDatacenterReconciler).Reconcile
```
And in the Cassandra pod's `server-system-logger` container:
```
Cannot achieve consistency level ONE" while executing SELECT * FROM system_auth.roles WHERE role = 'cassandra' ALLOW FILTERING
```
Trying to connect to the pod directly with CQLSH yields a similar error:
```
Unable to perform authentication: Cannot achieve consistency level LOCAL_QUORUM
```

This suggests a problem with system keyspaces replication settings, although the annotation on the `K8ssandraCluster` looks correct:
```yaml
k8ssandra.io/initial-system-replication: '{"Cql_DåtåCenter1":1}'
```

Note that this works correctly for a standalone `CassandraDatacenter`.
