### ISSUE TITLE
spec.cassandra.datacenters.datacenterName - per node config map name not sanitized

### ISSUE THREAD

**Issue by mk01** [k8ssandra/k8ssandra-operator#1259]
## Bug Report

**Describe the bug**
with k8ssandra-operator 1.13.0 - tried to name datacenter as "dc_ops_test" with "datacenterName" field.
reconsiliation failed with:
```
Warning  Reconcile Error  2m30s (x27 over 87m)  k8ssandracluster-controller  ConfigMap "dev-cluster-dc_ops_test-per-node-config" is invalid: metadata.name: Invalid value: "dev-cluster-dc_ops_test-per-node-config": ....
```

**Expected behavior**
all fields natively used by k8s should be sanitized as per the description of this field in CRD:
```
kubectl explain k8c.spec.cassandra.datacenters.datacenterName
```

**Environment (please complete the following information):**

* Helm charts version info
```
k8ssandra/k8ssandra-operator	chart: 1.13.0     app: 1.13.0
```

* Helm charts user-supplied values
```
  .....
  datacenters:
    - datacenterName: dc_ops_test
      metadata:
        name: dc-ops-test
      racks:
      - name: eu-west-1c
        nodeAffinityLabels:
          topology.kubernetes.io/zone: eu-west-1c
      - name: eu-west-1b
        nodeAffinityLabels:
          topology.kubernetes.io/zone: eu-west-1b
      size: 2
      stopped: false
  .....
```

* Kubernetes version information:
```
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.28.6-eks-508b6b3
```

* Kubernetes cluster kind:
```
eks
```
