### ISSUE TITLE
Backward incompatibility in Reaper authentication when upgrading from 1.10 to 1.12

### ISSUE THREAD

**Issue by c3-clement** [k8ssandra/k8ssandra-operator#1269]
**What happened?**

We have multiple K8ssandra clusters running on k8ssandra-operator `v1.10` with the following Reaper spec:
```yaml
spec:
  reaper:
    uiUserSecretRef: {}
```

`k8ssandra-operator` will generate a secret named `<cluster-name>-reaper-ui`. I can use the username and password contained in this secret to log in to the Reaper UI.
In the Reaper Deployment, the env var `REAPER_AUTH_ENABLED` is set to `"true"`.

After upgrading k8ssandra-operator to `v1.12`, it's possible to login into Reaper UI without authenticating.
Accessing `/webui/` will not redirect the user to the login page. 
In the Reaper Deployment, the env var `REAPER_AUTH_ENABLED` is now set to `"false"`.

I believe that this backward incompatibility has been introduced in https://github.com/k8ssandra/k8ssandra-operator/pull/1163 :
Prior to `v1.12`, setting `uiUserSecretRef` to `{}` will trigger Reaper UI secret reconciliation and `REAPER_AUTH_ENABLED` will be set `true`.

After `v1.12`, `uiUserSecretRef` has to be set to `null` to trigger the same behavior.

**Did you expect to see something different?**

I expect Reaper UI authentication to still be enabled when upgrading from `v1.10` to `v1.12` .

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a K8ssandra cluster with k8ssandra-operator `v1.10` with the following Reaper spec:
```yaml
spec:
  reaper:
    uiUserSecretRef: {}
```

2. Access to Reaper UI by using the reaper-ui secret
3. Upgrade k8ssandra-operator to `v1.12` without changing the k8ssandra cluster spec
4. Try to access Reaper UI as in step 2.

**Environment**

* K8ssandra Operator version:
`v1.10` and `v1.12`

* Kubernetes version information:
`1.27`

* Kubernetes cluster kind:
AKS

* Manifests:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
spec:
  reaper:
    uiUserSecretRef: {}
```
