### ISSUE TITLE
Integration with Istio Sidecar

### ISSUE THREAD

**Issue by jdamato-mitre** [k8ssandra/k8ssandra-operator#1276]
**What did you do?**
Attempted to setup a single cassandra single node cluster with istio-injection enabled.

```
helm repo add k8ssandra https://helm.k8ssandra.io/stable
helm repo add jetstack https://charts.jetstack.io
helm repo update
kubectl create ns cert-manager
helm install cert-manager jetstack/cert-manager --namespace cert-manager --set installCRDs=true
kubectl create ns k8ssandra-operator
kubectl label namespace k8ssandra-operator istio-injection=enabled --overwrite
helm install k8ssandra-operator k8ssandra/k8ssandra-operator -n k8ssandra-operator --version 1.13.0
kubectl apply --wait -f k8ssandra.yaml
```

The error occurs when creating the `K8ssandraCluster`. 
```
Error from server (InternalError): error when creating "k8ssandra.yaml": Internal error occurred: failed calling webhook "vk8ssandracluster.kb.io": failed to call webhook: Post "https://k8ssandra-operator-webhook-service.k8ssandra-operator.svc:443/validate-k8ssandra-io-v1alpha1-k8ssandracluster?timeout=10s": tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match k8ssandra-operator-webhook-service.k8ssandra-operator.svc
```

This is my kk8ssandra.yaml file

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-retain-lrs
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
spec:
  cassandra:
    serverVersion: "4.0.1"
    datacenters:
      - metadata:
          name: datacenter1
        size: 1
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: managed-premium-retain-lrs
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heap_initial_size: 512Mi
            heap_max_size: 512Mi
```

**Did you expect to see some different?**
Cassandra Database pod created with sidecar

**Environment**

* K8ssandra Operator version: 

    `1.13.0`
    
    

* Kubernetes version information: 

    `1.26.12`
    

* Kubernetes cluster kind: 

    AKS

* Manifests:

```
insert manifests relevant to the issue
```

* K8ssandra Operator Logs:

```
insert K8ssandra Operator logs relevant to the issue here
```

**Anything else we need to know?**:
