### ISSUE TITLE
K8SSAND-588 ⁃ Apply labels to CassandraDatacenters

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#13]
k8ssandra-operator should apply common used labels to each CassandraDatacenter it creates.  See https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ for some recommended labels.

When a user creates/updates a K8ssandraCluster, he should be able to set labels for the CassandraDatacenters. User-defined labels should be merged with those set by k8ssandra-operator.

There should be unit tests to verify labels are set correctly.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-588) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-588
┆Priority: Medium

**Comment by jsanda** [comment]
Closing this because it has already been addressed. Each CassandraDatacenter is configured with the following labels:

* app.kubernetes.io/name
* app.kubernetes.io/part-of
* app.kubernetes.io/component
* app.kubernetes.io/created-by
* k8ssandra.io/cluster-name
* k8ssandra.io/cluster-namespace

And here is an example of labels with values:

```yaml
app.kubernetes.io/component: cassandra
app.kubernetes.io/created-by: k8ssandracluster-controller
app.kubernetes.io/name: k8ssandra-operator
app.kubernetes.io/part-of: k8ssandra
k8ssandra.io/cluster-name: test
k8ssandra.io/cluster-namespace: multi-dc-kgsk9g
```
