### ISSUE TITLE
Reaper needs a static image filesystem to enable readOnlyRootFilesystem

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#1329]
When adding the following security context settings to Reaper, it fails to start complaining about access rights to `/etc/cassandra-reaper`:

```
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
```

We need to be able to run the Reaper pods with read only root FS.

```[tasklist]
### Definition of Done
- [ ] https://github.com/thelastpickle/cassandra-reaper/issues/1506
- [ ] an emptyDir volume is mounted in both init/containers to host the config files in writeable form
```
