### ISSUE TITLE
K8ssandraCluster kind doesn't support pod annotations needed to inject pods into service mesh (linkerd, Istio...)

### ISSUE THREAD

**Issue by sanararoj** [k8ssandra/k8ssandra-operator#1344]
**What is missing?**

K8ssandraCluster.spec.cassandra is missing podTemplateSpec, that could allow me to include annotations into cassandra pods, for instance to use linkerd service mesh implementation to enable mutualTLS in cassandra pods. This is feasible if instead of using k8ssandra-operator , I use directly cass-operator and CassandraDatacenter kind

```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: cassandra
spec:
  superuserSecretName: cassandra
  clusterName: local
  serverType: cassandra
  serverVersion: "4.0.1"
  managementApiAuth:
    insecure: {}
  size: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  resources:
    requests:
      memory: 1Gi
      cpu: 1000m
  podTemplateSpec:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.alpha.linkerd.io/proxy-enable-native-sidecar: "true"
        config.linkerd.io/opaque-ports: "9042"
        config.linkerd.io/default-inbound-policy: all-authenticated
    spec:
      containers:
        - name: "cassandra"
  racks:
    - name: rack1
  config:
    jvm-server-options:
      heapSize: "512M"
```

**Why do we need it?**

https://docs.k8ssandra.io/reference/crd/releases/k8ssandra-operator-releases/k8ssandra-operator-crds-1.0/#k8ssandraclusterspec

To include podTemplateSpec in K8ssandraCluster kind. So annotations, I put there can be transmitted in to cassandra pods

**Environment**
Docker-Desktop, local laptop

* K8ssandra Operator version:

1.16.0
    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:
