### ISSUE TITLE
Custom registry configuration affect default used tags

### ISSUE THREAD

**Issue by julienbaladier** [k8ssandra/k8ssandra-operator#1396]
**What happened?**

I am trying to use a private registry to pull images by following these [instructions](https://docs.k8ssandra.io/install/image-config/).

When setting only the `spec.reaper.containerImage.registry` and `spec.medusa.containerImage.registry` properties, it seems to affect the tags that are used as well. Instead of using the default fixed versions, it is using the `latest` tags for the repear and medusa images.

```txt
~$ kubectl get pods -n julien thehive-dc-r2-sts-0  -o json | jq -r '.spec.initContainers[].image'
cr.k8ssandra.io/k8ssandra/cass-management-api:4.1.5-ubi8
cr.k8ssandra.io/k8ssandra/k8ssandra-client:v0.5.0
docker.io/k8ssandra/medusa:0.22.0

~$ kubectl get pods -n julien thehive-dc-r2-sts-0  -o json | jq -r '.spec.containers[].image'
cr.k8ssandra.io/k8ssandra/cass-management-api:4.1.5-ubi8
docker.io/k8ssandra/medusa:0.22.0
cr.k8ssandra.io/k8ssandra/system-logger:v1.22.0

~$ kubectl get pods -n julien thehive-dc-reaper-58d5d9b994-thxnj  -o json | jq -r '.spec.containers[].image'
docker.io/thelastpickle/cassandra-reaper:3.6.1
~$ kubectl get pods -n julien thehive-dc-reaper-58d5d9b994-thxnj  -o json | jq -r '.spec.initContainers[].image'
docker.io/thelastpickle/cassandra-reaper:3.6.1
```

**Did you expect to see something different?**

I would have expected the tags not to be affected since I am only providing the information I case about. With the current behaviour I need to provide the tags and I need to update them each time the version changes.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create the `K8ssandraCluster` without setting `spec.reaper.containerImage.registry` and `spec.medusa.containerImage.registry`.
2. Check the images versions used for each container.
3. Delete the `K8ssandraCluster`.
4. Set the `spec.reaper.containerImage.registry` and `spec.medusa.containerImage.registry` perperties with the default registry: `docker.io`.
5. Check the images versions used, they are different.

**Environment**

* K8ssandra Operator version: v1.18.0

* Kubernetes version information:

    ```txt
    Client Version: v1.30.1
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.30.3-eks-2f46c53
    ```

* Kubernetes cluster kind: EKS

* Manifests:

```yaml
---
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  auth: true
  cassandra:
    serverVersion: "4.1.5"
    serverImage: <custom-registry>/k8ssandra/cass-management-api:4.1.5-ubi8
    serviceAccount: cassandra
    superuserSecretRef:
      name: test-superuser
    telemetry:
      mcac:
        enabled: false
      prometheus:
        enabled: true
    datacenters:
      - metadata:
          name: dc
        size: 3
        racks:
          - name: r1
            nodeAffinityLabels:
              "topology.kubernetes.io/zone": eu-west-1a
          - name: r2
            nodeAffinityLabels:
              "topology.kubernetes.io/zone": eu-west-1b
          - name: r3
            nodeAffinityLabels:
              "topology.kubernetes.io/zone": eu-west-1c
        perNodeConfigInitContainerImage: <custom-registry>/mikefarah/yq:4
        storageConfig:
          cassandraDataVolumeClaimSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
  reaper:
    cassandraUserSecretRef:
      name: test-reaper
    uiUserSecretRef:
      name: test-reaper-ui
    containerImage:
      registry: <custom-registry>
      # tag: 3.6.1
      pullSecretRef:
        name: docker-cfg
    telemetry:
      mcac:
        enabled: false
      prometheus:
        enabled: true
    deploymentMode: SINGLE
  medusa:
    containerImage:
      registry: <custom-registry>
      # tag: 0.22.0
      pullSecretRef:
        name: docker-cfg
    cassandraUserSecretRef:
      name: test-medusa
    purgeBackups: false
    storageProperties:
      prefix: test
      credentialsType: role-based
      storageSecretRef:
        name: ""
      storageProvider: s3
      region: eu-west-1
      bucketName: s3-test-cassandra
      sslVerify: true
      maxBackupAge: 5
      maxBackupCount: 30
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cassandra
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::XXXXXXXXXXXX:role/iam-role-sa-test-cassandra"
imagePullSecrets:
  - name: docker-cfg
```
