### ISSUE TITLE
Prometheus target dropped when using k8c.spec.cassandra.datacenters.datacenterName

### ISSUE THREAD

**Issue by Arun-Trichy** [k8ssandra/k8ssandra-operator#1404]
**What happened?**
When we override the _k8c.spec.cassandra.datacenters.datacenterName_ also enabling telemetry for monitoring, Prometheus is dropping the target due to selector label mismatch.

**Did you expect to see something different?**
Prometheus should be able to monitor the cassandra instance even with _datacenterName_ override.

**How to reproduce it (as minimally and precisely as possible)**:
Enable telemetry & override the datacenterName

**Environment**

* K8ssandra Operator version: v1.15.0

* Kubernetes version information:
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1

* Kubernetes cluster kind:
kind cluster v1.29.1

* Manifests:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: axone-dsecluster
spec:
  cassandra:
    config:
      cassandraYaml:
        ...
      dseYaml:
        ...
      jvmOptions:
        ...
    datacenters:
    - datacenterName: Cassandra
      metadata:
        name: dc1
      racks:
      - name: rack1
      resources:
        limits:
          memory: 40Gi
        requests:
          cpu: 3
          memory: 17.5Gi
      size: 1
      storageConfig:
        cassandraDataVolumeClaimSpec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 300Gi
    serverType: dse
    serverVersion: 6.8.47
    telemetry:
      cassandra:
        endpoint:
          address: 0.0.0.0
          port: "9000"
      mcac:
        enabled: false
      prometheus:
        enabled: true
```

**Anything else we need to know?**:
Selector used in SVC vs ServiceMonitor
![image](https://github.com/user-attachments/assets/ffd84c3f-9b37-41fa-8c7c-7a40f1879e4e)
<img width="978" alt="image" src="https://github.com/user-attachments/assets/c2a3eea8-4b90-429e-857d-6cbf934005ae">
Prometheus Target Empty
![image](https://github.com/user-attachments/assets/745378ed-fa15-4755-9fa1-8325418f538d)
