### ISSUE TITLE
Stargate pod fails to deploy on MacOS/kind

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#142]
**What is missing?**

Using the single-cluster install instructions the stargate pod appears to fail when running on MacOS/Kind.

```
setup-kind-multicluster.sh --kind-worker-nodes 4
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.yaml

K8SSANDRA_OPERATOR_HOME=$(mktemp -d)
cat <<EOF >$K8SSANDRA_OPERATOR_HOME/kustomization.yaml
resources:
- github.com/k8ssandra/k8ssandra-operator/config/default?ref=main

images:
- name: k8ssandra/k8ssandra-operator
  newTag: 7a2d65bb
EOF

kustomize build $K8SSANDRA_OPERATOR_HOME | kubectl apply -f -
```

We then deploy a cluster using 

```
cat <<EOF | kubectl apply -f -
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
spec:
  cassandra:
    cluster: demo
    serverVersion: "4.0.0"
    datacenters:
      - metadata:
          name: dc1
        size: 3
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 512M
        stargate:
          size: 1
          heapSize: 256M
EOF
```

After waiting for the cluster to do its thing, we end up seeing the following: 

```
NAME                                                   READY   STATUS    RESTARTS   AGE
cass-operator-controller-manager-59c874d45d-5ldbj      1/1     Running   0          25m
demo-dc1-default-stargate-deployment-d84558d8f-m4scv   0/1     Pending   0          3m12s
demo-dc1-default-sts-0                                 2/2     Running   0          11m
demo-dc1-default-sts-1                                 2/2     Running   0          11m
demo-dc1-default-sts-2                                 2/2     Running   0          11m
k8ssandra-operator-d94c855-lc99m                       1/1     Running   0          25m
```

With stargate pending because of scheduling issues:

```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  39s (x5 over 3m51s)  default-scheduler  0/4 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 3 node(s) didn't match pod affinity/anti-affinity rules, 3 node(s) didn't match pod anti-affinity rules.
```

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-904) by [Unito](https://www.unito.io)
┆Fix Versions: k8ssandra-operator-1.0.0-alpha.1
┆Issue Number: K8SSAND-904
┆Priority: Medium
