### ISSUE TITLE
reaper web ui  auth disable fail

### ISSUE THREAD

**Issue by xiongmozhou** [k8ssandra/k8ssandra-operator#1429]
yaml fil
```yaml
```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
spec:
  # cluster-level Stargate configuration goes here
  stargate:
    size: 1
    resources:
      requests:
        cpu: 1000m
        memory: 1Gi
  # cluster-level Reaper configuration goes here
  reaper:
    uiUserSecretRef: {}
    resources:
      requests:
        cpu: 1000m
        memory: 1Gi
  # cluster-level Medusa configuration goes here
  medusa:
    storageProperties:
      # Can be either of google_storage, azure_blobs, s3, s3_compatible, s3_rgw or ibm_storage
      storageProvider: s3_compatible
      # Name of the secret containing the credentials file to access the backup storage backend
      storageSecretRef:
        name: medusa-bucket-key
      # Name of the storage bucket
      bucketName: k8ssandra-medusa
      # Prefix for this cluster in the storage bucket directory structure, used for multitenancy
      prefix: test
      # Host to connect to the storage backend (Omitted for GCS, S3, Azure and local).
      host: minio-svc.minio.svc.cluster.local
      # Port to connect to the storage backend (Omitted for GCS, S3, Azure and local).
      port: 9000
      # Region of the storage bucket
      # region: us-east-1

      # Whether or not to use SSL to connect to the storage backend
      secure: false
  cassandra:
    serverVersion: "4.0.1"
    datacenters:
      - metadata:
          name: dc1
        size: 3
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: open-local-lvm
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 512M
```

k8ssandra-operator version is 1.18

![image2024-10-10_16-54-43](https://github.com/user-attachments/assets/cd32b08d-3524-4a74-a297-a4e4376976fd)
