### ISSUE TITLE
K8ssandra-operator (env K8SSANDRA_CONTROL_PLANE:  true) got crashed when adding the medusa block in my cluster manifest

### ISSUE THREAD

**Issue by tajul-lowp** [k8ssandra/k8ssandra-operator#1487]
I was trying to deploy a single DC cluster in my existing EKS cluster. Following the link (<https://docs.k8ssandra.io/install/eks/>) I installed the k8ssandra operator in control plane mode.
`helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --set installCRDs=true`
`helm install k8ssandra-operator k8ssandra/k8ssandra-operator -n k8ssandra`

After executing the above command above got k8ssandra operator running perfectly.

```
k8ssandra-operator-6644f46cff-m6p27                 1/1     Running   0  
k8ssandra-operator-cass-operator-594f6c5874-njtnc   1/1     Running   0  
```

The I deployed the Single-cluster with a singe DC with medusa as defined in the following manifest:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test-db
spec:
  cassandra:
    serverVersion: "4.1.8"
    superuserSecretRef: 
        name: test-db-superuser
    datacenters:
      - metadata:
          name: datacenter1
        size: 1
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: efs-sc
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 512M
        stargate:
          size: 1
          heapSize: 256M
          resources:
              requests:
                cpu: 100m
                memory: 256M
              limits:
                cpu: 500m
                memory: 2G
  
  medusa:
    cassandraUserSecretRef: 
      name: test-db-superuser
    storageProperties:
      storageProvider: s3
      storageSecretRef:
        name: medusa-bucket-secret
      bucketName: test-db-backup
      prefix: testdb
      region: ap-northeast-1
```

When I applied the above manifest the k8ssandra-operator got crashed. 

```
NAME                                                READY   STATUS             RESTARTS       AGE
k8ssandra-operator-6644f46cff-6z4t7                 0/1     CrashLoopBackOff   14 (47s ago)  
k8ssandra-operator-cass-operator-594f6c5874-njtnc   1/1     Running            0              
```

The log shows the following error message:

```
2025-02-14T04:34:08.176Z        INFO    Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference        {"controller": "k8ssandracluster", "controllerGroup": "k8ssandra.io", "controllerKind": "K8ssandraCluster", "K8ssandraCluster": {"name":"test-db","namespace":"k8ssandra"}, "namespace": "k8ssandra", "name": "test-db", "reconcileID": "9739b295-044a-491a-a62f-ba77591235af"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x173e4e7]
```

If I comment out the medusa block the cluster runs without error.  

`k8ssandra-operator version is 1.21.1`

kubectl version command output
```
Client Version: v1.29.3-eks-ae9a62a
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.12-eks-2d5f260
```

I don't understand what is missing or causing the crash. I would greatly appreciate any help.

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/K8OP-310) by [Unito](https://www.unito.io)
┆Issue Number: K8OP-310
