### ISSUE TITLE
Medusa's MedusaTask is incorrectly generated if datacenterName is used

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/k8ssandra-operator#1529]
**What happened?**
If using "datacenterName" in the following way:

```yaml
    datacenters:
      - metadata:
          name: dc2
        k8sContext: kind-k8ssandra-1
        size: 2
        datacenterName: real-dc2
```

Then what happens is that MedusaBackupJob gets the correct dc2 name:

```yaml
  spec:
    backupType: differential
    cassandraDatacenter: dc2
```

Yet the MedusaTask gets a wrong one:

```yaml
  spec:
    cassandraDatacenter: real-dc2
    operation: purge
```

This obviously results in the logs outputting the following stuff:

```
2025-05-08T14:43:07.550Z	ERROR	failed to get cassandradatacenter	{"controller": "medusatask", "controllerGroup": "medusa.k8ssandra.io", "controllerKind": "MedusaTask", "MedusaTask": {"name":"purge-backups-20250508144302","namespace":"multi-dc-encryption-medusa-dzqgrw"}, "namespace": "multi-dc-encryption-medusa-dzqgrw", "name": "purge-backups-20250508144302", "reconcileID": "68aceaad-d704-4076-9b0a-bb811d149fba", "MedusaTask": {"name":"purge-backups-20250508144302","namespace":"multi-dc-encryption-medusa-dzqgrw"}, "cassdc": "real-dc2", "CassandraDatacenter": {"name":"real-dc2","namespace":"multi-dc-encryption-medusa-dzqgrw"}, "error": "CassandraDatacenter.cassandra.datastax.com \"real-dc2\" not found"}
```

This behavior can be seen with the output of CreateMultiMedusaJob, yet sadly the tests do not validate at all that these things work.

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* K8ssandra Operator version:

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* K8ssandra Operator Logs:

```
insert K8ssandra Operator logs relevant to the issue here
```

**Anything else we need to know?**:
