### ISSUE TITLE
Multi-Cluster K8ssandraCluster dc2 pods fail to restart when dc1 is unavailable – stale IPs in additional-seed-service

### ISSUE THREAD

**Issue by Nefftyanik** [k8ssandra/k8ssandra-operator#1546]
I’ve deployed a multi-cluster K8ssandra setup using the official Helm instructions from:
👉 [https://docs-v2.k8ssandra.io/install/local/multi-cluster-helm/](https://docs-v2.k8ssandra.io/install/local/multi-cluster-helm/)

### Cluster Topology:

* **3 clusters**, deployed using [[kind](https://kind.sigs.k8s.io/)](https://kind.sigs.k8s.io/):

  * `kind-k8ssandra-0`: **control-plane only** (K8ssandra Operator)
  * `kind-k8ssandra-1`: `dc1` data plane
  * `kind-k8ssandra-2`: `dc2` data plane

### Problem:

When simulating a full outage of `dc1` (e.g., turning off the entire cluster), the `dc2` datacenter **fails to restart** after rebooting its pods.

Upon investigation, the issue appears to be with the `demo-dc2-additional-seed-service`, which retains stale IP addresses from `dc1`. These stale IPs prevent Cassandra pods in `dc2` from starting, as they attempt to connect to unreachable seeds from the downed `dc1`.

### Expected Behavior:

* `dc2` should be able to boot independently, even if `dc1` is offline.
* Stale IPs from other unreachable datacenters should be removed.

### Actual Behavior:

* After restarting pods in `dc2`, they hang waiting on unreachable seed nodes (from `dc1`).
* This breaks resilience and makes it impossible to recover a single DC in isolation.

### `K8ssandraCluster` manifest:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
  namespace: k8ssandra-operator
spec:
  cassandra:
    serverVersion: "4.0.1"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 100M
    networking:
      hostNetwork: true
    datacenters:
      - metadata:
          name: dc1
        k8sContext: kind-k8ssandra-1
        size: 3
      - metadata:
          name: dc2
        k8sContext: kind-k8ssandra-2
        size: 3
```

### Environment Info:

* **K8ssandra Operator:** `v1.21.2`
* **Cassandra version:** `4.0.1`
* **Kubernetes (kind):**

  * `kind-k8ssandra-0`: v1.27.3
  * `kind-k8ssandra-1`: v1.27.3
  * `kind-k8ssandra-2`: v1.27.3

### Notes:

* The problem seems to be that the `*-additional-seed-service` does not update or remove the stale `dc1` IPs even after `dc1` is completely unreachable.
