### ISSUE TITLE
ZGC not being set when specified in manifest

### ISSUE THREAD

**Issue by DanielNBach** [k8ssandra/k8ssandra-operator#1566]
**What happened?**
When I specify gc: ZGC in the K8ssandraCluster manifest, it looks like the GC is being set back to G1GC in the JVM options once the K8ssandraCluster comes up.

**Did you expect to see something different?**
I expected the GC to be set to ZGC and see -XX:UseZGC in the JVM arguments instead of -XX:UseG1GC. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a K8ssandraCluster using k8ssandra/cass-management-api:5.0.3-ubi-v0.1.104 as the server image and set gc: ZGC.

**Environment**

* K8ssandra Operator version::v.1.21.1
* Cass Operator version:v1.23.2
* K8ssandra-Client:v0.7.0

* Kubernetes version information:

Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version:v1.29.4

* Manifests:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: c5jdk17-test
spec:
  cassandra:
    serverVersion: "5.0.3"
    serverImage: docker.io/k8ssandra/cass-management-api:5.0.3-ubi-v0.1.104
    config:
      jvmOptions:
        additionalOptions:
        - -Xmx12G # max heap size to 12G
        - -Xms12G # min heap size to 12G
        gc: ZGC
    resources:
      limits:
        cpu: 8000m
        memory: 24Gi
      requests:
        cpu: 2000m
        memory: 24Gi
    datacenters:
    - metadata:
        name: dc1
      size: 3
      storageConfig:
        cassandraDataVolumeClaimSpec:
          storageClassName: storageclass-cassandra
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
```
