### ISSUE TITLE
Cassandra size should be configurable at cluster level

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#188]
The size property can only be set at the DC level, e.g. 

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
spec:
  cassandra:
    cluster: demo
    serverVersion: "4.0.0"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    datacenters:
      - metadata:
          name: dc1
          namespace: default
        size: 3
```

It should be configurable at the cluster level to be consistent with other properties.

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/K8OP-101) by [Unito](https://www.unito.io)
┆Issue Number: K8OP-101
