### ISSUE TITLE
K8SSAND-975 ⁃ Superuser secret name not set on CassandraDatacenters

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#203]
**What happened?**
cass-operator will generate a default superuser for Cassandra if none is specified via the `SuperuserSecretName` in the CassandraDatacenter spec. We want k8ssandra-operator to create a default superuser and secret and specify the `SuperuserSecretName` for each CassandraDatacenter to ensure we have consistent credentials across DCs. We rely on the secret controller to replicate the secret to all remote clusters. 

In test environment I observed that a remote DC had a superuser secret despite the replication not having happened. The problem is that the `SuperuserSecret` field isn't getting set. This resulted in the superuser having a different password in each DC.

**Did you expect to see something different?**
The superuser secret should be the same across remote clusters. This is done by making sure the `SuperuserSecretName` field in each CassandraDatacenter is set to the same value.

**How to reproduce it (as minimally and precisely as possible)**:

* Run `make multi-up`
  * This provisions two kind clusters and deploys k8ssandra-operator in each one
  * `kind-k8ssandra-0` is configured as the control plane cluster
* Create a superuser secret:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-superuser
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: password
```

* Deploy the following K8ssandraCluster manifest:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  cassandra:
    cluster: test
    superUserSecret: superuser-secret
    serverVersion: "4.0.0"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      cassandraYaml:
        auto_snapshot: false
        memtable_flush_writers: 1
        commitlog_segment_size_in_mb: 2
        concurrent_compactors: 1
        compaction_throughput_mb_per_sec: 0
        sstable_preemptive_open_interval_in_mb: 0
        key_cache_size_in_mb: 0
        thrift_prepared_statements_cache_size_mb: 1
        prepared_statements_cache_size_mb: 1
        start_rpc: false
        slow_query_log_timeout_in_ms: 0
        counter_cache_size_in_mb: 0
        concurrent_reads: 2
        concurrent_writes: 2
        concurrent_counter_writes: 2
      jvmOptions:
        heapSize: 384Mi
    networking:
      hostNetwork: true
    resources:
      limits:
        memory: 512Mi
    datacenters:
      - metadata:
          name: dc1
        size: 1
      - metadata:
          name: dc2
        k8sContext: kind-k8ssandra-1
        size: 1
```

* Check the CassandraDatacenter `dc1` in kind-k8ssandra-0. The `superuserSecretName` field won't be set.
* Check `dc2` in kind-k8ssandra-1. The `superuserSecretName` field won't be set.
* You will find a `test-superuser` secret in each cluster that is created by cass-operator. This should not be created.

**Environment**

* K8ssandra Operator version:

v1.0.0-alpha.1

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-975) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-975
┆Priority: Medium
