### ISSUE TITLE
K8SSAND-1090 ⁃ Scaling the cluster causes a rolling restart

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#240]
**What happened?**
When you scale a Cassandra cluster, either by adding nodes to a DC, removing nodes from a DC, or by adding a DC, it will trigger an unnecessary rolling restart for existing DCs. 

Replication of system keyspaces is configured by setting the following Java system properties in the `server-config-init` container:

* `cassandra.system_distributed_replication_dc_names`
* `cassandra.system_distributed_replication_per_dc`

They are specified in an env var that looks something like this:

```yaml
    - name: CONFIG_FILE_DATA
      value: '{"cluster-info":{"name":"test","seeds":"test-seed-service,test-dc1-additional-seed-service"},"datacenter-info":{"graph-
enabled":0,"name":"dc1","solr-enabled":0,"spark-enabled":0},"jvm-options":{"additional-jvm-opts":["-
Dcassandra.system_distributed_replication_dc_names=dc1","-Dcassandra.system_distributed_replication_per_dc=1"]}}'
```

This would be for a single node cluster. If we scale up our cluster to 2 nodes, k8ssandra-operator sets `cassandra.system_distributed_replication_per_dc=2`. This will cause a StatefulSet update, i.e., rolling restart, since it updates the underlying PodTemplateSpec.

What's worse is that if the scaling is within an existing DC, the replication doesn't get updated. The Java system properties are basically idempotent. Only their initial values are applied.

**Did you expect to see something different?**
The system keyspaces' replication should be configured as follows:

`replication = min(num_nodes, 3)`

Changing the replication should not trigger a rolling restart.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* K8ssandra Operator version:
1.0.0-alpha.2
* Manifests:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  cassandra:
    cluster: test
    serverVersion: "4.0.0"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      cassandraYaml:
        auto_snapshot: false
        memtable_flush_writers: 1
        commitlog_segment_size_in_mb: 2
        concurrent_compactors: 1
        compaction_throughput_mb_per_sec: 0
        sstable_preemptive_open_interval_in_mb: 0
        key_cache_size_in_mb: 0
        thrift_prepared_statements_cache_size_mb: 1
        prepared_statements_cache_size_mb: 1
        start_rpc: false
        slow_query_log_timeout_in_ms: 0
        counter_cache_size_in_mb: 0
        concurrent_reads: 2
        concurrent_writes: 2
        concurrent_counter_writes: 2
      jvmOptions:
        heapSize: 512Mi
    networking:
      hostNetwork: true
    resources:
      limits:
        memory: 1024Mi
    datacenters:
      - metadata:
          name: dc1
        size: 1
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1090) by [Unito](https://www.unito.io)
┆Reviewer: 557058:376e6d8d-84b1-46a1-a227-0887055aa65a
┆epic: Addition of new DataCenters
┆fixVersions: k8ssandra-operator-v1.0.0-alpha.3
┆friendlyId: K8SSAND-1090
┆priority: Medium
