### ISSUE TITLE
Adding/removing Stargate to/from a K8ssandraCluster causes rolling restart

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#349]
**What happened?**
I removed Stargate from an existing K8ssandraCluster and noticed that it resulted in a restart of the Cassandra pods. I then added Stargate back and observed the same thing.

When Stargate is enabled, the operator sets the `cassandra.allow_alter_rf_during_range_movement=true` JVM system property on the CassandraDatacenter. When Stargate is removed, the property will be removed. This results in StatefulSet updates, i.e., rolling restarts.

Let's say we have a cluster with 3 DCs, 3 C* nodes per DC. After the cluster is up and running, we decide to deploy Stargate in each DC. This will result in a rolling restart of Cassandra across all DCs.

**Did you expect to see something different?**
Adding or removing Stargate to/from the K8ssandraCluster should not trigger a rolling restart. #153 talks about why `cassandra.allow_alter_rf_during_range_movement=true` is necessary. https://github.com/stargate/stargate/issues/1274 is the upstream Stargate issue.

If the issue is fixed upstream in Stargate, the problem simply goes away as we won't need the `cassandra.allow_alter_rf_during_range_movement=true` property.

Is it worth considering leaving this property enabled all the time for now? If not, we need to document this behavior around enabling/disabling Stargate.

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster with Stargate:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  cassandra:
    serverVersion: "4.0.1"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 512Mi
    resources:
      limits:
        memory: 1024Mi
    datacenters:
      - metadata:
          name: dc1
        k8sContext: kind-k8ssandra-0
        size: 1
  stargate:
    size: 1
```

After Cassandra and Stargate become ready, remove the `stargate` property. You will see that the Cassandra pod gets recreated.

**Environment**

* K8ssandra Operator version:

    1.0.0-alpha.3
