### ISSUE TITLE
Removing Reaper from a K8ssandraCluster does not remove the reaper_db keyspace

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#350]
**What happened?**
I created a K8ssandraCluster with Reaper enabled. The operator creates the `reaper_db` keypsace for Reaper. After Cassandra and Reaper were initialized, I removed Reaper from my K8ssandraCluster object which resulted in Reaper being undeployed. The underlying deployments, pods, etc. are all deleted as expected. The `reaper_db` keyspace however, is not deleted.

**Did you expect to see something different?**
I expect all resources related to Reaper to be removed including the `reaper_db` keyspace.

**How to reproduce it (as minimally and precisely as possible)**:
Create K8ssandraCluster with this manifest:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  cassandra:
    serverVersion: "4.0.1"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 512Mi
    resources:
      limits:
        memory: 1024Mi
    datacenters:
      - metadata:
          name: dc1
        k8sContext: kind-k8ssandra-0
        size: 1
  reaper:
    autoScheduling:
      enabled: true
```
Wait for Cassandra and Reaper to become ready. Update the K8ssandraCluster by removing the `reaper` property. Wait for Reaper to be completely removed.

Get the superuser password with `kubectl get secret test-superuser -o json | jq -r '.data.password' | base64 --decode`.

Verify that the `reaper_db` keyspace still exists with

`kubectl exec -it test-dc1-default-sts-0 -c cassandra -- cqlsh -u test-superuser -p <superuser-password> -e "describe keyspace reaper_db"`

**Environment**

* K8ssandra Operator version:

```
1.0.0-alpha.3
```

**Anything else we need to know?**:
I wouldn't consider this a blocking bug for 1.0. It should probably be documented though.
