### ISSUE TITLE
K8SSAND-1214 ⁃ Update e2e tests and GHA workflows for releases

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#351]
# Background
The purpose of this ticket is to address changes that are needed for working on a release branch in preparation of a release.

# e2e tests
e2e tests deploy the operator via kustomize using the `config/deployments/default` kustomization which looks like this:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8ssandra-operator

resources:
  - ../../default

images:
  - name: k8ssandra/k8ssandra-operator
    newTag: latest
```

Prior to creating the release tag, we will override the image tag, e.g.,

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8ssandra-operator

resources:
  - ../../default

images:
  - name: k8ssandra/k8ssandra-operator
    newTag: 1.0.0
```

When this change is committed and pushed, tests will run and try to pull a 1.0.0 image, but it won't exist until the release is done. The easiest solution is to have the e2e tests add another kustomization on top of this where it explicitly sets the tag to `latest`. The test workflows already build the operator image with a `latest` tag and load into into kind.

It would be nice to make it configurable in the event someone wants to run the tests with a different image.

# GHA workflows
Workflows need to be updated to run on release branches. I propose that release branches have the prefix `releases/`. This has. couple benefits. First, we can use pattern matching for enabling workflows to run on release branches, e.g.,

```yaml
name: Run unit/integration tests and build image
on:
  push:
    branches:
      - main
      - 'releases/**'
```

Secondly, the naming convention makes it very clear what branches are release branches.

All workflows need to be updated to run on push to a release branch. 

I think it would be good if the `Run unit/integration tests and build image` workflow only pushed `latest` images from `main`.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1214) by [Unito](https://www.unito.io)
┆Reviewer: 5fa4593062584c006b1e04d0
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-1214
┆priority: Medium
