### ISSUE TITLE
Add matrixed C* versions support to tests

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra-operator#360]
**What is missing?**
Currently we're directly setting the version of C* to be run in all test scenarios, much like what is available in k8ssandra/k8ssandra a matrixed version of testing that can support various versions of platform to be tested with the same harness would be very useful.

This work was started in https://github.com/k8ssandra/k8ssandra-operator/pull/137 but that work has become stale over time and not presents a risk to merge as is late in the 1.0.0 development cycle.  We should bring the purpose of that PR back to life post 1.0.0.

**Why do we need it?**
To provide more comprehensive automated tests.

**Comment by Miles-Garnsey** [comment]
I'm not saying anything new here (see [original PR](https://github.com/k8ssandra/k8ssandra-operator/pull/137)) when I say that this one is going to be quite tough. As time has gone on, a lot of the e2e test fixtures have become quite complex/diverse. A lot of the complexity is to work around performance/resource constraints. 

The problem is that many of the settings that have been tweaked (to allow the tests to run in constrained environments) don't exist in both 3.x versions and 4.x versions of Cassandra. For example, if we look [here](https://github.com/k8ssandra/k8ssandra-operator/blob/0bc61ef1ce9f89571cc935d677630738b44dad15/test/testdata/fixtures/multi-dc/k8ssandra.yaml#L26-L41) we can see that we're tweaking a whole range of cassandra.yaml settings:

```
      cassandraYaml:
        auto_snapshot: false
        memtable_flush_writers: 1
        commitlog_segment_size_in_mb: 2
        concurrent_compactors: 1
        compaction_throughput_mb_per_sec: 0
        sstable_preemptive_open_interval_in_mb: 0
        key_cache_size_in_mb: 0
        thrift_prepared_statements_cache_size_mb: 1
        prepared_statements_cache_size_mb: 1
        slow_query_log_timeout_in_ms: 0
        counter_cache_size_in_mb: 0
        concurrent_reads: 2
        concurrent_writes: 2
        concurrent_counter_writes: 2
```

Some things like `thrift_prepared_statements_cache_size_mb` [aren't even listed](https://github.com/apache/cassandra/blob/cassandra-4.0/conf/cassandra.yaml) in the cassandra.yaml for 4.x. So I'm not sure how/why this works. I also don't have context to judge why some settings have been tuned the way they have.

So I'm going to propose two options:

1. Matrix only the kuttl tests because (a) they have a smaller surface area that I know well and (b) they don't exhibit the same resource problems that the other e2e tests do.
2. Look into creating a kustomize component which tunes the cassandra.yaml to test-appropriate settings for both 3.x and 4.x. Use those components in all tests. Then use the [kustomizations](https://github.com/k8ssandra/k8ssandra-operator/blob/main/test/framework/e2e_framework.go#L168) in the `e2e_framework` to patch the version and component according to an argument on the CLI. This is similar to Michael's original approach but the emphasis is on having a single place to configure the cassandra.yaml.
