### ISSUE TITLE
Stopping a DC always triggers Reaper restart

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#375]
**What happened?**
This is a follow up to my testing for #331. Reaper was configured with `deploymentMode: SINGLE`. I stopped the DC where Reaper was not running. It trigger an update to the Reaper Deployment which means a rolling restart. The same thing happens when I restart the DC.

Here is the manifest I used:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  cassandra:
    serverVersion: "4.0.1"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      cassandraYaml:
        auto_snapshot: false
        memtable_flush_writers: 1
        commitlog_segment_size_in_mb: 2
        concurrent_compactors: 1
        compaction_throughput_mb_per_sec: 0
        sstable_preemptive_open_interval_in_mb: 0
        key_cache_size_in_mb: 0
        prepared_statements_cache_size_mb: 1
        slow_query_log_timeout_in_ms: 0
        counter_cache_size_in_mb: 0
        concurrent_reads: 2
        concurrent_writes: 2
        concurrent_counter_writes: 2
      jvmOptions:
        heapSize: 512Mi
    networking:
      hostNetwork: true
    resources:
      limits:
        memory: 1024Mi
    datacenters:
      - metadata:
          name: dc1
        k8sContext: kind-k8ssandra-0
        size: 1
      - metadata:
          name: dc2
        k8sContext: kind-k8ssandra-1
        size: 1
  reaper:
    deploymentMode: SINGLE
    autoScheduling:
      enabled: true
```
Reaper was deployed in dc1. Stopping and restarting dc2 caused a restart of Reaper.

**Did you expect to see something different?**
Reaper should not get restarted in this case. This [if block](https://github.com/k8ssandra/k8ssandra-operator/blob/main/pkg/reaper/resource.go#L71) is the relevant code.

**Environment**

* K8ssandra Operator version:

    `Insert image tag or Git SHA here`
    c74fc252
