### ISSUE TITLE
K8SSAND-1233 ⁃ Provide support for custom system-logger and config-builder image coordinates

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra-operator#378]
**What is missing?**
It should be possible to specify the complete image coordinates for all of the images to be used by the elements deployed by K8ssandra Operator so that users can provide images via their own private repositories as required for security or other reasons.

Currently there's a known lack of configurability for the system-logger image and the config-builder image.

**Why do we need it?**
To remove barriers in certain potential use cases such as security rules and regulations.  To provide feature parity with k8ssndra 1.x.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1233) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-operator-v1.1.0
┆friendlyId: K8SSAND-1233
┆priority: Medium

**Comment by jsanda** [comment]
We should be able to reuse the same `images.Image` type that is used for other images. Here is an example of its usage for the JMX init container:

```go
// +kubebuilder:default={name:"busybox",tag:"1.34.1"}
JmxInitContainerImage *images.Image `json:"jmxInitContainerImage,omitempty"`
```

**Comment by Miles-Garnsey** [comment]
Couple of notes on this. I'm a bit hesitant on omitting the defaults in this case. 

I understand that we want to leave this field blank by default and that (when it is undefined) the images that we end up using will be those used by default in cass-operator.

However, given the current nature of the `*images.Image.String()` [function](https://github.com/Miles-Garnsey/k8ssandra-operator/blob/main/pkg/images/images.go#L51), I'm not sure if this is the safest approach. 

It seems likely to me that the user will try to override 1-2 particular fields within the `Image`, and in this case, passing the resulting string from `*images.Image.String()` down into cass-operator will trigger an error because the image location will not be fully defined.

E.g. 

K8ssandraCluster definition:
```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  cassandra:
    serverVersion: "4.0.1"
    configBuilderContainerImage:
      registry: myregistry.com
...
```

Resulting CassandraDatacenter:

```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: "3.11.10"
  configBuilderImage: myregistry.com #ERROR
```

Do we want to do some additional validation around the string conversion function, or should we define defaults for registry/image/name/tag the same way that we do for `JmxInitContainerImage`?
