### ISSUE TITLE
K8SSAND-1240 ⁃ Watches are not configured for control plane client in K8ssandraCluster controller

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#389]
**What happened?**
The problem manifested itself with kuttl test failures discussed in #383. One one of the kuttl tests deploys a K8ssandraCluster with a single DC. It does not specify the `k8sContext` property for the DC. I will explain momentarily why that is relevant. The test also deploys ServiceMonitors and Stargate. 

After #331 was merged the kuttl test started failing. It appeared to be caused by this [commit](https://github.com/k8ssandra/k8ssandra-operator/commit/c74fc252d9f158f8b5dbd0d4e44a688eae319658) where we return `result.Done()` instead of `result.RequeueSoon()` when the CassandraDatacenter isn't ready instead. I suggested the change because no requeue should be necessary since a reconciliation should get triggered whenever cass-operator updates the status of the CassandraDatacenter.

In the kuttl test that later reconciliation wasn't happening; consequently, neither the ServiceMonitors nor Stargate were getting created. We have to look at how watches are configured for the K8ssandraCluster controller to understand what is happening:

```go
func (r *K8ssandraClusterReconciler) SetupWithManager(mgr ctrl.Manager, clusters []cluster.Cluster) error {
	cb := ctrl.NewControllerManagedBy(mgr).
		For(&api.K8ssandraCluster{}, builder.WithPredicates(predicate.GenerationChangedPredicate{}))

	clusterLabelFilter := func(mapObj client.Object) []reconcile.Request {
		requests := make([]reconcile.Request, 0)

		kcName := labels.GetLabel(mapObj, api.K8ssandraClusterNameLabel)
		kcNamespace := labels.GetLabel(mapObj, api.K8ssandraClusterNamespaceLabel)

		if kcName != "" && kcNamespace != "" {
			requests = append(requests, reconcile.Request{NamespacedName: types.NamespacedName{Namespace: kcNamespace, Name: kcName}})
		}
		return requests
	}

	for _, c := range clusters {
		cb = cb.Watches(source.NewKindWithCache(&cassdcapi.CassandraDatacenter{}, c.GetCache()),
			handler.EnqueueRequestsFromMapFunc(clusterLabelFilter))
		cb = cb.Watches(source.NewKindWithCache(&stargateapi.Stargate{}, c.GetCache()),
			handler.EnqueueRequestsFromMapFunc(clusterLabelFilter))
		cb = cb.Watches(source.NewKindWithCache(&reaperapi.Reaper{}, c.GetCache()),
			handler.EnqueueRequestsFromMapFunc(clusterLabelFilter))
	}

	return cb.Complete(r)
}
```
The first line,

```go
	cb := ctrl.NewControllerManagedBy(mgr).
		For(&api.K8ssandraCluster{}, builder.WithPredicates(predicate.GenerationChangedPredicate{}))
```
configures a watch on K8ssandraCluster objects. The watch is configured on the local or control plane `cluster.Cluster` object. 

The code further down in the method configures watches on CassandraDatacenter, Stargate, and Reaper objects. Note however that the watches are being configured on the `clusters` passed into the method. These `Cluster` objects are created based on the ClientConfigs that exist. This means that these watches come into play only when the `k8sContext` property is set for a DC in a K8ssandraCluster. 

If the `k8sContext` property is not set, the operator falls back to using the control plane `Cluster`. Watches need to be configured for the control plane `Cluster` just as they are for the remote `Cluster`s.

**Did you expect to see something different?**
ServiceMonitors and Stargate should have been deployed without having to set the `k8sContext` property.

**How to reproduce it (as minimally and precisely as possible)**:
Use this manifest:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
  namespace: k8ssandra-operator
spec:
  cassandra:
    cassandraTelemetry:
      prometheus:
        enabled: true
    datacenters:
    - config:
        jvmOptions:
          heapSize: 384Mi
      metadata:
        name: dc1
      size: 1
      storageConfig:
        cassandraDataVolumeClaimSpec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: standard
    serverVersion: 3.11.11
  stargate:
    allowStargateOnDataNodes: true
    size: 1
    telemetry:
      prometheus:
        enabled: true
```
Wait 5 a few minutes after the Cassandra pod becomes ready. There won't be any ServiceMonitors or Stargate objects created.

**Environment**

* K8ssandra Operator version:

    `v0.5.0`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1240) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-1240
┆priority: Highest
