### ISSUE TITLE
Kustomize files in e2e-tests don't set correct clientConfig.service.namespace in cass-operator ValidatingWebhookConfiguration

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/k8ssandra-operator#397]
**What happened?**
When building control-plane kustomize template, we create one unnecessary namespace: cass-operator:

```console
➜  k8ssandra-operator git:(validating_webhook) ✗ bin/kustomize build config/deployments/control-plane > control-plane.yaml
➜  k8ssandra-operator git:(validating_webhook) ✗ grep 'kind: Namespace' control-plane.yaml | wc -l
2
➜  k8ssandra-operator git:(validating_webhook) ✗
```

There's also incorrect cass-operator webhook service deployment:

```yaml
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: k8ssandra-operator/cass-operator-serving-cert
  name: cass-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: cass-operator-webhook-service
      namespace: cass-operator
      path: /validate-cassandra-datastax-com-v1beta1-cassandradatacenter
```

The clientConfig/service/namespace should be in k8ssandra-operator namespace since that's where the webhook path is also deployed to. 

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:
build config/deployments/control-plane

**Comment by jsanda** [comment]
#387 may address this.

**Comment by Miles-Garnsey** [comment]
This is an issue so I'm reopening it. @jsanda is correct in saying that #387 addresses the additional namespace and just needs to be merged to solve that problem.

The `ValidatingWebhookConfiguration` is a separate issue and actually appears to be a regression. If you run the following you'll note that the namespace is correct:

```
git remote add miles git@github.com:Miles-Garnsey/k8ssandra-operator.git
git fetch --all 
git checkout miles/single-ns-component
kustomize build config/deployments/control-plane | yq e 'select(.kind == "ValidatingWebhookConfiguration")' -
```

```
...
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: k8ssandra-operator/cass-operator-serving-cert
  name: cass-operator-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: cass-operator-webhook-service
        namespace: k8ssandra-operator
        path: /validate-cassandra-datastax-com-v1beta1-cassandradatacenter
    failurePolicy: Ignore
    name: vcassandradatacenter.kb.io
    rules:
      - apiGroups:
          - cassandra.datastax.com
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - cassandradatacenters
    sideEffects: None```

However, if you do the same on `main` you get:

```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: k8ssandra-operator/cass-operator-serving-cert
  name: cass-operator-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: cass-operator-webhook-service
        namespace: k8ssandra-operator
        path: /validate-cassandra-datastax-com-v1beta1-cassandradatacenter
    failurePolicy: Ignore
    name: vcassandradatacenter.kb.io
    rules:
      - apiGroups:
          - cassandra.datastax.com
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - cassandradatacenters
    sideEffects: None
```

**Comment by Miles-Garnsey** [comment]
Michael reports that, having rebased his branch, he no longer sees problems with the `ValidatingWebhookConfiguration`'s namespace.

To ensure that these issues do not return, I have [added](https://github.com/k8ssandra/k8ssandra-operator/pull/387/commits/a147a905cd95b8f7b50b9970c5f679290e7e5f91) an additional assertion to the kuttl test `test-user-defined-ns` to ensure that the cass-operator `ValidatingWebhookConfiguration`'s  `webhooks.0.clientConfig.service.namespace`  is always k8ssandra-operator NS. 

If we start seeing that failing elsewhere then we'll need to investigate further, but for now, it may just be that some branches have not been rebased from the most recent kustomize changes.

**Comment by burmanm** [comment]
Now I'll genuinely reopen this since actually.. there is an issue. Everything works if the namespace is indeed k8ssandra-operator, but once that's changed, things no longer deploy correctly. If I run ``bin/kustomize build build/test-config/k8ssandra-operator/control-plane > default-test.yaml`` and verify the output, I see:

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: single-dc-6228xl/cass-operator-serving-cert
  name: cass-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: cass-operator-webhook-service
      namespace: k8ssandra-operator
      path: /validate-cassandra-datastax-com-v1beta1-cassandradatacenter
```

Here we see the clientConfig/service/name not being the correct one, but pointing to a wrong namespace.
