### ISSUE TITLE
K8SSAND-1244 ⁃ Removing a DC with size > 1 results in panic

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#398]
**What happened?**
I had a cluster with 2 DCs, 3 nodes per DC. I removed DC2. The operator in the control plane crashed with a panic due to an odd number of key-value args in a log statement. Here is the stack trace:

```
2022-02-14T20:20:04.209Z	INFO	controller.k8ssandracluster	Reconciling replicated secrets	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test", "namespace": "k8ssandra-operator", "K8ssandraCluster": "k8ssandra-operator/test"}
2022-02-14T20:20:04.210Z	INFO	controller.k8ssandracluster	Proceeding with DC deletion	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test", "namespace": "k8ssandra-operator", "K8ssandraCluster": "k8ssandra-operator/test", "DC": "dc2"}
2022-02-14T20:20:04.270Z	DPANIC	controller.k8ssandracluster	odd number of arguments passed as key-value pairs for logging	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test", "namespace": "k8ssandra-operator", "K8ssandraCluster": "k8ssandra-operator/test", "ignored key": {"namespace": "k8ssandra-operator", "name": "dc2"}}
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).checkDcDeletion
	/workspace/controllers/k8ssandra/cleanup.go:147
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).reconcileDatacenters
	/workspace/controllers/k8ssandra/datacenters.go:28
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).reconcile
	/workspace/controllers/k8ssandra/k8ssandracluster_controller.go:133
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).Reconcile
	/workspace/controllers/k8ssandra/k8ssandracluster_controller.go:87
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227
panic: odd number of arguments passed as key-value pairs for logging
```
We have an e2e test for removing a DC. It only deploys a single node per DC, so it wouldn't hit this logging statement.

**Did you expect to see something different?**
No panic

**How to reproduce it (as minimally and precisely as possible)**:
Deploy this K8ssandraCluster:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  auth: false
  cassandra:
    serverVersion: "4.0.1"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 512Mi
    datacenters:
      - metadata:
          name: dc1
        size: 3
      - metadata:
          name: dc2
        k8sContext: dev-2 # Update this according to you environment
        size: 3
```
After both dc1 and dc2 become ready, remove dc2 from the spec and apply changes.

**Environment**

* K8ssandra Operator version:

    `v0.5.0`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1244) by [Unito](https://www.unito.io)
┆Reviewer: 5fa45931c8247300705e1fed
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-1244
┆priority: Medium
