### ISSUE TITLE
K8SSAND-1247 ⁃ Current anti affinity rules don't apply with multi DC

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#402]
The anti affinity rules we currently apply to prevent different Cassandra pods from being collocated on the same workers don't apply when multiple DCs get started, as they will be started in different namespaces:

```
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: cassandra.datastax.com/cluster
                operator: Exists
              - key: cassandra.datastax.com/datacenter
                operator: Exists
              - key: cassandra.datastax.com/rack
                operator: Exists
           topologyKey: kubernetes.io/hostname
```

Adding `namespaces: []` would allow the label selector to apply across all namespaces instead of just the current pod's namespace:

```
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: cassandra.datastax.com/cluster
                operator: Exists
              - key: cassandra.datastax.com/datacenter
                operator: Exists
              - key: cassandra.datastax.com/rack
                operator: Exists
           topologyKey: kubernetes.io/hostname
           namespaces: []
```

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-1247) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-1247
┆priority: Medium
