### ISSUE TITLE
K8SSAND-1252 ⁃ Rename cassandraTelemetry property to just telemetry

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#411]
**What is missing?**
The `casandra` part of the `cassandraTelemetry` property name is redundant and unnecessary.

Here is an example manifest:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
  namespace: k8ssandra-operator
spec:
  cassandra:
    datacenters:
    - config:
        jvmOptions:
          heapSize: 384Mi
      metadata:
        name: dc1
      size: 1
      storageConfig:
        cassandraDataVolumeClaimSpec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: standard
    serverVersion: 3.11.11
    cassandraTelemetry:
      prometheus:
        enabled: true
  stargate:
    allowStargateOnDataNodes: true
    size: 1
    telemetry:
      prometheus:
        enabled: true
```

**Why do we need it?**
Changing the name to just `telemetry` removes the redundancy and makes the naming consistent with the stargate property. It is already clear that the property corresponds to Cassandra as it is a child property under the `cassandra` property.

**Environment**

* K8ssandra Operator version:

    `v0.5.0`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1252) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-1252
┆priority: Medium
