### ISSUE TITLE
K8SSAND-1321 ⁃ Use yq to parse fixture files

### ISSUE THREAD

**Issue by adutra** [k8ssandra/k8ssandra-operator#462]
We need to parse fixture YAML files to find which `k8sContext` fields are defined, so that we can create a kustomization to change the context names.

Currently this is done with a manual parsing. But this is a bit hacky.

Using `yq` is a more robust solution. 

For example, assuming the following spec:

```yaml
    datacenters:
      - metadata:
          name: dc1
        size: 3
      - metadata:
          name: dc2
        k8sContext: kind-k8ssandra-1
        size: 3
```

Then the following command:

```
 > yq e '.spec.cassandra.datacenters.[] | .k8sContext | {(path | .[-2] ): .}' k8ssandra.yaml  
```

would print:

```
0: null
1: kind-k8ssandra-1
```

With this, we know that the kustomization must target only `.spec.cassandra.datacenters[1].k8sContext` since `.spec.cassandra.datacenters[0].k8sContext` isn't defined.

This would also be useful to count occurrences of other fields, e.g. `storageClassName`.

_Originally posted by adutra in https://github.com/k8ssandra/k8ssandra-operator/pull/446#discussion_r824933997_

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1321) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1321
┆priority: Medium
