### ISSUE TITLE
K8SSAND-1325 ⁃ Java garbage collection properties cannot be configured correctly

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#465]
**What happened?**
I created a Cassandra 4.x cluster with some GC properties set in my manifest, but they were not configured correctly in the Cassandra pod. This is closely related to https://github.com/k8ssandra/k8ssandra/issues/1353 in that it has to do with how [cass]-config-definitions] handles JVM GC properties for Cassandra 4.x. 

First I tried to configure some G1 settings:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  auth: false
  cassandra:
    serverVersion: "4.0.3"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 512Mi
        additionalOptions:
          - "-XX:MaxGCPauseMillis=600"
          - "-XX:ParallelGCThreads=4"
    networking:
      hostNetwork: true
    datacenters:
      - metadata:
           name: dc1
         size: 1
```

The `additionalOptions` property basically appends properties to the list of properties passed to Cassandra's JVM. `-XX:MaxGCPauseMillis=500` is already passed, so `-XX:MaxGCPauseMillis=600` is appended to the list. It isn't clear which one will take precedence, but there should only be one instance of `-XX:MaxGCPauseMillis` in the properties passed to the JVM. 

I didn't see `-XX:ParallelGCThreads` previously set so that was ok.

I tried configuring CMS with the following settings:

```yaml
    config:
      jvmOptions:
        heapSize: 512Mi
        additionalOptions:
          - "-XX:+UseConcMarkSweepGC"
          - "-XX:SurvivorRatio=4"
```

Again those properties are simply appended to the list of properties passed to the JVM. `-XX:+UseG1GC` appears earlier in the list, so presumably it is used. 

I don't think we can rely on using `additionalOptions` for configuring GC properties. 

**Did you expect to see something different?**
I expect to be able to configure GC properties.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the above manifest. When the Cassandra pod is ready grab Cassandra's logs with:

`kubectl logs test-dc1-default-sts-0 -c server-system-logger > cassandra.log`

Look for the log statement that starts with `INFO  [main] 2022-03-13 22:35:40,855 CassandraDaemon.java:642 - JVM Arguments`.

**Environment**

* K8ssandra Operator version:

    `1.0.1`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1325) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1325
┆priority: Medium

**Comment by adutra** [comment]
A few data points:

* In (almost?) all JMVs, in case of duplicate JVM options, the last occurrence wins (see [here](https://stackoverflow.com/questions/2740725/duplicated-java-runtime-options-what-is-the-order-of-preference)). It's not a documented feature, but it just happens to be that way for every JVM out there. So I would expect our options to be taken into account rather than the default ones, since cass-config-builder usually appends additional stuff at the end of each file. If that's not happening, maybe it's because files such as `jvm.options`, `jvm-server.options`. etc. are treated differently, it would be good to investigate that:
  * In C* 4.0, the various `jvm*.options` files are read into `$JVM_OPTS` in `cassandra.in.sh`, see [here](https://github.com/apache/cassandra/blob/82e0453901765efb678f9471c9cf30248318bcf7/bin/cassandra.in.sh#L155-L158).
  * In C* 3.11, these files are read inside `cassandra-env.sh`, see [here](https://github.com/apache/cassandra/blob/c3ae22d654630706f0baa0ead4547e2c87919bb9/conf/cassandra-env.sh#L135-L140).
* Currently `config.jvmOptions.additionalOptions` is being inserted in `cassandra-env.sh`, at the end of the script, see [here](https://github.com/datastax/cass-config-definitions/blob/4bda549aafdc3c00e75d5f95a9d5c9295a361d20/resources/cassandra-env-sh/cassandra/cassandra-env-sh-cassandra-4.0.0.template#L310-L312). I did this recently so that our JMX-related JVM options are not accidentally overwritten by previous lines in this script.
  * As I said, I would expect anything specified in `config.jvmOptions.additionalOptions` to prevail, because they are applied last. Maybe what's happening is that contradictory GC settings end up being applied by the JVM?
* In general, Cassandra startup scripts generated by cass-config builder are tricky to customize in a fine-grained fashion because they take decisions for you that might contradict your expectations, e.g.: JMX which is a mess since it is configured in many files in ways that are not always customizable. I fear that garbage collection is another example. 
* All config-builder templates for `jvm*.options` files accept a parameter called `garbage_collector`, see [here](https://github.com/datastax/cass-config-definitions/blob/f3f5e40c780100990729abc1c62498c520c26815/resources/jvm11-server-options/cassandra/jvm11-server-options-cassandra-4.0.0.template#L18-L38). The default is always `G1GC`. We might want to expose this setting in k8ssandra-operator, Having it default to G1GC is maybe interfering when you specify a different GC, e.g. with `-XX:+UseConcMarkSweepGC`.

**Comment by adutra** [comment]
I tried the above definition using G1. Here is what I observed:

Contents of /etc/cassandra:

```sh
cassandra-env.sh
cassandra-jaas.config
cassandra-rackdc.properties
cassandra-topology.properties
cassandra.yaml
commitlog_archiving.properties
cqlshrc.sample
hotspot_compiler
jvm11-clients.options
jvm11-server.options
jvm8-clients.options
jvm8-server.options
jvm-clients.options
jvm.options
jvm-server.options
logback-tools.xml
logback.xml
metrics-reporter-config-sample.yaml
README.txt
triggers
```

Contents of jvm.options (trimmed to relevant bits):

```
-XX:G1RSetUpdatingPauseTimePercent=5
-XX:MaxGCPauseMillis=500
-XX:+UseG1GC
```

Contents of jvm-server.options: nothing relevant to GC.

Contents of jvm11-server.options (trimmed to relevant bits):

```
-XX:G1RSetUpdatingPauseTimePercent=5
-XX:MaxGCPauseMillis=500
-XX:+UseG1GC
-XX:+ParallelRefProcEnabled
```

Contents of cassandra-env.sh (only relevant bits):

```sh
echo $JVM_OPTS | grep -q UseConcMarkSweepGC
USING_CMS=$?
echo $JVM_OPTS | grep -q +UseG1GC
USING_G1=$?

# We only set -Xmn flag if it was not defined in jvm-server.options file
# and if the CMS GC is being used
# If defined, both Xmn and Xmx should be defined together.
if [ $DEFINED_XMN -eq 0 ] && [ $DEFINED_XMX -ne 0 ]; then
    echo "Please set or unset -Xmx and -Xmn flags in pairs on jvm-server.options file."
    exit 1
elif [ $DEFINED_XMN -ne 0 ] && [ $USING_CMS -eq 0 ]; then
    JVM_OPTS="$JVM_OPTS -Xmn${HEAP_NEWSIZE}"
fi

# We fail to start if -Xmn is used with G1 GC is being used
# See comments for -Xmn in jvm-server.options
if [ $DEFINED_XMN -eq 0 ] && [ $USING_G1 -eq 0 ]; then
    echo "It is not recommended to set -Xmn with the G1 garbage collector. See comments for -Xmn in jvm-server.options for details."
    exit 1
fi

if [ "$JVM_ARCH" = "64-Bit" ] && [ $USING_CMS -eq 0 ]; then
    JVM_OPTS="$JVM_OPTS -XX:+UseCondCardMark"
fi

JVM_OPTS="$JVM_OPTS $JVM_EXTRA_OPTS"

JVM_OPTS="$JVM_OPTS -Dcassandra.system_distributed_replication_dc_names=dc1"
JVM_OPTS="$JVM_OPTS -Dcassandra.system_distributed_replication_per_dc=1"
JVM_OPTS="$JVM_OPTS -Dcom.sun.management.jmxremote.authenticate=false"
JVM_OPTS="$JVM_OPTS -XX:MaxGCPauseMillis=600"
JVM_OPTS="$JVM_OPTS -XX:ParallelGCThreads=4"
JVM_OPTS="$JVM_OPTS -javaagent:/opt/metrics-collector/lib/datastax-mcac-agent.jar"
JVM_OPTS="$JVM_OPTS -javaagent:/opt/management-api/datastax-mgmtapi-agent-0.1.0-SNAPSHOT.jar"
```

Note that the last lines above are the ones added by K8ssandra.

Now contents of JVM flags as reported by the logs, trimmed to relevant ones only:

* -XX:G1RSetUpdatingPauseTimePercent=5 (from jvm11-server.options)
* **-XX:MaxGCPauseMillis=500** (from jvm11-server.options)
* -XX:+UseG1GC (from jvm11-server.options)
* -XX:+ParallelRefProcEnabled (from jvm11-server.options)
* **-XX:MaxGCPauseMillis=600** (from cassandra-env.sh)
* -XX:ParallelGCThreads=4 (from cassandra-env.sh)

Indeed `-XX:MaxGCPauseMillis` appears twice, but I'm confident that the last appearance wins. IMO for G1 at least, everything is working as expected. I will try CMS next.

**Comment by adutra** [comment]
So with CMS, things get indeed into the weeds. I tried the definition above with CMS, and cassandra didn't even started. 

Contents of files didn't change except, of course, cassandra-env.sh that had at the end:

```sh
JVM_OPTS="$JVM_OPTS -XX:+UseConcMarkSweepGC"
JVM_OPTS="$JVM_OPTS -XX:SurvivorRatio=4"
```

The reason was:

```
cassandra@k8ssandra-0-worker4:/$ cat /var/log/cassandra/stdout.log
Error occurred during initialization of VM
Multiple garbage collectors selected
```

Hopefully, there is a workaround: add `-XX:-UseG1GC` to `additionalOptions`:

```yaml
    config:
      jvmOptions:
        heapSize: 512Mi
        additionalOptions:
          - "-XX:-UseG1GC" # add this
          - "-XX:+UseConcMarkSweepGC"
          - "-XX:SurvivorRatio=4"
```

With this change, Cassandra started, and indeed CMS is used, as we see from the logs:

```
INFO  [main] 2022-03-15 11:54:44,199 CassandraDaemon.java:638 - Par Eden Space Heap memory: init = 119275520(116480K) used = 119275520(116480K) committed = 119275520(116480K) max = 119275520(116480K)
INFO  [main] 2022-03-15 11:54:44,199 CassandraDaemon.java:638 - Par Survivor Space Heap memory: init = 29818880(29120K) used = 14816800(14469K) committed = 29818880(29120K) max = 29818880(29120K)
...
INFO  [main] 2022-03-15 11:54:44,199 CassandraDaemon.java:638 - CMS Old Gen Heap memory: init = 357957632(349568K) used = 0(0K) committed = 357957632(349568K) max = 357957632(349568K)
```

We can even see that the survivor ratio was correctly applied: 119275520/29818880 = 4.

Conclusions:
* It is risky to attempt to change GC without changing the `garbage_collector` config-builder variable – I suggest that we found a way to expose it in K8ssandra.
* There is hopefully a workaround, but one needs to "cancel" all GC settings before applying new ones, e.g. add `-XX:-UseG1GC` before `-XX:+UseConcMarkSweepGC`.
* This workaround has one downside: in cassandra-env.sh, 2 variables are used for sanity checks: `USING_CMS` and `USING_G1`. Given that K8ssandra JVM options arrive after their declarations, these variables will always be set to false and true respectively, effectively making the sanity checks inoperable.

**Comment by adutra** [comment]
We currently don't expose the `jvm11-server-options` key in K8ssandra operator. The `JvmOptions` type has:

```go
type JvmOptions struct {
	HeapSize          *resource.Quantity `json:"heapSize,omitempty"`
	HeapNewGenSize    *resource.Quantity `json:"heapNewGenSize,omitempty"`
	AdditionalOptions []string           `json:"additionalOptions,omitempty"`
}
```

`HeapSize` and `HeapNewGenSize` go into `initial_heap_size`, `max_heap_size` and `heap_size_young_generation`, under the `jvm-server-options` key. And as I said, `AdditionalOptions` end up under the `cassandra-env-sh` key as `additional-jvm-opts`.

We will need to modify `JvmOptions` and add more fields there, I think this is a backwards compatible change as long as the new fields are optional. I suggest that we don't change `AdditionalOptions` since this field is key for JMX to work properly.

**Comment by jsanda** [comment]
I am also in favor of leaving `AdditionalOptions` as is. If possible I prefer to avoid exposing `jvm-server-options`. I think it should be an implementation detail. We should just add additional properties in the `JvmOptions` struct and the operator should configure them as necessary in the CassandraDatacenter.

**Comment by adutra** [comment]
Also see my comment here: https://github.com/k8ssandra/k8ssandra/issues/1353#issuecomment-1068157469.

Your proposed config:

```yaml
    jvm-server-options:
      initial_heap_size: "512m"
      max_heap_size: "512m"
    jvm11-server-options:
      garbage_collector: G1GC
      max_gc_pause_millis: 550
```

is indeed correct. I wonder however if we shouldn't explicitly disable GC setting in `jvm-options`:


```yaml
    jvm-options:
      garbage_collector: NONE
    jvm-server-options:
      initial_heap_size: "512m"
      max_heap_size: "512m"
    jvm11-server-options:
      garbage_collector: G1GC
      max_gc_pause_millis: 550
```
