### ISSUE TITLE
K8SSAND-1353 ⁃ Deploy-gke-multi script execution failure

### ISSUE THREAD

**Issue by jeffbanks** [k8ssandra/k8ssandra-operator#481]
**What happened?**

ragsns discovered this issue when attempting to setup 3 clusters in his gcp environment using the following script: 

* [gke-multi](https://github.com/k8ssandra/k8ssandra-operator/blob/main/docs/install/deploy-gke-multi.sh)

**Error reported**

```
source ./docs/install/deploy-gke-multi.sh
error: no context exists with the name: "gke_datastax-marketing_us-east1-b_k8sop0"
Error: evalsymlink failure on 'aux-config/control_plane' : lstat /Users/raghavan.srinivas/work/datastax/src/k8ssandra-terraform/k8ssandra-operator/aux-config: no such file or directory
```

**Did you expect to see something different?**

Installation of k8ssandra resources based on his configuration.

It was difficult for ragsns to determine how to best setup and run the script given the kustomize activities that were referenced.  It may be that we need more detailed installer documentation and/or there is an issue with the script itself.

**How to reproduce it (as minimally and precisely as possible)**:

Running the script referenced above with the following configuration that was pre-provisioned in his GCP environment.

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: ragsns
spec:
  cassandra:
    serverVersion: "4.0.1"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 512M
    networking:
      hostNetwork: true
    datacenters:
      - metadata:
          name: dc1
        k8sContext: gke_...k8sopc
        size: 1
      - metadata:
          name: dc2
        k8sContext: gke_...k8sopb
        size: 1
  stargate:
     size: 1
     heapSize: 512M
```

**Environment**

GCP/GKE

* K8ssandra Operator version:
v1.0.1

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1353) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1353
┆priority: Medium
