### ISSUE TITLE
Allow performing restores without having a running cluster

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#487]
Cassandra data should be restore-able on the initial cluster startup.
The K8ssandraCluster object would need to be augmented with settings that indicate which backup should be restored on the first start:

```
    datacenters:
      - metadata:
          name: dc1
        k8sContext: dev
        size: 3
        restoreFrom:
          prefix: cluster-1
          backupName: medusa_20220315
```

Connection settings would still be set up in the Medusa section of the manifest, as Medusa's containers will rely on it.
The prefix will be customizable for the restore operation though, which will be carried out in #453.
This work will also leverage what will be done in #486.
