### ISSUE TITLE
K8SSAND-1430 ⁃ Allow configuring annotations and labels on services, statefulsets, deployments and pods

### ISSUE THREAD

**Issue by akshaymankar** [k8ssandra/k8ssandra-operator#501]
**What is missing?**

Annotations and labels cannot be configured on services, statefulsets, deployments and pods created by the operator.

**Why do we need it?**

The annotations and labels are useful in many ways, for example: exposing a service using [external-dns](https://github.com/kubernetes-sigs/external-dns), tagging logs from a pod so they can indexed and searched appropriately.

**Environment**

* K8ssandra Operator version: v1.0.1

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1430) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1430
┆priority: Medium

**Comment by jsanda** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra-operator/501?planning-poker) with ZenHub @adutra @burmanm

**Comment by adutra** [comment]
Sorry for the late reply, estimate done.

**Comment by andrey-dubnik** [comment]
Hi, does this cover the scenario below (so I don't have to create a new issue)? 

It seem CRD support labels and annotations but the operator does not seem to notice this and there is no updates triggering leaving the POD with the standard label set.

```
 spec:
        cassandra:
          serverVersion: "4.0.3"
          datacenters:
            - metadata:
                name: dc1
                labels:
                  env: dev
                  app: someapp
                annotations:
                  prometheus.io/scrape: 'true'
                  prometheus.io/port: '9103'
```

**Comment by jsanda** [comment]
@andrey-dubnik the `metadata` field there applies _only_ to the CassandraDatacenter that is created for each entry in `datacenters`, so you should see those labels and annotations on the `dc1` CassandraDatacenter that the operator creates.

Assuming you want those labels and annotations applied to other resources, then this issue should cover it.

We have a pattern or convention in place where things can be configured at the cluster-level or at the individual DC-level. The former would apply to all DCs. The latter overrides the former. We probably want to take that same approach with labels and annotations. Does that seem reasonable?

**Comment by andrey-dubnik** [comment]
Overlays totally make sense.

**Comment by adutra** [comment]
@akshaymankar @andrey-dubnik @sseidman first off, thank you for your interest in K8ssandra!

The team had the chance to discuss this issue yesterday. It appeared to us that, before proceeding to the PR review (thanks again @sseidman!), it would be beneficial to refine the requirements first.

We came to the conclusion that the use cases that we need to support are:

1. Placing labels & annotations on pods;
2. Placing labels & annotations on services;
3. Placing labels on other types of objects, including custom resources.

We also noted that:

* At this point it doesn't seem useful to provide the ability to place annotations on any type of object. Besides, cass-operator doesn't allow that.
* It also doesn't seem particularly useful to place labels on intermediary objects such as Deployments or StatefulSets, but to simplify the goals, and since cass-operator allows that, we agree to provide the ability to place labels on such objects as well. 
* However it won't be necessary to distinguish between object types; providing a generic mechanism to apply the same labels to all objects is enough (cf. cass-operator's `AdditionalLabels`).
* For Cassandra services, the requirement is to be able to distinguish between different services; iow, each specific service should be able to get specific labels & annotations.
* The requirements should be extended to `Reaper` and `Stargate` objects as well.
* Telemetry: labels can already be set on service monitors through the `telemetry.prometheus.commonLabels` field. Annotations, however, cannot be set currently on service monitors. We agree that this is enough for now and so telemetry should be left out of the scope of this work.

With that in mind, it's also interesting to look at the statu quo.

Requirement | Available in K8ssandra operator? | Available in Cass operator?
-- | -- | --
Labels & annotations on pods | No | Yes, using either `PodTemplateSpec` or `AdditionalLabels`
Labels & annotations on services | No | Yes, using `AdditionalServiceConfig` or `AdditionalLabels`
Labels on any type of object | No | Yes, using `AdditionalLabels`

We see that the required functionality is already exposed in cass-operator. There have been arguments against using `PodTemplateSpec` in cass-operator, but changing this is outside the scope of this work. It is also outside the scope of this work to expose `PodTemplateSpec` in K8ssandra operator.

From the table above, we infer that cass-operator does not need modifications. But we also infer that we need to rely on what's exposed by cass-operator when implementing the missing features in K8ssandra operator.

Does everyone agree with the above? 

If so, the next step would be to see how things would look like from the user's standpoint.

We would like to enforce the following:

* The same principles governing the merge between cluster- and DC-level values should apply, that is, labels and annotations should be definable at cluster level and overridable at DC level.
* We should reuse existing terminology and fields. There is already a `metadata` field in `CassandraDatacenterTemplate`, we should then generalize its usage. We already have a few fields named `commonLabels`, we should reuse that whenever appropriate.

Here is a very long YAML example of what things might look like according to us:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:

  ########################################
  # Cluster-level values
  ########################################
  
  stargate:
    size: 1
    metadata:
      labels: { } # applies to Stargate resources
      annotations: { } # applies to Stargate resources
      commonLabels: { } # applies to ALL objects created by Stargate controller
      pods:
        labels: { }
        annotations: { }
      services:
        labels: { }
        annotations: { }
    telemetry:
      prometheus:
        commonLabels: { }

  reaper:
    metadata:
      labels: { } # applies to Reaper resources
      annotations: { } # applies to Reaper resources
      commonLabels: { } # applies to ALL objects created by Reaper controller
      pods:
        labels: { }
        annotations: { }
      services:
        labels: { }
        annotations: { }
    telemetry:
      prometheus:
        commonLabels: { }

  cassandra:
    metadata:
      labels: { } # applies to CassandraDatacenter resources
      annotations: { } # applies to CassandraDatacenter resources
      commonLabels: { } # applies to ALL objects created by cass-operator
      pods:
        labels: { } 
        annotations: { }
      services:
        dcService:
          labels: { }
          annotations: { }
        seedService:
          labels: { }
          annotations: { }
        additionalSeedService:
          labels: { }
          annotations: { }
        allPodsService:
          labels: { }
          annotations: { }
        nodePortService:
          labels: { }
          annotations: { }
    telemetry:
      prometheus:
        commonLabels: { }
    
    ########################################
    # DC-level values
    ########################################
    
    datacenters:
      - metadata: # Note: this is an existing field, will need to be refactored
          name: dc1
          namespace: ns1
          labels: { } # applies to CassandraDatacenter resources
          annotations: { } # applies to CassandraDatacenter resources
          commonLabels: { } # applied to ALL objects created by cass-operator
          pods:
            labels: { } 
            annotations: { } 
          services:
            dcService:
              labels: { }
              annotations: { }
            seedService:
              labels: { }
              annotations: { }
            additionalSeedService:
              labels: { }
              annotations: { }
            allPodsService:
              labels: { }
              annotations: { }
            nodePortService:
              labels: { }
              annotations: { }
        telemetry:
          prometheus:
            commonLabels: { }
        size: 3

        stargate:
          size: 1
          metadata:
            labels: { }
            annotations: { }
            commonLabels: { }
            pods:
              labels: { }
              annotations: { }
            services:
              labels: { }
              annotations: { }
          telemetry:
            prometheus:
              commonLabels: { }
```

What does everyone think? Is there any other requirement that should be considered as well?

Once we have an agreement, I will provide a first round of review for #788.

Thanks!
