### ISSUE TITLE
K8SSAND-1460 ⁃ Cluster- and dc-level templates should be deep-merged

### ISSUE THREAD

**Issue by adutra** [k8ssandra/k8ssandra-operator#525]
**What happened?**

Consider the following `K8ssandraCluster`:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  # Cluster level
  stargate:
    size: 1
    heapSize: 512Mi
  cassandra:
    datacenters:
      - metadata:
          name: dc1
        size: 1
        # DC level
        stargate:
          size: 1
          racks:
            # Rack level
            - name: rack1
```

If I deploy this CRD, the observed heap size for Stargate nodes is `256Mi` (the default).

**Did you expect to see something different?**

I would expect the heap size of all Stargate nodes to be `512Mi`.

This is because the `Coalesce` methods do not merge fields, they simply pick the first non-nil template. In the above example, the Rack template wins over the DC template and the cluster template, so it gets applied, and its heap size is 256Mi (the default).

Note that many e2e are wrongly conceived because of that. They try to set the heap size cluster-wide, yet it is not applied because there is a DC or Rack template somewhere.

**How to reproduce it (as minimally and precisely as possible)**:

Use the above CRD.

**Environment**

* K8ssandra Operator version: 1.0.0

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1460) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1460
┆priority: Medium
