### ISSUE TITLE
Superuser secret is not getting updated with a new secret reference

### ISSUE THREAD

**Issue by andrey-dubnik** [k8ssandra/k8ssandra-operator#566]
**What happened?**

We would like to change the superuser secret reference from default `dev-westeurope-01-superuser` to cassandra-superuser (password will remain the same, we just wanted to have manual secret)

We have added a block below which works for the new builds

```
cassandra:          
    superuserSecretRef: 
        name: cassandra-superuser
```

What we found is this block does not let us change the existing secret reference

```
1.6551330905527017e+09	DEBUG	events	Warning	{"object": {"kind":"CassandraDatacenter","namespace":"temporal-state","name":"primary","uid":"71dc3bb0-708f-4993-8be5-fae8129e85e0","apiVersion":"cassandra.datastax.com/v1beta1","resourceVersion":"205502018"}, "reason": "ValidationFailed", "message": "Could not load superuser secret for CassandraCluster: temporal-state/dev-westeurope-01-superuser"}
```

We have checked the CassandraDatacenter object reference and indeed this is not updated

```
spec:
  superuserSecretName: dev-westeurope-01-superuser
  systemLoggerResources: {}
  users:
  - secretName: cassandra-reaper-cql
    superuser: true
  - secretName: cassandra-medusa
    superuser: true
```

**Did you expect to see something different?**

I would expect the superuser reference to be updated

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster with a default superuser secret
Update the cluster to use a different superuser secret

**Environment**

* K8ssandra Operator version: v1.1.1

* Kubernetes version information: "v1.22

* Kubernetes cluster kind: AKS

**Comment by jsanda** [comment]
cass-operator does not allow the superuser secret reference to be updated to point to a different secret. We should allow the secret reference to change in order to better support rotating and changing credentials. I will create an issue in cass-operator for this.

k8ssandra-operator does allow the reference to be changed which means we unfortunately have some inconsistent behavior.

I have some questions for your to help with the investigation.

Did you deploy the operators with their validating webhooks? If so you should see something like this:

```
kubectl get validatingwebhookconfigurations
NAME                                                  WEBHOOKS   AGE
cass-operator-validating-webhook-configuration        1          7d4h
cert-manager-webhook                                  1          7d4h
k8ssandra-operator-validating-webhook-configuration   1          7d4h
```

I ask because the validating webhook for cass-operator prevents the superuser secret reference from being updated. The error you hit happens during reconciliation in cass-operator which means after the webhook runs.

Can you describe the topology for your K8ssandraCluster. Is it deployed across multiple k8s clusters, multiple namespaces?

Is the new secret in the same namespace as the K8ssandraCluster? It needs to be in the same namespace as the K8ssandraCluster.

Can you check and see if the secret has these labels:

```yaml
app.kubernetes.io/managed-by: k8ssandra-operator
k8ssandra.io/cluster-name: <your-cluster-name>
k8ssandra.io/cluster-namespace: <your-cluster-namespace>
```

The secret needs to have those labels in order to get replicated to the namespaces/k8s clusters where the CassandraDatacenters are deployed. The error you reported is triggered when cass-operator cannot find the secret. This makes me wonder if the secret was replicated.

**Comment by andrey-dubnik** [comment]
And yes - the secret we have is in the same namespace with both the operator and cassandra cluster. We only have one cassandra cluster per k8s cluster at the moment.

**Comment by jsanda** [comment]
Based on what you reported the cass-operator webhook, `cass-operator-validating-webhook-configuration`, is not deployed. That makes sense given the original error you hit. How did you install k8ssandra-operator? I am curious how you wound up with the k8ssandra-operator webhook deployed but not the cass-operator one.

Go ahead and add the labels to the secret.

Can you share your K8ssandraCluster spec?

**Comment by andrey-dubnik** [comment]
We use flux to deploy things

This is a normal helm release deployment which seem to be all default values

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8ssandra
  namespace: temporal-state
spec:
  releaseName: k8ssandra
  interval: 5m
  chart:
    spec:
      chart: k8ssandra-operator
      version: "=0.37.3"
      sourceRef:
        kind: HelmRepository
        name: k8ssandra
        namespace: temporal-state
  values:
    cass-operator:
      resources: 
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 50m
          memory: 50Mi
    resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 256Mi
```

The cluster specs are following

```
      apiVersion: k8ssandra.io/v1alpha1
      kind: K8ssandraCluster
      metadata:
        name: ${CASSANDRA_CLUSTER_NAME}
        namespace: temporal-state
      spec:
        reaper:
          cassandraUserSecretRef: 
            name: cassandra-reaper-cql
          jmxUserSecretRef: 
            name: cassandra-reaper-jmx
          uiUserSecretRef: 
            name: cassandra-reaper-ui
        medusa:
          cassandraUserSecretRef: 
            name: cassandra-medusa
          storageProperties:
            storageProvider: azure_blobs
            storageSecretRef:
              name: medusa-azure-credentials
            bucketName: cassandra-backups
        cassandra:          
          serverVersion: "4.0.3"
          superuserSecretRef: 
            name: cassandra-superuser
          datacenters:
            - metadata:
                name: ${CASSANDRA_DATACENTER}
                labels:
                  env: ${ENVIRONMENT_NAME}
                  app: temporal
                  product_id: service-composition
                  provider: azure
                  region: westeurope
                  k8s_cluster: ${CLUSTER_NAME}
                annotations:
                  prometheus.io/scrape: 'true'
                  prometheus.io/port: '9103'
              telemetry:
                prometheus:
                  enabled: true
              size: 3
              storageConfig:
                cassandraDataVolumeClaimSpec:
                  storageClassName: cassandra-csi
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 1Ti
              resources:
                requests:
                  cpu: 2000m
                  memory: 10Gi
                limits:
                  cpu: 3500m
                  memory: 10Gi
              config:
                jvmOptions:
                  heapSize: 8G
                  gc: G1GC
                  gc_g1_rset_updating_pause_time_percent: 5
                  gc_g1_max_gc_pause_ms: 300
              racks:
              - name: az-1
                nodeAffinityLabels:
                  cassandra-rack: az1
              - name: az-2
                nodeAffinityLabels:
                  cassandra-rack: az2
              - name: az-3
                nodeAffinityLabels:
                  cassandra-rack: az3
```
