### ISSUE TITLE
K8SSAND-1563 ⁃ error "Exception encountered during startup: The seed provider lists no seeds" when recreating pods

### ISSUE THREAD

**Issue by Tom910** [k8ssandra/k8ssandra-operator#567]
**What happened?**

When I have many cass clusters and run `kubectl delete --all pods --namespace k8s-cluster-test` after this command 70% of clusters would recover but 30% of clusters would have the error `Exception encountered during startup: The seed provider lists no seeds.`

cluster logs

```
WARN  [main] 2022-06-14 11:52:25,312 K8SeedProvider4x.java:58 - Seed provider couldn't lookup host test-clusterr-37-seed-service
WARN  [main] 2022-06-14 11:52:25,338 K8SeedProvider4x.java:58 - Seed provider couldn't lookup host test-clusterr-37-dctestr-37-additional-seed-service
ERROR [main] 2022-06-14 11:52:25,340 CassandraDaemon.java:909 - Exception encountered during startup: The seed provider lists no seeds.
```

dns check on cass nodes

```
❯ kubectl exec --stdin --tty -n k8s-cluster-test test-clusterr-37-dctestr-37-default-sts-0 -- /bin/bash

cassandra@test-clusterr-37-dctestr-37-default-sts-0:/$ curl test-clusterr-37-seed-service
curl: (6) Could not resolve host: test-clusterr-37-seed-service

cassandra@test-clusterr-37-dctestr-37-default-sts-0:/$ curl test-clusterr-37-dctestr-37-all-pods-service
curl: (7) Failed to connect to test-clusterr-37-dctestr-37-all-pods-service port 80: Connection refused
```

At the same time, the cluster is repaired if you delete the pods again

**Did you expect to see something different?**

I want to see 100% recover clusters

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* K8ssandra Operator version:

    `github.com/k8ssandra/k8ssandra-operator/config/deployments/control-plane/cluster-scope?ref=v1.1.1`
    
    * Kubernetes version information:

    `v1.21.5` coredns = 1.6.3
    * Kubernetes cluster kind:

```
managed
```

* Manifests:

I have 40 similar clusters like:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test-clusterr-37
  namespace: k8s-cluster-test
spec:
  cassandra:
    serverVersion: "4.0.1"
    softPodAntiAffinity: true
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1900m"
        memory: "2Gi"
    datacenters:
      - metadata:
          name: dctestr-37
        size: 2
        storageConfig:
          cassandraDataVolumeClaimSpec:
            resources:
              requests:
                storage: 2Gi
        config:
          jvmOptions:
            heapSize: 256M

```

* K8ssandra Operator Logs:

```
1.655210188848521e+09   INFO    controller.k8ssandracluster     Reconciling Medusa user secrets {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test-clusterr-37", "namespace": "k8s-cluster-test", "K8ssandraCluster": "k8s-cluster-test/test-clusterr-37"}
1.6552101888485692e+09  INFO    controller.k8ssandracluster     Medusa user secrets successfully reconciled     {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test-clusterr-37", "namespace": "k8s-cluster-test", "K8ssandraCluster": "k8s-cluster-test/test-clusterr-37"}
1.655210188848572e+09   INFO    controller.k8ssandracluster     Reconciling replicated secrets  {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test-clusterr-37", "namespace": "k8s-cluster-test", "K8ssandraCluster": "k8s-cluster-test/test-clusterr-37"}
1.655210188848788e+09   INFO    controller.k8ssandracluster     Medusa reconcile for dctestr-37 on namespace k8s-cluster-test   {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test-clusterr-37", "namespace": "k8s-cluster-test", "K8ssandraCluster": "k8s-cluster-test/test-clusterr-37"}
1.655210188848799e+09   INFO    controller.k8ssandracluster     Medusa is not enabled   {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test-clusterr-37", "namespace": "k8s-cluster-test", "K8ssandraCluster": "k8s-cluster-test/test-clusterr-37"}
1.6552101888513434e+09  INFO    controller.k8ssandracluster     Reconciling seeds       {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test-clusterr-37", "namespace": "k8s-cluster-test", "K8ssandraCluster": "k8s-cluster-test/test-clusterr-37", "CassandraDatacenter": "k8s-cluster-test/dctestr-37", "K8SContext": ""}
1.6552101888514278e+09  INFO    controller.k8ssandracluster     The datacenter is reconciled    {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test-clusterr-37", "namespace": "k8s-cluster-test", "K8ssandraCluster": "k8s-cluster-test/test-clusterr-37", "CassandraDatacenter": "k8s-cluster-test/dctestr-37", "K8SContext": ""}
1.6552101888591702e+09  DEBUG   controller-runtime.webhook.webhooks     received request        {"webhook": "/validate-k8ssandra-io-v1alpha1-k8ssandracluster", "UID": "bd0f9a93-61da-44ff-88fb-3f19a6955a6c", "kind": "k8ssandra.io/v1alpha1, Kind=K8ssandraCluster", "resource": {"group":"k8ssandra.io","version":"v1alpha1","resource":"k8ssandraclusters"}}
1.6552101888596108e+09  INFO    k8ssandracluster-webhook        validate K8ssandraCluster update        {"K8ssandraCluster": "test-clusterr-37"}
1.6552101888596413e+09  DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/validate-k8ssandra-io-v1alpha1-k8ssandracluster", "code": 200, "reason": "", "UID": "bd0f9a93-61da-44ff-88fb-3f19a6955a6c", "allowed": true}
1.6552101888640745e+09  INFO    controller.k8ssandracluster     Preparing to update replication for system keyspaces    {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test-clusterr-37", "namespace": "k8s-cluster-test", "K8ssandraCluster": "k8s-cluster-test/test-clusterr-37", "CassandraDatacenter": "k8s-cluster-test/dctestr-37", "K8SContext": "", "replication": {"dctestr-37":2}}
1.6552101888641243e+09  INFO    controller.k8ssandracluster     Ensuring that keyspace system_traces exists in cluster test-clusterr-37...      {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test-clusterr-37", "namespace": "k8s-cluster-test", "K8ssandraCluster": "k8s-cluster-test/test-clusterr-37", "CassandraDatacenter": "k8s-cluster-test/dctestr-37", "K8SContext": ""}
1.6552101888643324e+09  ERROR   controller.k8ssandracluster     Failed to fetch datacenter pods {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test-clusterr-37", "namespace": "k8s-cluster-test", "K8ssandraCluster": "k8s-cluster-test/test-clusterr-37", "CassandraDatacenter": "k8s-cluster-test/dctestr-37", "K8SContext": "", "error": "no pods in READY state found in datacenter dctestr-37"}
github.com/k8ssandra/k8ssandra-operator/pkg/cassandra.(*defaultManagementApiFacade).EnsureKeyspaceReplication
        /workspace/pkg/cassandra/management.go:289
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).updateReplicationOfSystemKeyspaces
        /workspace/controllers/k8ssandra/schemas.go:183
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).checkSchemas
        /workspace/controllers/k8ssandra/schemas.go:43
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).reconcileDatacenters
        /workspace/controllers/k8ssandra/datacenters.go:168
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).reconcile
        /workspace/controllers/k8ssandra/k8ssandracluster_controller.go:133
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).Reconcile
        /workspace/controllers/k8ssandra/k8ssandracluster_controller.go:87
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
1.6552101888643928e+09  ERROR   controller.k8ssandracluster     Failed to update replication    {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test-clusterr-37", "namespace": "k8s-cluster-test", "K8ssandraCluster": "k8s-cluster-test/test-clusterr-37", "CassandraDatacenter": "k8s-cluster-test/dctestr-37", "K8SContext": "", "keyspace": "system_traces", "error": "no pods in READY state found in datacenter dctestr-37"}
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).checkSchemas
        /workspace/controllers/k8ssandra/schemas.go:43
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).reconcileDatacenters
        /workspace/controllers/k8ssandra/datacenters.go:168
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).reconcile
        /workspace/controllers/k8ssandra/k8ssandracluster_controller.go:133
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).Reconcile
        /workspace/controllers/k8ssandra/k8ssandracluster_controller.go:87
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
1.6552101888729985e+09  INFO    controller.k8ssandracluster     updated k8ssandracluster status {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test-clusterr-37", "namespace": "k8s-cluster-test", "K8ssandraCluster": "k8s-cluster-test/test-clusterr-37"}
1.6552101888730514e+09  ERROR   controller.k8ssandracluster     Reconciler error        {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test-clusterr-37", "namespace": "k8s-cluster-test", "error": "no pods in READY state found in datacenter dctestr-37"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
```

**Anything else we need to know?**:

I found a similar issue - https://github.com/kubernetes/kubernetes/issues/92559 about DNS cache but I don't have oportunity change this parameters right now

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1563) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1563
┆priority: Medium

**Comment by Tom910** [comment]
Additional information
```
❯ kubectl get pods test-clusterr-37-dctestr-37-default-sts-0 -n k8s-cluster-test -o yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-06-14T11:21:21Z"
  generateName: test-clusterr-37-dctestr-37-default-sts-
  labels:
    app.kubernetes.io/instance: cassandra-test-clusterr-37
    app.kubernetes.io/managed-by: cass-operator
    app.kubernetes.io/name: cassandra
    app.kubernetes.io/version: 4.0.1
    cassandra.datastax.com/cluster: test-clusterr-37
    cassandra.datastax.com/datacenter: dctestr-37
    cassandra.datastax.com/node-state: Starting
    cassandra.datastax.com/rack: default
    controller-revision-hash: test-clusterr-37-dctestr-37-default-sts-78698c559b
    statefulset.kubernetes.io/pod-name: test-clusterr-37-dctestr-37-default-sts-0
  name: test-clusterr-37-dctestr-37-default-sts-0
```

```
❯ kubectl get svc test-clusterr-37-seed-service -n k8s-cluster-test -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    cassandra.datastax.com/resource-hash: n6slxhCbAHOHCzjD4a6VkgBOeGLkAVQ+cLrpmZHxNKI=
  creationTimestamp: "2022-06-10T11:55:32Z"
  labels:
    app.kubernetes.io/instance: cassandra-test-clusterr-37
    app.kubernetes.io/managed-by: cass-operator
    app.kubernetes.io/name: cassandra
    app.kubernetes.io/version: 4.0.1
    cassandra.datastax.com/cluster: test-clusterr-37
  name: test-clusterr-37-seed-service
  namespace: k8s-cluster-test
  ownerReferences:
  - apiVersion: cassandra.datastax.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CassandraDatacenter
    name: dctestr-37
    uid: ed346db6-6df8-47e3-b555-0a55139f92c2
  resourceVersion: "397321"
  uid: 0ca4f1a1-0f22-47e5-a892-42d7304af523
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  publishNotReadyAddresses: true
  selector:
    cassandra.datastax.com/cluster: test-clusterr-37
    cassandra.datastax.com/seed-node: "true"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

as result pod didn't have `cassandra.datastax.com/seed-node: "true"` and service don't work correctly
