### ISSUE TITLE
Medusa same cluster Restore is failing because it is looking for data with node ips instead that kubernetes pod names

### ISSUE THREAD

**Issue by grassiale** [k8ssandra/k8ssandra-operator#585]
**What did you do?**
We are performing a medusa backup of a cassandra datacenter with 3 racks and trying to restore the data on the same cluster. We are not achieving that because medusa-restore is apparently trying to download data from folders that refer to ips of cassandra nodes instead of their pod names. Actually only one of the pods is able to restore the data correctly, the other ones are left by the operator in a podInitCrashloopBackoff state. There are some errors presented below in the operator logs, but they don't tell me much.
Fun fact, when I tried the same procedure on a 2 racks cluster, it worked. But with the same error in logs.

**Did you expect to see some different?**
We were expecting medusa restore to download data from the same paths on s3 they were uploaded to on all nodes

**Environment**

* K8ssandra Operator version:

    `v1.1.1`

* Kubernetes version information:

    `  Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:

    EKS 1.21
* Manifests:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: k8ssandra-backup-test
spec:
  auth: false
  cassandra: 
    serverVersion: "4.0.4"
    serverImage: "k8ssandra/cass-management-api:4.0.4-v0.1.40"
    telemetry: 
      prometheus:
        enabled: true
    datacenters:
    - metadata:
        name: dc-backup-test
      size: 3
      config:
        jvmOptions:
          heapSize: "15G"
          additionalOptions:
            - "-Dcassandra.system_distributed_replication_dc_names=dc-backup-test"
            - "-Dcassandra.system_distributed_replication_per_dc=3"
        cassandraYaml:
          num_tokens: 32
          allocate_tokens_for_local_replication_factor: 3
          authenticator: AllowAllAuthenticator
          authorizer: AllowAllAuthorizer
          role_manager: CassandraRoleManager
          read_request_timeout_in_ms: 8000
          write_request_timeout_in_ms: 6000
          request_timeout_in_ms: 12000
          compaction_throughput_mb_per_sec: 200
          concurrent_compactors: 32 
          stream_entire_sstables: true
          stream_throughput_outbound_megabits_per_sec: 61440
          streaming_connections_per_host: 6
      storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: ssd
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 400Gi
            persistentVolumeReclaimPolicy: Retain
      networking:
        nodePort:
          native: 30001
          internode: 30002
      resources:
        requests:
          memory: 60Gi
          cpu: 7000m
      racks:
        - name: rack-a
          nodeAffinityLabels:
            topology.kubernetes.io/zone: eu-west-1a
        - name: rack-b
          nodeAffinityLabels:
            topology.kubernetes.io/zone: eu-west-1b
        - name: rack-c
          nodeAffinityLabels:
            topology.kubernetes.io/zone: eu-west-1c
  medusa:
    storageProperties:
      storageProvider: s3
      storageSecretRef:
        name: medusa-bucket-key
      bucketName: bucket-name
      prefix: cassandra-small
      region: eu-west-1
      transferMaxBandwidth: 5000MB/s
      concurrentTransfers: 16
```
```
apiVersion: medusa.k8ssandra.io/v1alpha1
kind: MedusaBackupJob
metadata:
  name: backup-20220623-dc-backup-test
spec:
  cassandraDatacenter: dc-backup-test
  backupType: full
```
```
apiVersion: medusa.k8ssandra.io/v1alpha1
kind: MedusaRestoreJob
metadata:
  name: restore-20220623-dc-backup-test
spec:
  cassandraDatacenter: dc-backup-test
  backup: backup-20220623-dc-backup-test
```
* K8ssandra Operator Logs:

```
1.655995580045647e+09	INFO	controller.medusarestorejob	Starting reconcile	{"reconciler group": "medusa.k8ssandra.io", "reconciler kind": "MedusaRestoreJob", "name": "restore-20220623-dc-small", "namespace": "k8ssandra", "medusarestorejob": "k8ssandra/restore-20220623-dc-small", "MedusaRestoreJob": "restore-20220623-dc-small"}
1.6559955800583858e+09	INFO	controller.medusarestorejob	updated MedusaRestoreJob with owner reference	{"reconciler group": "medusa.k8ssandra.io", "reconciler kind": "MedusaRestoreJob", "name": "restore-20220623-dc-small", "namespace": "k8ssandra", "medusarestorejob": "k8ssandra/restore-20220623-dc-small", "CassandraDatacenter": {"namespace": "k8ssandra", "name": "dc-backup-test"}}
1.655995580060357e+09	INFO	controller.medusarestorejob	Starting reconcile	{"reconciler group": "medusa.k8ssandra.io", "reconciler kind": "MedusaRestoreJob", "name": "restore-20220623-dc-small", "namespace": "k8ssandra", "medusarestorejob": "k8ssandra/restore-20220623-dc-small", "MedusaRestoreJob": "restore-20220623-dc-small"}
1.6559955800707614e+09	INFO	controller.medusatask	Starting reconciliation for MedusaTask{"reconciler group": "medusa.k8ssandra.io", "reconciler kind": "MedusaTask", "name": "f6d50670-9b1c-4e45-a27b-5973e73781d3", "namespace": "k8ssandra", "MedusaTask": "k8ssandra/f6d50670-9b1c-4e45-a27b-5973e73781d3", "cassdc": "dc-backup-test"}
1.655995580077983e+09	INFO	controller.medusatask	updated task with owner reference	{"reconciler group": "medusa.k8ssandra.io", "reconciler kind": "MedusaTask", "name": "f6d50670-9b1c-4e45-a27b-5973e73781d3", "namespace": "k8ssandra", "MedusaTask": "k8ssandra/f6d50670-9b1c-4e45-a27b-5973e73781d3", "cassdc": "dc-backup-test", "CassandraDatacenter": {"namespace": "k8ssandra", "name": "dc-backup-test"}}
1.6559955800791261e+09	INFO	controller.medusatask	Starting reconciliation for MedusaTask{"reconciler group": "medusa.k8ssandra.io", "reconciler kind": "MedusaTask", "name": "f6d50670-9b1c-4e45-a27b-5973e73781d3", "namespace": "k8ssandra", "MedusaTask": "k8ssandra/f6d50670-9b1c-4e45-a27b-5973e73781d3", "cassdc": "dc-backup-test"}
1.6559955800794597e+09	INFO	controller.medusatask	Starting prepare restore operations	{"reconciler group": "medusa.k8ssandra.io", "reconciler kind": "MedusaTask", "name": "f6d50670-9b1c-4e45-a27b-5973e73781d3", "namespace": "k8ssandra", "MedusaTask": "k8ssandra/f6d50670-9b1c-4e45-a27b-5973e73781d3", "cassdc": "dc-backup-test", "cassdc": "dc-backup-test"}
1.6559955800893202e+09	INFO	controller.medusarestorejob	Starting reconcile	{"reconciler group": "medusa.k8ssandra.io", "reconciler kind": "MedusaRestoreJob", "name": "restore-20220623-dc-small", "namespace": "k8ssandra", "medusarestorejob": "k8ssandra/restore-20220623-dc-small", "MedusaRestoreJob": "restore-20220623-dc-small"}
1.655995580090005e+09	ERROR	controller.medusarestorejob	Failed to prepare restore	{"reconciler group": "medusa.k8ssandra.io", "reconciler kind": "MedusaRestoreJob", "name": "restore-20220623-dc-small", "namespace": "k8ssandra", "medusarestorejob": "k8ssandra/restore-20220623-dc-small", "error": "prepare restore task failed for restore restore-20220623-dc-small"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
1.65599558009014e+09	ERROR	controller.medusarestorejob	Reconciler error	{"reconciler group": "medusa.k8ssandra.io", "reconciler kind": "MedusaRestoreJob", "name": "restore-20220623-dc-small", "namespace": "k8ssandra", "error": "prepare restore task failed for restore restore-20220623-dc-small"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
1.6559955800904531e+09	INFO	controller.medusatask	starting pod operation	{"reconciler group": "medusa.k8ssandra.io", "reconciler kind": "MedusaTask", "name": "f6d50670-9b1c-4e45-a27b-5973e73781d3", "namespace": "k8ssandra", "MedusaTask": "k8ssandra/f6d50670-9b1c-4e45-a27b-5973e73781d3", "cassdc": "dc-backup-test", "Operation": "prepare restore", "CassandraPod": "k8ssandra-backup-test-dc-backup-test-rack-b-sts-0"}
1.6559955800908427e+09	INFO	controller.medusatask	Starting reconciliation for MedusaTask{"reconciler group": "medusa.k8ssandra.io", "reconciler kind": "MedusaTask", "name": "f6d50670-9b1c-4e45-a27b-5973e73781d3", "namespace": "k8ssandra", "MedusaTask": "k8ssandra/f6d50670-9b1c-4e45-a27b-5973e73781d3", "cassdc": "dc-backup-test"}
1.6559955800908892e+09	INFO	controller.medusatask	Tasks already in progress	{"reconciler group": "medusa.k8ssandra.io", "reconciler kind": "MedusaTask", "name": "f6d50670-9b1c-4e45-a27b-5973e73781d3", "namespace": "k8ssandra", "MedusaTask": "k8ssandra/f6d50670-9b1c-4e45-a27b-5973e73781d3", "cassdc": "dc-backup-test"}
1.6559955800957592e+09	INFO	controller.medusarestorejob	Starting reconcile	{"reconciler group": "medusa.k8ssandra.io", "reconciler kind": "MedusaRestoreJob", "name": "restore-20220623-dc-small", "namespace": "k8ssandra", "medusarestorejob": "k8ssandra/restore-20220623-dc-small", "MedusaRestoreJob": "restore-20220623-dc-small"}```

**Anything else we need to know?**:
Logs from the container:
[medusa-restore-logs.log](https://github.com/k8ssandra/k8ssandra-operator/files/8968516/medusa-restore-logs.log)
