### ISSUE TITLE
Some metrics are exported in the format not complatible with Prometheus - mcac_hints_hints_created.10.1.0.251.7000_total

### ISSUE THREAD

**Issue by andrey-dubnik** [k8ssandra/k8ssandra-operator#589]
**What happened?**

Service monitor relabels some metrics in the incompatible prometheus format like mcac_hints_hints_created.10.1.0.251.7000_total

This is likely caused by the mcac bein in a format like this

```
collectd_mcac_counter_total{mcac="org.apache.cassandra.metrics.hints_service.hints_created.10.2.4.178.7000",instance="10.2.4.124",cluster="cdt-westeurope-01",dc="secondary",rack="az-1"} 76 1656419282037
```

And the service monitor relabeling the metric purely on mcac content 

https://github.com/k8ssandra/k8ssandra-operator/blob/d728668b76cf1e9da2eeb78842ecfb2c7cade49f/pkg/telemetry/prom_cass_servicemonitor.go#L231

```
   - regex: org\.apache\.cassandra\.metrics\.hints_service\.([^\-]+)
      replacement: mcac_hints_${1}
      sourceLabels:
      - mcac
      targetLabel: __name__
```

which leads to a wrong format as metrics have dots in it

**Did you expect to see something different?**

Relabeling should also replace dots with underscores

**How to reproduce it (as minimally and precisely as possible)**:

It is a standard metrics feed
