### ISSUE TITLE
K8SSAND-1612 ⁃ How I can delete specific node, and resize cluster?

### ISSUE THREAD

**Issue by AntonDzyk** [k8ssandra/k8ssandra-operator#595]
**What did you do?**
I have 3 k8s nodes with k8ssandra cluster. I can drain number 2 node. If I change size K8SsandraCluster size, deleting number 3 node.

**Did you expect to see some different?**
first:

```
$ kubectl get pod -n cassandra -w -o wide
NAME                                                READY   STATUS    RESTARTS   AGE     IP             NODE       NOMINATED NODE   READINESS GATES
k8ssandra-operator-cass-operator-59956b455b-22k5b   1/1     Running   0          7m12s   10.244.1.5     cass-m02   <none>           <none>
k8ssandra-operator-ffb675cd9-94l4f                  1/1     Running   0          7m12s   10.244.2.4     cass-m03   <none>           <none>
test123-dc1-rack1-sts-0                             2/2     Running   0          6m48s   192.168.49.3   cass-m02   <none>           <none>
test123-dc1-rack1-sts-1                             2/2     Running   0          6m48s   192.168.49.4   cass-m03   <none>           <none>
test123-dc1-rack1-sts-2                             2/2     Running   0          6m48s   192.168.49.2   cass       <none>           <none>
```

change size:

```
$ kubectl get pod -n cassandra -w -o wide
NAME                                                READY   STATUS    RESTARTS   AGE     IP             NODE       NOMINATED NODE   READINESS GATES
k8ssandra-operator-cass-operator-59956b455b-22k5b   1/1     Running   0          11m     10.244.1.5     cass-m02   <none>           <none>
k8ssandra-operator-ffb675cd9-94l4f                  1/1     Running   0          11m     10.244.2.4     cass-m03   <none>           <none>
test123-dc1-rack1-sts-0                             2/2     Running   0          11m     192.168.49.3   cass-m02   <none>           <none>
test123-dc1-rack1-sts-1                             2/2     Running   0          11m     192.168.49.4   cass-m03   <none>           <none>
test123-dc1-reaper-646989f667-w2ffl                 1/1     Running   0          5m50s   10.244.1.7     cass-m02   <none>           <none>
```

**Environment**

* K8ssandra Operator version:

    `Insert image tag or Git SHA here`
    k8ssandra/k8ssandra-operator:v1.1.1
    k8ssandra/cass-operator:v1.11.0* Kubernetes version information:

    `kubectl version`
    Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.11", GitCommit:"5824e3251d294d324320db85bf63a53eb0767af2", GitTreeState:"clean", BuildDate:"2022-06-16T05:33:55Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}* Kubernetes cluster kind:

```
minikube, docker driver, 3 nodes.
```

* Manifests:

first:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test123
spec:
  reaper: {}
  cassandra:
    serverVersion: "3.11.13"
    softPodAntiAffinity: true
    resources:
      requests:
        cpu: "150m"
    networking:
      hostNetwork: true
    datacenters:
      - metadata:
          name: dc1
        size: 3
        racks:
        - name: rack1
          nodeAffinityLabels:
            cassandra.node: used
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 512M
```

change size:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test123
spec:
  reaper: {}
  cassandra:
    serverVersion: "3.11.13"
    softPodAntiAffinity: true
    resources:
      requests:
        cpu: "150m"
    networking:
      hostNetwork: true
    datacenters:
      - metadata:
          name: dc1
        size: 2
        racks:
        - name: rack1
          nodeAffinityLabels:
            cassandra.node: used
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 512M
```

* K8ssandra Operator Logs:

```

```

**Anything else we need to know?**:
How can I delete node "cass-m03" with test123-dc1-rack1-sts-1, and resize k8ssandraCluster?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1612) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1612
┆priority: Medium
