### ISSUE TITLE
K8SSAND-1643 ⁃ Cassandra fails to tag any node as seed when additionalSeeds are provided

### ISSUE THREAD

**Issue by andrey-dubnik** [k8ssandra/k8ssandra-operator#618]
**What happened?**

Cassandra fails to start with all nodes pending forever for the seeds

**Did you expect to see something different?**

At least one node of the current DC should be delegated as a seed node

**How to reproduce it (as minimally and precisely as possible)**:

Deploy k8cs DC with the configuration, it will start nodes but will never join them as none of the nodes will have a seed label applied. If additionalSeeds are removed then nodes can start successfully as at least one of the nodes is going to have a seed label.

```
apiVersion: k8ssandra.io/v1alpha1
      kind: K8ssandraCluster
      metadata:
        name: test-cluster
        namespace: cassandra
      spec:
        cassandra:          
          serverVersion: "4.0.3"
          additionalSeeds:
            - 10.2.0.153
          datacenters:
            - metadata:
                name: test-cp
                annotations:
                  prometheus.io/scrape: 'true'
                  prometheus.io/port: '9103'
              telemetry:
                prometheus:
                  enabled: true
              size: 3
              storageConfig:
                cassandraDataVolumeClaimSpec:
                  storageClassName: local-path
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 1Ti
              resources:
                requests:
                  cpu: 500m
                  memory: 2Gi
                limits:
                  cpu: 500m
                  memory: 2Gi
              config:
                jvmOptions:
                  heapSize: 512M
                  gc: G1GC
                  gc_g1_rset_updating_pause_time_percent: 5
                  gc_g1_max_gc_pause_ms: 300
              racks:
              - name: az-1
              - name: az-2
              - name: az-3
```

**Environment**

* K8ssandra Operator version: 1.1.1
* `kubectl version`:  1.22

```
insert how you created your cluster: kops, bootkube, etc.
```

* K8ssandra Operator Logs:

```
No errors of any kind
```

**Anything else we need to know?**:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1643) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1643
┆priority: Medium
