### ISSUE TITLE
K8SSAND-1704 ⁃ Decommissioning datacenter does not work unless k8sContext is set

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#642]
**What happened?**
Someone on Discord reported a problem with deleting a datacenter (see [here](https://discord.com/channels/836217371453685760/836217371453685763/1002205193879953439)). The replication of keyspaces is updated, removing the DC as expected. k8ssandra-operator reports that the deletion happens, but the CassandraDatacenter is neither decommissioned nor deleted.

For reference a decommissioning a DC is done simply by removing it from the K8ssandraCluster spec. On a subsequent reconciliation, k8ssandra-operator detects that the DC is removed by comparing the DCs in the spec to those in the status, and then starts the decommissioning process.

**Did you expect to see something different?**
Removing a DC from the K8ssandraCluster should result in the following:

* The DC should be removed from the replication strategy of all keyspaces
* Every C* node in the DC should be decommissioned
* The CassandraDatacenter should be deleted

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  cassandra:
    serverVersion: "4.0.3"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 1Gi
    # Only needed when running a local k8s distro like kind
    networking:
      hostNetwork: true
    datacenters:
      - metadata:
          name: dc1
          namespace: dev1
        size: 1
      - metadata:
          name: dc2
          namespace: dev2
        size: 1
```

This example requires a cluster-scoped deployment, but the problem will happen with namespace-scoped deployments as well. I was too lazy to set up a multi-cluster environment :) 

**Environment**

* K8ssandra Operator version:

    `v1.2.0`
    
    * Kubernetes version information:

    `kubectl version`
    **Anything else we need to know?**:
The first thing that the `reconcileDatacenters` method does is to call the `checkDcDeletion` [here](https://github.com/k8ssandra/k8ssandra-operator/blob/132f65c1a507ccfea605e21da2208107a93a9a4f/controllers/k8ssandra/datacenters.go#L34).

After replication settings are updated the `deleteDc` method is called [here](https://github.com/k8ssandra/k8ssandra-operator/blob/132f65c1a507ccfea605e21da2208107a93a9a4f/controllers/k8ssandra/cleanup.go#L147). This method first attempts to delete any Stargate and Reaper instances that are deployed with the DC. Then `findDcForDeletion` is called [here](https://github.com/k8ssandra/k8ssandra-operator/blob/132f65c1a507ccfea605e21da2208107a93a9a4f/controllers/k8ssandra/cleanup.go#L178).

The problem is in the `if` block:

```go
if remoteClient == nil {
	for _, remoteClient := range r.ClientCache.GetRemoteClients() {
		err := remoteClient.List(ctx, dcList, options)
		if err != nil {
			return nil, nil, fmt.Errorf("failed to CassandraDatacenter (%s) for DC (%s) deletion: %v", dcName, dcName, err)
		}
		for _, dc := range dcList.Items {
			if dc.Name == dcName {
				return &dc, remoteClient, nil
			}
		}
	}
```

We iterate over the remote clients from the ClientCache in search of the DC. We have to do this because we no longer know in which cluster the CassandraDatacenter was deployed. If the DC is in the local, control plane cluster and`k8sContext` is not set, then the DC won't be found. This is because `r.ClientCache.GetRemoteClients` does not include a client for the local, control plane cluster.

An easy fix for this is to also iterate over the local, control plane client, maybe introduce a method like `ClientCache.GetAllClients()`.

Lastly, the same iteration logic is used in the methods do delete Stargate and Reaper which means they won't be deleted either. The `findStargateForDeletion` and `findReaperForDeletion` methods need to be updated as well.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1704) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1704
┆priority: Medium
