### ISSUE TITLE
K8SSAND-1723 ⁃ JMX does not appear accessible via a port forward

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#646]
**What happened?**

Attempting to access JMX via a k8s port-forward does not appear to work.

**Did you expect to see something different?**

Yes, JMX should be accessible when forwarding a local port to the cassandra pod's JMX port.

**How to reproduce it (as minimally and precisely as possible)**:

Apply the below manifest, run:

```
kubectl port-forward test-dc1-default-sts-0 10000:7199
```

Try to launch jconsole and connect to localhost:10000.

You should see a failed connection.

**Environment**

* Manifests:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  auth: false
  cassandra:
    telemetry:
      prometheus:
        enabled: true
    serverVersion: "4.0.4"
    datacenters:
      - metadata:
          name: dc1
        size: 1
        cdc:
          pulsarServiceUrl: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 384Mi
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1723) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1723
┆priority: Medium
