### ISSUE TITLE
K8SSAND-1732 ⁃ DC level config overwrites cluster level config with no merge behaviour

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#651]
**What happened?**

DC level config will overwrite cluster level config with no merge behaviour.

**Did you expect to see something different?**

In the below manifest, we'd expect to see configs from both the cluster level and DC level both merged together. What we actually see is that only the DC level configs are applied.

**How to reproduce it (as minimally and precisely as possible)**:

Apply the below manifest.

**Environment**

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  auth: false
  cassandra:
    config:
      jvmOptions:
        jmx_connection_type: remote-no-auth
        additionalOptions:
        - -Dcassandra.jmx.remote.port=7199
        - -Djava.rmi.server.hostname=127.0.0.1
        - -Dcom.sun.management.jmxremote.rmi.port=7199
    telemetry:
      prometheus:
        enabled: true
    serverVersion: "4.0.4"
    datacenters:
      - metadata:
          name: dc1
        size: 1
        cdc:
          pulsarServiceUrl: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 512Mi
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1732) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1732
┆priority: Medium
