### ISSUE TITLE
K8SSAND-1769 ⁃ Operator does not handle invalid syntax in K8ssandraCluster creation

### ISSUE THREAD

**Issue by jeff-knurek** [k8ssandra/k8ssandra-operator#673]
**What happened?**

created a K8ssandraCluster manifest and set the rack name to have an `_`. Underscores aren't acceptable characters in pod names. 

The issue is that I created the K8ssandraCluster, everything seemed to be fine, no warnings or errors. But the pods weren't spinning up. Checking the `k8ssandra-operator` logs didn't show any problem. It was only in the `k8ssandra-operator-cass-operator` pod logs did I find the problem. 

> a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"}

**Did you expect to see something different?**

Expected some validation checks to prevent this early in the create process. 

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: example
spec:
  cassandra:
    datacenters:
      - metadata:
          name: dc1
        size: 2
        racks:
          - name: invalid_pod_name
```

* K8ssandra Operator version:

v1.2.0

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1769) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1769
┆priority: Medium
