### ISSUE TITLE
K8SSAND-1782 ⁃ Stargate not working when using encryption

### ISSUE THREAD

**Issue by stdmje** [k8ssandra/k8ssandra-operator#683]
**What happened?**

Stargate is failing to start when i enable encryption in the Cassandra cluster.

**Did you expect to see something different?**

I expected to have a Stargate component working.

**How to reproduce it (as minimally and precisely as possible)**:

As easy as applying this manifest.

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
spec:
  stargate:
    size: 1
  cassandra:
    serverEncryptionStores:
      keystoreSecretRef:
        name: demo-dc1-tls-keystore
      truststoreSecretRef:
        name: demo-dc1-tls-truststore
    clientEncryptionStores:
      keystoreSecretRef:
        name: demo-dc1-tls-keystore
      truststoreSecretRef:
        name: demo-dc1-tls-truststore
    serverVersion: "4.0.5"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: gp3
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 1024M
        additionalOptions:
        - -Djavax.net.debug=all
      cassandraYaml:
        server_encryption_options:
          internode_encryption: all
          require_client_auth: true
        client_encryption_options:
          enabled: true
          require_client_auth: true
    datacenters:
      - metadata:
          name: dc1
        size: 3
        racks:
        - name: eu-west-1a
          nodeAffinityLabels:
            topology.kubernetes.io/zone: eu-west-1a
        - name: eu-west-1b
          nodeAffinityLabels:
            topology.kubernetes.io/zone: eu-west-1b
        - name: eu-west-1c
          nodeAffinityLabels:
            topology.kubernetes.io/zone: eu-west-1c
```

**Environment**

* K8ssandra Operator version: 1.2.0
* Kubernetes version information:

```
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.11-eks-18ef993", GitCommit:"b9628d6d3867ffd84c704af0befd31c7451cdc37", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**:
After enabling `-Djavax.net.debug=all` i can see the following errors in the Cassandra nodes.

```
ERROR [Messaging-EventLoop-3-1] 2022-09-15 09:57:37,574 InboundConnectionInitiator.java:360 - Failed to properly handshake with peer /10.55.93.240:36094. Closing the channel.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1782) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1782
┆priority: Medium
