### ISSUE TITLE
CassandraDatacenters are deployed too soon in multi-DC cluster

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#69]
I observed this behavior in the `CreateMultiDatacenterCluster` e2e test while working on #66.

Here is the manifest with which I have seen this:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  k8sContextsSecret: k8s-contexts
  cassandra:
    cluster: test
    datacenters:
      - metadata:
          name: dc1
        k8sContext: kind-k8ssandra-0
        serverImage: emerkle826/cass-mgmtapi:3.11.11-v0.1.28
        size: 3
        serverVersion: "3.11.10"
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          cassandra-yaml:
            auto_snapshot: false
            memtable_flush_writers: 1
            commitlog_segment_size_in_mb: 2
            concurrent_compactors: 1
            compaction_throughput_mb_per_sec: 0
            sstable_preemptive_open_interval_in_mb: 0
            key_cache_size_in_mb: 0
            thrift_prepared_statements_cache_size_mb: 1
            prepared_statements_cache_size_mb: 1
            start_rpc: false
            slow_query_log_timeout_in_ms: 0
            counter_cache_size_in_mb: 0
            concurrent_reads: 2
            concurrent_writes: 2
            concurrent_counter_writes: 2
          jvm-options:
            initial_heap_size: "448m"
            max_heap_size: "448m"
        resources:
          limits:
             memory: 800Mi
        stargate:
          size: 1
          heapSize: 384Mi
          resources:
            limits:
              memory: 512Mi
          cassandraConfigMap:
            name: cassandra-config
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /checker/liveness
              port: health
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      - metadata:
          name: dc2
        k8sContext: kind-k8ssandra-1
        serverImage: emerkle826/cass-mgmtapi:3.11.11-v0.1.28
        size: 3
        serverVersion: "3.11.10"
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          cassandra-yaml:
            auto_snapshot: false
            memtable_flush_writers: 1
            concurrent_compactors: 1
            commitlog_segment_size_in_mb: 2
            compaction_throughput_mb_per_sec: 0
            sstable_preemptive_open_interval_in_mb: 0
            start_rpc: false
            key_cache_size_in_mb: 0
            thrift_prepared_statements_cache_size_mb: 1
            prepared_statements_cache_size_mb: 1
            slow_query_log_timeout_in_ms: 0
            counter_cache_size_in_mb: 0
            concurrent_reads: 2
            concurrent_writes: 2
            concurrent_counter_writes: 2
          jvm-options:
            initial_heap_size: "448m"
            max_heap_size: "448m"
        resources:
          limits:
            memory: 800Mi
        stargate:
          size: 1
          heapSize: 384Mi
          cassandraConfigMap:
            name: cassandra-config
          resources:
            limits:
              memory: 512Mi
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /checker/liveness
              port: health
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
```

Immediately after Stargate is deployed in the `kind-k8ssandra-0` cluster, dc2 is deployed in the `kind-k8ssandra-1` cluster. 

My intent, at least for now, has been to create the objects serially. When the CassandraDatacenter and Stargate objects in the first cluster reach the ready state, then we move on to deploying objects in subsequent clusters.

It is arguable and possibly even preferable to create some of the objects in parallel. For example, once dc1 is up we can probably safely create the Stargate instance in the first cluster and dc2 in the next cluster in parallel. Right now where we are primarily working with everything running locally in kind clusters I think it is better to first roll things out serially.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-783) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-783
┆Priority: Medium
