### ISSUE TITLE
K8SSAND-1792 ⁃ Build ARM64 Container Images for the K8ssandra Operator and its Ecosystem.

### ISSUE THREAD

**Issue by cgruver** [k8ssandra/k8ssandra-operator#693]
**K8ssandra Container Images built for arm64 architecture**

**Development on Apple Silicon, Production on ARM k8s compute nodes**

**Apple MacBook with M2 CPU**

I am preparing a blog post on Quarkus with Cassandra persistence through Stargate.  The post will include deploying the Cassandra cluster into OpenShift Local: [https://github.com/code-ready/crc](https://github.com/code-ready/crc).

This is working on my Intel based MacBook, but not on my M2 based MacBook.

This is perhaps not an urgent request.  But, as Apple silicon becomes more pervasive, and aarch64 is more widely used in the datacenter it will become a bigger gap.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1792) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1792
┆priority: Medium

**Comment by burmanm** [comment]
I think there was another ticket for this (could have been another repo). But basically, there's no GHA support for ARM64 yet, so we can't run CI for ARM64. That's the biggest blocker.

And none of us have ARM machines, so we can't test it or fix anything. That said, I could perhaps setup Oracle Linux instance to test manually with Ampere - but it doesn't solve the CI issue.

**Comment by cgruver** [comment]
Understood.

I just got a new MacBook Air M2...  so, playing with it a lot.  ;-)

It looks like someone has already attempted a build: [https://hub.docker.com/u/jmpalomar](https://hub.docker.com/u/jmpalomar)

I don't use images from an unknown source, but if I can find out who is building these images, I might collaborate.

**Comment by burmanm** [comment]
Building itself is no problem (golang x86 can compile ARM code) - but since we can't verify if it actually works, it's a bit problematic to release from our official sources.

But yes, you will need multiple repos replaced if doing it manually.

**Comment by cgruver** [comment]
Very true.

I'll set it aside for now, and maybe pick it up as a weekend project and a later blog post for folks on Apple silicon.

**Comment by cgruver** [comment]
FWIW, I have Stargate and Cassandra running on Apple silicon (M2) via the K8ssandra operator.  It was pretty easy.

[https://upstreamwithoutapaddle.com/blog%20post/quarkus%20series/2022/10/08/Quarkus-For-Architects-03.html](https://upstreamwithoutapaddle.com/blog%20post/quarkus%20series/2022/10/08/Quarkus-For-Architects-03.html)

Details on building the ARM64 images is here: [https://github.com/cgruver/k8ssandra-blog-resources](https://github.com/cgruver/k8ssandra-blog-resources) The documentation is WIP, but shows a developer how to build multi-arch manifests.

@burmanm   I made very minor changes to the Docker files in the k8ssandra-operator, and cass-operator projects which allows them to build ARM64 images if vars are set but still defaults to AMD64.  I'll submit those in a couple of PRs to see if you want to include that capability for dev purposes.

**Comment by mprimeaux** [comment]
Same issue for me on both M1 and M2 chips.

```yaml
│ Events:                                                                                                                                                    │
│   Type     Reason     Age   From               Message                                                                                                     │
│   ----     ------     ----  ----               -------                                                                                                     │
│   Normal   Scheduled  6s    default-scheduler  Successfully assigned k8ssandra/k8ssandra-operator-6db4b98db5-8hmwz to minikube                         │
│   Normal   Pulling    5s    kubelet            Pulling image "docker.io/k8ssandra/k8ssandra-operator:v1.5.2"                                               │
│   Warning  Failed     3s    kubelet            Failed to pull image "docker.io/k8ssandra/k8ssandra-operator:v1.5.2": rpc error: code = NotFound desc = fai │
│ led to pull and unpack image "docker.io/k8ssandra/k8ssandra-operator:v1.5.2": no match for platform in manifest: not found                                 │
│   Warning  Failed     3s    kubelet            Error: ErrImagePull                                                                                         │
│   Normal   BackOff    3s    kubelet            Back-off pulling image "docker.io/k8ssandra/k8ssandra-operator:v1.5.2"                                      │
│   Warning  Failed     3s    kubelet            Error: ImagePullBackOff
```

**Comment by michal-mazurkiewicz** [comment]
I have exactly same issue. Is there any workaround? (Trying to run single cluster locally following getting started docs with helm - [here](https://docs.k8ssandra.io/install/local/single-cluster-helm/))
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/29739339/223349465-7b7af525-c307-4720-9688-eb94fbc561d5.png">

I found the solution that when I pull this image directly from docker repo with flag `--platform linux/x86_64` I am able to get the image. But I don't know how to make helm install to use this flag. 

Please help.

**Comment by cgruver** [comment]
@michal-mazurkiewicz @mprimeaux   I have built images for running Cassandra and Stargate with the K8ssandra operator.  They are in my quay.io account.

This blog post will get you up and running Apple silicon: [https://upstreamwithoutapaddle.com/blog%20post/quarkus%20series/2022/10/08/Quarkus-For-Architects-03.html](https://upstreamwithoutapaddle.com/blog%20post/quarkus%20series/2022/10/08/Quarkus-For-Architects-03.html)

The images are a little dated, but I plan to update them soon.

**Comment by mprimeaux** [comment]
@cgruver Thanks much. I'll test but do hope this is resolved soon by the k8ssandra team.

**Comment by mprimeaux** [comment]
It does through Rosetta2 and while this can be enabled in Docker Desktop, we don't use Docker Desktop.  We use QEMU for our Minikube driver and so it uses the underlying CPU architecture; arm64. 

Even so, using Docker as the driver for Minikube, this still fails on the M2 as it requires a container image built as linux/arm64/v8. The M1 uses linux/arm64/v7. This is why you see the "no match for platform in manifest" exception above on the M2.

The request is to build for linux/arm64/v8 in addition to linux/arm64/v7. Here is a more precise exception:

```shell
Events:                                                                                                                                                                                 │
│   Type     Reason     Age                From               Message                                                                                                                     │
│   ----     ------     ----               ----               -------                                                                                                                     │
│   Normal   Scheduled  69s                default-scheduler  Successfully assigned sage-cassandra/k8ssandra-operator-7b789666ff-75xdk to minikube                                        │
│   Normal   BackOff    23s                kubelet            Back-off pulling image "docker.io/k8ssandra/k8ssandra-operator:v1.5.2"                                                      │
│   Warning  Failed     23s                kubelet            Error: ImagePullBackOff                                                                                                     │
│   Normal   Pulling    11s (x2 over 68s)  kubelet            Pulling image "docker.io/k8ssandra/k8ssandra-operator:v1.5.2"                                                               │
│   Warning  Failed     8s (x2 over 23s)   kubelet            Failed to pull image "docker.io/k8ssandra/k8ssandra-operator:v1.5.2": rpc error: code = Unknown desc = no matching manifest │
│  for linux/arm64/v8 in the manifest list entries                                                                                                                                        │
│   Warning  Failed     8s (x2 over 23s)   kubelet            Error: ErrImagePull    
```

**Comment by mprimeaux** [comment]
@burmanm Just as a follow up, the above failure is with Rosetta enabled in Docker Desktop as per the attached. The expected image is `linux/arm64/v8` on M2.

<img width="1263" alt="rosetta" src="https://user-images.githubusercontent.com/293512/224081050-abd47651-5e62-4953-ad83-e0721984ef9c.png">

**Comment by mprimeaux** [comment]
Does anyone know if the `linux/arm64` images were previously available? I ask because I am fairly certain I had the operator running before on `arm64` but I only see the [`linux/amd64` images on DockerHub](https://hub.docker.com/r/k8ssandra/k8ssandra-operator/tags).

**Comment by burmanm** [comment]
No, we've never published arm64 images for k8ssandra operators.

**Comment by mprimeaux** [comment]
Thanks for confirming, @burmanm.

**Comment by mprimeaux** [comment]
@burmanm How can we help to support ARM64? We’ve got quite a few software engineers block and, due to cost / performance reasons, prefer to run ARM in EKS node groups. Your help is greatly appreciated.

**Comment by santosh-d3vpl3x** [comment]
Could we use QEMU in GitHub actions to circumvent the limitation of GHA?

**Comment by mprimeaux** [comment]
> Could we use QEMU in GitHub actions to circumvent the limitation of GHA?

Yes. This is what we do for our multi-arch container images.

**Comment by adejanovski** [comment]
Hi, I agree we need to move forward with supporting arm64 architectures as for a couple years now all macbook pros ship with M chips. It's a pretty common laptop for developers, and running kind locally is always cheaper (and usually faster) than spinning up GKE/EKS clusters.

Wouldn't the use of QEMU make the CI runs last for much longer?
While ideally we'd want the upcoming arm64 builds to be tested in GHA, we can start without arm64 CI and evaluate our options there (could be CircleCI for example which has arm64 runners).

**Comment by mprimeaux** [comment]
A CI pipeline will take slightly longer to run since you're using at least two more GitHub Actions. 

IMPO, continuing to not support multi-arch images will further hinder adoption. We've had to include logic to fork based on the CPU architecture to satisfy different deployment options for local development and it is less than ideal. 

For public cloud providers (i.e. AWS Graviton3), ARM CPUs for EKS represent nearly a 40% cost per transaction savings for our workloads. So, supporting ARM64 does not only benefit local development.

Here is an *excerpt* from our GitHub Actions CI pipeline:

```yaml
  # Ref: https://github.com/manusa/actions-setup-minikube
  - name: Install Minikube
    uses: manusa/actions-setup-minikube@v2.7.2
    with:
      minikube version: 'v1.30.1'
      driver: docker
      container runtime: docker
      kubernetes version: ${{ matrix.k8s }}
      start args: "--addons registry --memory 2048 --cpus 2"
      github token: ${{ secrets.GITHUB_TOKEN }}

  - name: Install Dependencies
    run: |
      chmod o-r ~/.kube/config
      chmod g-r ~/.kube/config

      scripts/ci-deps.sh
      scripts/ci-deps-oci.sh

  # Ref: https://github.com/docker/setup-buildx-action
  # Ref: https://github.com/marketplace/actions/docker-setup-buildx
  - name: Install Moby BuildKit
    id: buildx
    uses: docker/setup-buildx-action@v2
    with:
      install: true

  - name: Display Moby BuildKit Context
    run: |
      echo "Name:      ${{ steps.buildx.outputs.name }}"
      echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
      echo "Status:    ${{ steps.buildx.outputs.status }}"
      echo "Flags:     ${{ steps.buildx.outputs.flags }}"
      echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
```

We use [nerdctl](https://github.com/containerd/nerdctl) with [tonistiigi/binfmt](https://github.com/containerd/nerdctl/blob/main/docs/multi-platform.md).  

`nerdctl` and other dependencies are installed in the "Install Dependencies" step. Here are excerpts from those two files.

<details>
  <summary>scripts/ci-deps.sh</summary>


```shell
sudo DEBIAN_FRONTEND=noninteractive apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common ca-certificates gnupg-agent curl build-essential make python3-pip golang-goprotobuf-dev protobuf-compiler
```

</details>

<details>
  <summary>scripts/ci-deps-oci.sh</summary>

```shell
sudo apt-get update

sudo DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common ca-certificates gnupg-agent curl build-essential make python3-pip golang-goprotobuf-dev protobuf-compiler
sudo apt-get update

# Install git
sudo add-apt-repository -y ppa:git-core/ppa
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y git jq

# Install nerdctl
# Ref: https://github.com/containerd/nerdctl/releases
__version="1.4.0"
curl -Lo ./nerdctl.tar.gz "https://github.com/containerd/nerdctl/releases/download/v${__version}/nerdctl-full-${__version}-linux-amd64.tar.gz"
sudo tar Cxzvvf /usr/local nerdctl.tar.gz
sudo cp /usr/local/lib/systemd/system/*.service /etc/systemd/system/
rm ./nerdctl.tar.gz

# Configure containerd and nerdctl as a non-root user.
# Ref: https://github.com/containerd/nerdctl/blob/master/docs/rootless.md
/usr/local/bin/containerd-rootless-setuptool.sh install
sudo loginctl enable-linger $(id -un)
systemctl --user restart containerd.service

# Configure BuildKit to run as non-root user.
/usr/local/bin/containerd-rootless-setuptool.sh install-buildkit
systemctl --user restart buildkit.service

# Ensure we enable the ability to build multi-architecture container images.
# Ref: https://github.com/containerd/nerdctl/blob/master/docs/multi-platform.md
sudo nerdctl run --privileged --rm tonistiigi/binfmt --install all
``` 

</details>

You can also use `docker buildx` to create your multi-arch manifest (and related container image layers) using the `--platform` arguments; e.g. `--platform="linux/arm64,linux/amd64"`. This generates a multi-arch manifest with container image layers for both `linux/arm64` and `linux/amd64'.

FWIW, layer size is critical so the above  is coupled with multi-stage container files, which is our case is `Containerfile` since we use `nerdctl`. 

In the end, we're keen to see a single OCI-compliant manifest that minimally supports `linux/amd64` and `linux/arm64' for purposes of local development and cost savings when running in any of the "big 3" cloud vendor's managed k8s environments.  The only `amd64`-based nodes in any of our EKS node groups are to support the k8ssandra-operator and, consequently, Apache Cassandra. We're currently working to move the Apache Cassandra node group to `arm64`. 

Let me know if I can provide any other details. Happy to help.

**Comment by adejanovski** [comment]
Hey folks, we now have multiarch images being pushed to our docker hub repository.
Successfully tested on Macbook pro M1/M2 laptops using Kind.
Let us know how it works for y'all.

![Capture d’écran 2023-07-03 à 17 15 36](https://github.com/k8ssandra/k8ssandra-operator/assets/5096002/c5f44354-cff4-4226-b022-65ce92cddaef)

**Comment by mprimeaux** [comment]
@adejanovski I finally had a chance today to test this out and all works as expected. Thanks much for your support with the operator.

On a related note, I'm using the k8ssandra-oerator Helm chart [v1.7.0](https://github.com/k8ssandra/k8ssandra-operator/tree/release/1.7/charts/k8ssandra-operator).  When I went to apply a `K8ssandraCluster` manifest, I ended up needing to override the `server-config-init` container (in the `initContainers` stanza since the `image` needed to refer to at least `datastax/cass-config-builder:1.7.0` and greater.  

Here's manifest we use for local development in Minikube.

<details>
<summary>manifest.yaml</summary>

 
```yaml
# Ref: https://docs-v2.k8ssandra.io/reference/crd/k8ssandra-operator-crds-latest/
# Ref: https://github.com/k8ssandra/k8ssandra-operator
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: cluster1
spec:
  cassandra:
    # Ref: https://hub.docker.com/r/k8ssandra/cass-management-api/tags
    serverVersion: "4.1.2"
    clusterName: cluster1

    # Sets whether multiple Cassandra instances can be scheduled on the same node.
    # This should normally be false to ensure cluster resilience but may be set true
    # for test/dev scenarios to minimise the number of nodes required.
    softPodAntiAffinity: true

    # Use superuserSecretName to setup superuser pre-defined credentials for the
    # database in a Kubernetes secret. Cass Operator will read the secret and pass
    # the values to the Management API when managing the cluster. If this is
    # empty, Cass Operator will generate a secret instead.
    superuserSecretRef:
      name: "cluster1-superuser"

    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 2500m

    datacenters:
      - metadata:
          name: dc1

        # The number of server nodes.
        size: 1

        initContainers:
          - name: server-config-init
            image: datastax/cass-config-builder:1.0.7
            resources:
              requests:
                cpu: 1000m
                memory: 1Gi
              limits:
                cpu: 1000m
                memory: 1Gi

        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi

        config:
          jvmOptions:
            heapSize: 512M
            gc: G1GC
            gc_g1_rset_updating_pause_time_percent: 5
            gc_g1_max_gc_pause_ms: 300
          cassandraYaml:
            authenticator: org.apache.cassandra.auth.PasswordAuthenticator
            authorizer: org.apache.cassandra.auth.CassandraAuthorizer
            role_manager: org.apache.cassandra.auth.CassandraRoleManager
            # Ref: https://github.com/apache/cassandra/blob/cassandra-4.1/NEWS.txt
            enable_sasi_indexes: true
            enable_materialized_views: true

```
