### ISSUE TITLE
K8SSAND-784 ⁃ Replication of system_auth is not updated when adding a datacenter

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#70]
Initially I created this K8ssandraCluster with one dc:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  k8sContextsSecret: k8s-contexts
  cassandra:
    cluster: test
    datacenters:
      - metadata:
          name: dc1
        k8sContext: kind-k8ssandra-0
        serverImage: emerkle826/cass-mgmtapi:3.11.11-v0.1.28
        size: 3
        serverVersion: "3.11.10"
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          cassandra-yaml:
            auto_snapshot: false
            memtable_flush_writers: 1
            commitlog_segment_size_in_mb: 2
            concurrent_compactors: 1
            compaction_throughput_mb_per_sec: 0
            sstable_preemptive_open_interval_in_mb: 0
            key_cache_size_in_mb: 0
            thrift_prepared_statements_cache_size_mb: 1
            prepared_statements_cache_size_mb: 1
            start_rpc: false
            slow_query_log_timeout_in_ms: 0
            counter_cache_size_in_mb: 0
            concurrent_reads: 2
            concurrent_writes: 2
            concurrent_counter_writes: 2
          jvm-options:
            initial_heap_size: "448m"
            max_heap_size: "448m"
        resources:
          limits:
             memory: 800Mi
        stargate:
          size: 1
          heapSize: 384Mi
          resources:
            limits:
              memory: 512Mi
          cassandraConfigMap:
            name: cassandra-config
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /checker/liveness
              port: health
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
```

After dc1 and Stargate became ready I added dc2 via `kubectl apply`:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  k8sContextsSecret: k8s-contexts
  cassandra:
    cluster: test
    datacenters:
      - metadata:
          name: dc1
        k8sContext: kind-k8ssandra-0
        serverImage: emerkle826/cass-mgmtapi:3.11.11-v0.1.28
        size: 3
        serverVersion: "3.11.10"
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          cassandra-yaml:
            auto_snapshot: false
            memtable_flush_writers: 1
            commitlog_segment_size_in_mb: 2
            concurrent_compactors: 1
            compaction_throughput_mb_per_sec: 0
            sstable_preemptive_open_interval_in_mb: 0
            key_cache_size_in_mb: 0
            thrift_prepared_statements_cache_size_mb: 1
            prepared_statements_cache_size_mb: 1
            start_rpc: false
            slow_query_log_timeout_in_ms: 0
            counter_cache_size_in_mb: 0
            concurrent_reads: 2
            concurrent_writes: 2
            concurrent_counter_writes: 2
          jvm-options:
            initial_heap_size: "448m"
            max_heap_size: "448m"
        resources:
          limits:
             memory: 800Mi
        stargate:
          size: 1
          heapSize: 384Mi
          resources:
            limits:
              memory: 512Mi
          cassandraConfigMap:
            name: cassandra-config
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /checker/liveness
              port: health
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      - metadata:
          name: dc2
        k8sContext: kind-k8ssandra-1
        serverImage: emerkle826/cass-mgmtapi:3.11.11-v0.1.28
        size: 3
        serverVersion: "3.11.10"
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          cassandra-yaml:
            auto_snapshot: false
            memtable_flush_writers: 1
            concurrent_compactors: 1
            commitlog_segment_size_in_mb: 2
            compaction_throughput_mb_per_sec: 0
            sstable_preemptive_open_interval_in_mb: 0
            start_rpc: false
            key_cache_size_in_mb: 0
            thrift_prepared_statements_cache_size_mb: 1
            prepared_statements_cache_size_mb: 1
            slow_query_log_timeout_in_ms: 0
            counter_cache_size_in_mb: 0
            concurrent_reads: 2
            concurrent_writes: 2
            concurrent_counter_writes: 2
          jvm-options:
            initial_heap_size: "448m"
            max_heap_size: "448m"
        resources:
          limits:
            memory: 800Mi
        stargate:
          size: 1
          heapSize: 384Mi
          cassandraConfigMap:
            name: cassandra-config
          resources:
            limits:
              memory: 512Mi
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /checker/liveness
              port: health
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
```

The replication for system_auth is not updated to include dc2.

We probably need #66 to fix this. Currently we configure the replication for system keyspaces by setting a couple system properties in the Cassandra pod:

```
-Dcassandra.system_distributed_replication_dc_names=<dc-names>
-Dcassandra.system_distributed_replication_per_dc=<replication-factor>
```

Unless there is a change to dc1, those system properties won't get updated. When the #66 is merged, we can check the status to see which DCs are already part of the cluster to determine whether the replication needs to be updated.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-784) by [Unito](https://www.unito.io)
┆Reviewer: 5fa4593062584c006b1e04d0
┆epic: Addition of new DataCenters
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-784
┆priority: Medium
