### ISSUE TITLE
K8SSAND-1815 ⁃ cass-operator kustomize resources in main should point to master in cass-operator

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#705]
**What happened?**
When the cass-operator dependency was upgraded to `v1.12.0` we wound up with:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/k8ssandra/cass-operator/config/deployments/cluster?ref=master


images:
  - name: k8ssandra/cass-operator
    newTag: v1.12.0
```

and

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/k8ssandra/cass-operator/config/deployments/default?ref=master

images:
  - name: k8ssandra/cass-operator
    newTag: v1.12.0

components:
  - ../../components/cass-operator-image-config
```

for cluster-scoped and namespace-scoped deployments of cass-operator respectively.

This could be problematic because we have pinned the cass-operator image version to v1.12.0, but we are getting the latest manifests from the cass-operator master branch. This could involve CRD or RBAC changes for example. 

**Did you expect to see something different?**
The ref and image tag should be kept in sync. In the main branch I think we should in general point to the latest of cass-operator. There may be situations where we want to pin to a specific version in which case both the ref and image tag should be updated to that version.

When preparing to release k8ssandra-operator, we should pin to a specific version of cass-operator. For example I opened #704 to upgrade to cass-operator v1.13.0.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* K8ssandra Operator version:

    `Insert image tag or Git SHA here`
    
    * Kubernetes version information:

    `kubectl version`
    * Kubernetes cluster kind:

```
insert how you created your cluster: kops, bootkube, etc.
```

* Manifests:

```
insert manifests relevant to the issue
```

* K8ssandra Operator Logs:

```
insert K8ssandra Operator logs relevant to the issue here
```

**Anything else we need to know?**:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1815) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1815
┆priority: Medium
