### ISSUE TITLE
Ability to override resources for default init-containers

### ISSUE THREAD

**Issue by K2017** [k8ssandra/k8ssandra-operator#723]
**What is missing?**
Ability to override resource limits and requests for CassandraDatacenter default initContainers.

**Why do we need it?**
Under certain conditions, cassandra datacenter pods do not start because the server-config-init container is configured with too little memory and crashes with a status of 137, i.e. OOMKilled.

**Environment**

* K8ssandra Operator version:

    `v1.3.0`
    
    
* K8s version:

   `v1.23.7`

**Anything else we need to know?**:
Relevant snippet of K8ssandraDatacenter resource definition:
```
  cassandra:
    serverVersion: "4.0.1"
    superuserSecretRef:
      name: [redacted]
    datacenters:
      - metadata:
          name: dc1
        size: 5
#        initContainers:
#          - name: server-config-init # defaults cannot be overridden ?
#            resources:
#              requests:
#                cpu: 1
#                memory: 1G
#              limits:
#                cpu: 1
#                memory: 1G
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 500Gi
        resources:
          requests:
            memory: 8G
          limits:
            memory: 24G
        telemetry:
          prometheus:
            enabled: true
```
In our environment, the server-config-init container is automatically configured with a memory limit of 256Mi and memory request of 256Mi. This does not seem to be enough for the config application to start correctly. We have found that 512Mi is sufficient in our case and would like to set this from the get-go instead of patching the statefulset post-deployment. Node resources are sufficient in every case.

**Comment by d-honeybadger** [comment]
+1

Seeing the same OOMKill. According to the [documentation][(https://docs-v2.k8ssandra.io/reference/crd/k8ssandra-operator-crds-latest/#k8ssandraclusterspeccassandradatacentersindex)
> K8ssandra-operator and cass-operator will create their own init-containers, which can be referenced here to control ordering or override specific settings such as mounts or resources request/limits for example. 

So, I was under the impression that this override should already be in place. Is it a case of incomplete doc or a bug?

**Comment by d-honeybadger** [comment]
> I'm wondering what makes it use more than that in your environments

It's on k3s instead of k8s, but other than that a basic 3-node cluster taken from an example for setting up monitoring:
```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: metrics-test
  namespace: k8ssandra-operator
spec:
  cassandra:
    serverVersion: "4.0.3"
    serverImage: k8ssandra/cass-management-api:4.0.3
    telemetry:
      prometheus:
        enabled: true
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    config:
      jvmOptions:
        heapSize: 2G
    datacenters:
      - metadata:
          name: dc1
        size: 3
    mgmtAPIHeap: 64Mi
  reaper:
    keyspace: reaper_db
    telemetry:
      prometheus:
        enabled: true
```
