### ISSUE TITLE
DataStax Management API fails to restart with "File name too long"

### ISSUE THREAD

**Issue by mieslep** [k8ssandra/k8ssandra-operator#734]
**What happened?**

When rolling out a new YAML, the 3rd (of 3) nodes got "stuck" in `cassandra.datastax.com/node-state=Starting`. Looking in `server-system-logger` was the following:

```
INFO  [main] 2022-10-20 07:53:08,901 CassandraDaemonInterceptor.java:62 - Starting DataStax Management API Agent for Apache Cassandra v0.1
INFO  [main] 2022-10-20 07:53:09,004 IPCController.java:130 - Starting Server
WARN  [main] 2022-10-20 07:53:09,007 CassandraDaemonInterceptor.java:101 - Problem starting DataStax Management API for Apache Cassandra
io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: File name too long
INFO  [main] 2022-10-20 07:53:09,007 CassandraDaemon.java:782 - Startup complete
```

Given that other nodes started cleanly, I deleted the pod and it restarted cleanly. 

I've not seen this happen with many restarts of this demo cluster, so imagine it will be hard to reproduce...but at the very least the issue / workaround might be noted here for posterity.

**Did you expect to see something different?**

Cluster should have started cleanly.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure it is easy to reproduce!

**Environment**

* K8ssandra Operator version:

    `docker.io/k8ssandra/k8ssandra-operator:v1.2.1`

* Kubernetes version information:
```
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.21.14
```

* Kubernetes cluster kind:

kind

* Manifests:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
spec:
  cassandra:
    tolerations:
    - key: "cassandraOnly"
      operator: "Exists"
      effect: "NoSchedule"
    serverVersion: "4.0.3"
    telemetry:
      prometheus:
        enabled: true
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    networking:
      hostNetwork: true
    mgmtAPIHeap: 64Mi
    superuserSecretRef:
      name: demo-superuser
    serverEncryptionStores:
      keystoreSecretRef:
        name: server-encryption-stores
      truststoreSecretRef:
        name: server-encryption-stores
    clientEncryptionStores:
      keystoreSecretRef:
        name: client-encryption-stores
      truststoreSecretRef:
        name: client-encryption-stores
    datacenters:
      - metadata:
          name: "dc1v2"
        config:
          jvmOptions:
            heapSize: 750Mi
            heapNewGenSize: 512Mi
            gc: CMS
          cassandraYaml:
            server_encryption_options:
               internode_encryption: all
               require_client_auth: true
               optional: true
               store_type: PKCS12
            client_encryption_options:
               enabled: true
               require_client_auth: true
               optional: true
               store_type: PKCS12
        num_tokens: 16
        racks:
        - name: zone1
          nodeAffinityLabels:
            topology.kubernetes.io/zone: "region1-zone1"
        - name: zone2
          nodeAffinityLabels:
            topology.kubernetes.io/zone: "region1-zone2"
        - name: zone3
          nodeAffinityLabels:
            topology.kubernetes.io/zone: "region1-zone3"
        size: 3
  medusa:
    cassandraUserSecretRef:
      name: demo-medusa
    certificatesSecretRef:
      name: medusa-client-certificate
    storageProperties:
      storageProvider: s3_compatible
      bucketName: k8ssandra-medusa
      host: minio.minio.svc.cluster.local
      port: 9000
      secure: false
      storageSecretRef:
        name: medusa-bucket-key
    containerResources:
      requests:
        cpu: 1000m
        memory: 2G
      limits:
        cpu: 1000m
        memory: 2G
  # reaper:
  #   heapSize: 1Gi
  #   keyspace: reaper_db
  #   cassandraUserSecretRef:
  #     name: demo-reaper
  #   jmxUserSecretRef:
  #     name: demo-reaper-jmx
  #   uiUserSecretRef:
  #     name: demo-reaper-ui
  #   telemetry:
  #     prometheus:
  #       enabled: true
```

* K8ssandra Operator Logs:

```
insert K8ssandra Operator logs relevant to the issue here
```

**Anything else we need to know?**:
