### ISSUE TITLE
K8SSAND-1859 ⁃ Apply DSE-specific authentication settings

### ISSUE THREAD

**Issue by olim7t** [k8ssandra/k8ssandra-operator#744]
Currently in `ApplyAuthSettings` if auth is enabled in the cluster, we apply default authentication options to `CassandraYaml`, if the user didn’t specify anything.

The options being applied are fine for Cassandra, but not for DSE.

This means that authentication needs to be configured explicitly for DSE clusters.

If nothing is specified, we should apply the following for DSE clusters:

CassandraYaml:
```
authenticator: com.datastax.bdp.cassandra.auth.DseAuthenticator
authorizer: com.datastax.bdp.cassandra.auth.DseAuthorizer
role_manager: com.datastax.bdp.cassandra.auth.DseRoleManager
```
DseYaml:
```
authentication_options:
  enabled: true
authorization_options:
  enabled: true
role_management_options:
  mode: internal
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1859) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1859
┆priority: Medium
