### ISSUE TITLE
Bad behaviour from Reaper's imageconfig

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#745]
**What happened?**

Reaper's imageconfig doesn't behave well. 

```
    containerImage:
      registry: ""
      repository: ""
      name: cassandra-reaper
      tag: incremental-test
```

The above block results in the operator trying to pull the image `docker.io/thelastpickle/cassandra-reaper:incremental-test` which clearly isn't the intention.

**Did you expect to see something different?**

Yes, the image should have been `docker.io/thelastpickle/cassandra-reaper:incremental-test`.
