### ISSUE TITLE
K8SSAND-583 ⁃ The inlined ObjectMeta field of CassandraDatacenterTemplateSpec is not serialized

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#8]
While working on #7 I ran into a problem where it seems that a field is not getting serialized. I have the following code:

```go
type K8ssandraClusterSpec struct {
	Cassandra *Cassandra `json:"cassandra,omitempty"`
}

type Cassandra struct {
	Datacenters []CassandraDatacenterTemplateSpec `json:"datacenters,omitempty"`
}

type CassandraDatacenterTemplateSpec struct {
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Name string `json:"name,omitempty"`

	Spec cassdcv1beta1.CassandraDatacenterSpec `json:"spec,omitempty"`
}
```

The `ObjectMeta` field in `CassandraDatacenterTemplateSpec` does not get serialized when I create a K8ssandraCluster object. Here is an manifest I used for testing:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  cassandra:
    datacenters:
    - metadata:
        name: dc1
        labels:
          env: dev
      spec:
        size: 1
        serverType: "cassandra"
        serverVersion: "3.11.10"
        clusterName: test
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
```

The `metadata` property in the `datacenters` array is empty after I create the object. I came across an old issue that could be relevant https://github.com/kubernetes/client-go/issues/8.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-583) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-583
┆Priority: Medium
