### ISSUE TITLE
CassandraDatacenter updates fail due to resource version conflicts

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#80]
While doing some manual testing I observed errors in the operator log when k8ssandra-operator was attempting to update CassandraDatacenters.

Here is the manifest for my K8ssandraCluster:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  cassandra:
    cluster: test
    datacenters:
      - metadata:
          name: dc1
        k8sContext: jsanda-1
        size: 3
        serverVersion: "3.11.10"
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvm-options:
            initial_heap_size: "1024m"
            max_heap_size: "1024m"
        resources:
          limits:
             memory: 2048Mi
        stargate:
          size: 1
          heapSize: 512Mi
          resources:
            limits:
              memory: 1024Mi
      - metadata:
          name: dc2
        k8sContext: jsanda-2
        size: 3
        serverVersion: "3.11.10"
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvm-options:
            initial_heap_size: "1024m"
            max_heap_size: "1024m"
        resources:
          limits:
            memory: 2048Mi
        stargate:
          size: 1
          heapSize: 512Mi
          resources:
            limits:
              memory: 1024Mi
      - metadata:
          name: dc3
        k8sContext: jsanda-3
        size: 3
        serverVersion: "3.11.10"
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvm-options:
            initial_heap_size: "1024m"
            max_heap_size: "1024m"
        resources:
          limits:
            memory: 2048Mi
        stargate:
          size: 1
          heapSize: 512Mi
          resources:
            limits:
              memory: 512Mi      
```

The errors look like this:

```
2021-08-12T21:38:33.668Z        ERROR   controller-runtime.manager.controller.k8ssandracluster  Failed to update datacenter 
 {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "test", "namespace": "default", 
"CassandraDatacenter": {"namespace": "default", "name": "dc2"}, "error": "Operation cannot be fulfilled on
cassandradatacenters.cassandra.datastax.com \"dc2\": the object has been modified; please apply your changes to the latest
version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
github.com/k8ssandra/k8ssandra-operator/controllers.(*K8ssandraClusterReconciler).reconcile
        /workspace/controllers/k8ssandracluster_controller.go:137
github.com/k8ssandra/k8ssandra-operator/controllers.(*K8ssandraClusterReconciler).Reconcile
        /workspace/controllers/k8ssandracluster_controller.go:76
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216
```

I made no update to the K8ssandraCluster spec but had lots of errors like this in the log.

While a resource version conflict is often perfectly normal, I think this deserves some investigation. We perform an update when the hash of the desired spec does not match the spec of the actual spec. The only update that the operator performs right now on its own without changes to the K8ssandraCluster spec is to update `AdditionalSeeds`.

We compute the hash after the computing the remote seeds endpoints. That should be excluded from computing the resource hash as it won't trigger a StatefulSet update.

Lastly, we should think about adding some retry logic since we have both k8ssandra-operator and cass-operator updating the CassandraDatacenter. The former updates the spec and metadata while the latter update the status.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-795) by [Unito](https://www.unito.io)
┆Fix Versions: k8ssandra-2.0.0-alpha
┆Issue Number: K8SSAND-795
┆Priority: Medium
