### ISSUE TITLE
commonLabels missing from ServiceMonitors

### ISSUE THREAD

**Issue by elchenberg** [k8ssandra/k8ssandra-operator#803]
I am not sure if this is a support question or a bug report because this is the first time I tried to set up the k8ssandra-operator.

**What did you do?**

I deployed the k8ssandra-operator v1.4.0 using the Helm chart k8ssandra/k8ssandra-operator v0.37.4.

Then I deployed a K8ssandraCluster in the same namespace.

The StatefulSet k8ssandra-dc1-default-sts got created and when it was rolled out the ServiceMonitor k8ssandra-dc1-cass-servicemonitor was created.

**Did you expect to see some different?**

I expected to see the label `release: kube-prometheus-stack` on the ServiceMonitor but it was missing:

```yaml
  labels:
    app.kubernetes.io/component: telemetry
    app.kubernetes.io/created-by: k8ssandracluster-controller
    app.kubernetes.io/managed-by: k8ssandra-operator
    app.kubernetes.io/part-of: k8ssandra
    k8ssandra.io/cluster-name: k8ssandra
    k8ssandra.io/cluster-namespace: cassandra
    k8ssandra.io/datacenter: dc1
```

Am I doing something wrong? Am I missing something?

**Environment**

* K8ssandra Operator version:

```
docker.io/k8ssandra/k8ssandra-operator:v1.4.0
```

* Kubernetes version information:

```
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.25.2
```

* Kubernetes cluster kind:

```
kind v0.16.0 go1.19.1 linux/amd64
```

* Manifests:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: k8ssandra
spec:
  auth: false
  cassandra:
    datacenters:
      - metadata:
          name: dc1
        size: 1
        storageConfig:
          cassandraDataVolumeClaimSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        telemetry:
          prometheus:
            commonLabels:
              release: kube-prometheus-stack
            enabled: true
    serverVersion: "4.0.7"
```

* K8ssandra Operator Logs:

```
2022-12-22T17:50:04.788Z	INFO	checking whether Prometheus ServiceMonitor for Cassandra already exists	{"controller": "k8ssandracluster", "controllerGroup": "k8ssandra.io", "controllerKind": "K8ssandraCluster", "k8ssandraCluster": {"name":"k8ssandra","namespace":"cassandra"}, "namespace": "cassandra", "name": "k8ssandra", "reconcileID": "415f31a3-3f99-4332-9b3e-bad8fc21bdd6", "K8ssandraCluster": "cassandra/k8ssandra", "CassandraDatacenter": "cassandra/dc1"}
2022-12-22T17:50:04.889Z	INFO	Prometheus ServiceMonitor for Cassandra not found, creating	{"controller": "k8ssandracluster", "controllerGroup": "k8ssandra.io", "controllerKind": "K8ssandraCluster", "k8ssandraCluster": {"name":"k8ssandra","namespace":"cassandra"}, "namespace": "cassandra", "name": "k8ssandra", "reconcileID": "415f31a3-3f99-4332-9b3e-bad8fc21bdd6", "K8ssandraCluster": "cassandra/k8ssandra", "CassandraDatacenter": "cassandra/dc1"}
```

**Anything else we need to know?**:

I tried v0.38.4 of the Helm chart (operator v1.3.0) and v0.37.4 (operator v1.1.1) but this did not help
