### ISSUE TITLE
Operator is not resilient to missing spec.cassandra.serverVersion

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#809]
**What happened?**

The operator is not resilient to cases where the `spec.cassandra.serverVersion` is `nil`. 

**Did you expect to see something different?**

Even malformed CRs should not cause crashes. This could lead to a DOS issue in multi-tenant clusters.

**How to reproduce it (as minimally and precisely as possible)**:

When creating a `K8ssandraCluster`, it appears that I can crash the operator by submitting the following CR:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
  namespace: k8ssandra-operator
spec:
  cassandra:
    datacenters:
      - metadata:
          name: dc1
        size: 1
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 384Mi
```
