### ISSUE TITLE
Adding\remove cassandra DC

### ISSUE THREAD

**Issue by telepuz** [k8ssandra/k8ssandra-operator#902]
## Bug Report
**Describe the bug**

Hello!
I have got errors, when I try to add new cassandra DC
- [Cassandra error](https://github.com/apache/cassandra/blob/9860c1e9d9fb45342fa674782ecd135cf6875943/src/java/org/apache/cassandra/locator/NetworkTopologyStrategy.java#L324)

I found the [ticket](https://issues.apache.org/jira/browse/CASSANDRA-17478) in Cassadra Jira with new improvement

**How To Reproduce**
1. Go to [instruction](https://github.com/k8ssandra/k8ssandra-operator/blob/v1.4.1/docs/add-dc.md)
2. Add the manifest of the new cassandra DC
3. Add annotations `k8ssandra.io/dc-replication`
4. Get an errors in system.log
```
INFO  [epollEventLoopGroup-5-3] 2023-02-27 06:12:09,202 RpcExecutionException.java:39 - Failed to execute method NodeOps.createRole
org.apache.cassandra.exceptions.UnavailableException: Cannot achieve consistency level LOCAL_QUORUM
```
5. Addition new DC loops with the same errors
6. Change `cassandraYaml`  in the new DC
```
auth_read_consistency_level: ONE
auth_write_consistency_level: ONE
```
7. DC added successfully

Remove DC
1. Remove manifest of the old DC
2. Get errors in k8ssandra-operator: 
```
"keyspace": "system_auth", "error": "CALL alter keyspaces system_auth failed on all datacenter cass-dc pods"
```
3. Get errors in system.log
```
INFO  [epollEventLoopGroup-5-3] 2023-02-27 06:57:10,359 RpcExecutionException.java:39 - Failed to execute method NodeOps.alterKeyspace
org.apache.cassandra.exceptions.ConfigurationException: Following datacenters have active nodes and must be present in replication options for keyspace system_auth: [cass-dc]
```
4. Removing old DC loops with the same errors

If I try to decommission\\remove old node manually, DC removes successfully

**Expected behavior**
1. Add new manifest
2. Waiting...
3. Get\\Remove cassandra DC

**Environment:**

* Helm charts version info
	* Don't use helm
* Kubernetes version information:
	* v1.22.6
- Additional
	- Cassandra version: 4.1.0
	- K8ssandra operator version: 1.4.1

**Comment by Telepuz** [comment]
Ok. Thanks you
I will test new version

**Comment by Telepuz** [comment]
Hello
I upgraded operator to 1.5.2. I have same trouble with additional DC

**Comment by adejanovski** [comment]
Hi @Telepuz,

I was able to add a DC using k8ssandra-operator v1.5.2 and v1.6.1.
I deployed k8ssandra-operator with cluster scope and created a single DC cluster with the following manifest:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
  namespace: k8ssandra-operator
spec:
  cassandra:
    serverVersion: 4.1.0
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 512Mi
    datacenters:
      - metadata:
          name: dc1
        size: 2
```

Once the first DC was up and running, I created a `ks1` keyspace through cqlsh and then created another DC in a different namespace:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
  namespace: k8ssandra-operator
  annotations:
    k8ssandra.io/dc-replication: '{"dc2": {"ks1": 2}}'
spec:
  cassandra:
    serverVersion: 4.1.0
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 512Mi
    datacenters:
      - metadata:
          name: dc1
        size: 2
      - metadata:
          name: dc2
          namespace: dc2
        k8sContext: 
        size: 2
```

All pods started correctly:

```
% kubectl get pods -A | grep '\-sts\-'
dc2                  test-dc2-default-sts-0                              2/2     Running   0          4m49s
dc2                  test-dc2-default-sts-1                              2/2     Running   0          4m49s
k8ssandra-operator   test-dc1-default-sts-0                              2/2     Running   0          13m
k8ssandra-operator   test-dc1-default-sts-1                              2/2     Running   0          13m
```

In the process I identified [a bug](https://github.com/k8ssandra/k8ssandra-operator/issues/973) for which I pushed [a PR](https://github.com/k8ssandra/k8ssandra-operator/pull/974) with a fix. That bug doesn't seem to be what's affecting you though.

Could you detail your procedure step by step so that we can investigate why it's not working for you?
Thanks
