### ISSUE TITLE
Prometheus scrape: Connection refused

### ISSUE THREAD

**Issue by jpicara** [k8ssandra/k8ssandra-operator#929]
**What did you do?**
I deployed K8ssandraCluster in a minikube environment where kube-prometheus-stack was already deployed. Target is to scrape the metrics over https://docs.k8ssandra.io/tasks/monitor/prometheus-grafana/#filtering-metrics-with-the-new-metrics-endpoint-from-v150. However I got the connection refused as below:

`Get "http://172.17.0.9:9000/metrics": dial tcp 172.17.0.9:9000: connect: connection refused`

**Did you expect to see some different?**
No scrape errors being able to receive the K8ssandra metrics to Prometheus

**Environment**

* K8ssandra Operator version:

    `docker.io/k8ssandra/k8ssandra-operator:v1.5.0`
     
    

* Kubernetes version information:

```
clientVersion:
  buildDate: "2020-08-13T16:12:48Z"
  compiler: gc
  gitCommit: 9f2892aab98fe339f3bd70e3c470144299398ace
  gitTreeState: clean
  gitVersion: v1.18.8
  goVersion: go1.13.15
  major: "1"
  minor: "18"
  platform: linux/amd64
serverVersion:
  buildDate: "2022-01-25T21:19:12Z"
  compiler: gc
  gitCommit: 816c97ab8cff8a1c72eccca1026f7820e93e0d25
  gitTreeState: clean
  gitVersion: v1.23.3
  goVersion: go1.17.6
  major: "1"
  minor: "23"
  platform: linux/amd64
```

* Kubernetes cluster kind:

    minikube

* Manifests:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata: 
  annotations:
    k8ssandra.io/initial-system-replication: '{"dc1":1}'
    meta.helm.sh/release-name: kasope-platform
    meta.helm.sh/release-namespace: platform
  creationTimestamp: '2023-03-27T11:58:53Z'
  finalizers:
    - k8ssandracluster.k8ssandra.io/finalizer
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  auth: true
  cassandra:
    config:
      cassandraYaml:
        num_tokens: 8
      jvmOptions:
        gc: G1GC
        heapSize: 1Gi
    datacenters:
      - jmxInitContainerImage:
          name: busybox
          registry: docker.io
          tag: 1.34.1
        metadata:
          name: dc1
          services:
            allPodsService:
              annotations:
                consul.hashicorp.com/service-port: native
            dcService:
              annotations:
                consul.hashicorp.com/service-port: native
        perNodeConfigInitContainerImage: mikefarah/yq:4
        size: 1
        stopped: false
    jmxInitContainerImage:
      name: busybox
      registry: docker.io
      tag: 1.34.1
    perNodeConfigInitContainerImage: mikefarah/yq:4
    resources:
      requests:
        memory: 2Gi
    serverType: cassandra
    serverVersion: 3.11.11
    storageConfig:
      cassandraDataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    superuserSecretRef:
      name: cluster-superuser
    telemetry:
      mcac:
        enabled: false
      prometheus:
        commonLabels:
          release: monitoring-platform
        enabled: true
  reaper: 
    ServiceAccountName: default
    autoScheduling:
      enabled: true
      initialDelayPeriod: PT15S
      percentUnrepairedThreshold: 10
      periodBetweenPolls: PT10M
      repairType: AUTO
      scheduleSpreadPeriod: PT6H
      timeBeforeFirstSchedule: PT5M
    containerImage:
      name: cassandra-reaper
      registry: docker.io
      repository: thelastpickle
      tag: 3.2.1
    deploymentMode: PER_DC
    heapSize: 2Gi
    initContainerImage:
      name: cassandra-reaper
      registry: docker.io
      repository: thelastpickle
      tag: 3.2.1
    keyspace: reaper_db
    secretsProvider: internal
  secretsProvider: internal
```

So the relevant part:
```
    telemetry:
      mcac:
        enabled: false
      prometheus:
        commonLabels:
          release: monitoring-platform
        enabled: true
```
* K8ssandra Operator Logs:

No log output to point where the issue is.

**Anything else we need to know?**:

Automatically Servicemonitor created:
```

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    k8ssandra.io/resource-hash: QBE3Hqk8zb8XFEOHl9lpnWDplf3YpRVG47nV09xy5Dw=
  creationTimestamp: '2023-03-27T12:06:48Z'
  generation: 1
  labels:
    app.kubernetes.io/component: telemetry
    app.kubernetes.io/created-by: k8ssandracluster-controller
    app.kubernetes.io/managed-by: k8ssandra-operator
    app.kubernetes.io/part-of: k8ssandra
    k8ssandra.io/cluster-name: cluster
    k8ssandra.io/cluster-namespace: platform
    k8ssandra.io/datacenter: dc1
    release: monitoring-platform
  managedFields:
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:k8ssandra.io/resource-hash: {}
          f:labels: 
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/created-by: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/part-of: {}
            f:k8ssandra.io/cluster-name: {}
            f:k8ssandra.io/cluster-namespace: {}
            f:k8ssandra.io/datacenter: {}
            f:release: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"6968cea7-98b9-4df0-b883-eb0a2f26d601"}: {}
        f:spec:
          .: {}
          f:endpoints: {}
          f:namespaceSelector:
            .: {}
            f:matchNames: {}
          f:selector: {}
          f:targetLabels: {}
      manager: manager
      operation: Update
      time: '2023-03-27T12:06:48Z'
  name: cluster-dc1-cass-servicemonitor
  namespace: platform
  ownerReferences:
    - apiVersion: cassandra.datastax.com/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: CassandraDatacenter
      name: dc1
      uid: 6968cea7-98b9-4df0-b883-eb0a2f26d601
  resourceVersion: '2484'
  uid: 8b04ff14-adb4-4084-b3ea-6ddb3458f20d
  selfLink: >-
    /apis/monitoring.coreos.com/v1/namespaces/platform/servicemonitors/cluster-dc1-cass-servicemonitor
spec:
  endpoints:
    - bearerTokenSecret:
        key: ''
      interval: 15s
      path: /metrics
      port: metrics
      scheme: http
      scrapeTimeout: 15s
  namespaceSelector:
    matchNames:
      - platform
  selector:
    matchExpressions: 
      - key: cassandra.datastax.com/cluster
        operator: In
        values: 
          - cluster
      - key: cassandra.datastax.com/datacenter
        operator: In
        values:
          - dc1
    matchLabels:
      app.kubernetes.io/managed-by: cass-operator
      cassandra.datastax.com/prom-metrics: 'true'
  targetLabels:
    - cassandra.datastax.com/cluster
    - cassandra.datastax.com/datacenter
```

**Comment by jpicara** [comment]
Hi,
Alright, thanks for your quick response. So then, it is clear that using MCAC or upgrade the Cassandra version. Probably it was a misunderstand cause in the documentation it only points to version 1.5 https://docs.k8ssandra.io/tasks/monitor/prometheus-grafana/#filtering-metrics-with-the-new-metrics-endpoint-from-v150 which I already have.
![image](https://user-images.githubusercontent.com/6992066/227952478-6131b85b-c0af-47df-84e6-16672c51b78a.png)

**Comment by jpicara** [comment]
Hi @adejanovski 
I tested this out by upgrading to the 3.11.13 `app.kubernetes.io/version=3.11.13` 
```
            telemetry:
              prometheus:
                enabled: true
                commonLabels:
                  release: monitoring-platform
              mcac:
                enabled: false
```
and Prometheus job can scrape the metrics coming from Cassandra.
```
 kubectl --namespace platform exec pod/cluster-dc1-default-sts-0 --container cassandra -- curl -IsS http://localhost:9000/metrics
HTTP/1.1 200 OK
Content-Type: text/plain; version=0.0.4; charset=utf-8
Content-Length: 7535536
Connection: keep-alive
```

Thanks for the support.
BR

**Comment by jpicara** [comment]
HI @adejanovski ,
As my previous comment, I finally was able to updagre de server version to 3.11.13 and metrics start coming to Prometheus thanks to the cass-servicemonitor created automatically. However, metrics look like:

`org_apache_cassandra_.*`

I have checked the way to relabel all the metrics to make them compatible with the default cassandra dashboards and jumped into this ticket: https://github.com/k8ssandra/management-api-for-apache-cassandra/issues/255
However, I tried to make it directly over the serviceMonitor on this way, just the first Request type and consistency levels extraction:

`spec:
  endpoints:
    - regex: org\.apache\.cassandra\.metrics\.client_request\.(\w+)\.(\w+)$
      replacement: ${2}
      sourceLabels:
        - mcac
      targetLabel: request_type
    - regex: org\.apache\.cassandra\.metrics\.client_request\.(\w+)\.(\w+)$
      replacement: org_apache_cassandra_metrics_client_request_${1}
      sourceLabels:
        - mcac
      targetLabel: __name__
    - regex: org\.apache\.cassandra\.metrics\.client_request\.(\w+)\.(\w+)\.(\w+)$
      replacement: ${3}
      sourceLabels:
        - mcac
      targetLabel: cl
    - regex: org\.apache\.cassandra\.metrics\.client_request\.(\w+)\.(\w+)\.(\w+)$
      replacement: ${2}
      sourceLabels:
        - mcac
      targetLabel: request_type
    - regex: >-
       org\.apache\.cassandra\.metrics\.client_request\.(\w+)\.(\w+)\.(\w+)$
      replacement: org_apache_cassandra_metrics_client_request_${1}_cl
      sourceLabels:
        - mcac
      targetLabel: __name__
    - bearerTokenSecret:
        key: ''
      interval: 15s
      path: /metrics
      port: metrics
      scheme: http
      scrapeTimeout: 15s
  namespaceSelector:
    matchNames:
      - platform
  selector:
    matchExpressions:
      - key: cassandra.datastax.com/cluster
        operator: In
        values:
          - cluster
      - key: cassandra.datastax.com/datacenter
        operator: In
        values:
          - dc1
    matchLabels:
      app.kubernetes.io/managed-by: cass-operator
      cassandra.datastax.com/prom-metrics: 'true'
  targetLabels:
    - cassandra.datastax.com/cluster
    - cassandra.datastax.com/datacenter`

And after save it, it is totally a mess. 

`spec:
  endpoints:
    - {}
    - {}
    - {}
    - {}
    - {}
    - bearerTokenSecret:
        key: ''
      interval: 15s
      path: /metrics
      port: metrics
      scheme: http
      scrapeTimeout: 15s
  namespaceSelector:
    matchNames:
      - platform
  selector:
    matchExpressions:
      - key: cassandra.datastax.com/cluster
        operator: In
        values:
          - cluster
      - key: cassandra.datastax.com/datacenter
        operator: In
        values:
          - dc1
    matchLabels:
      app.kubernetes.io/managed-by: cass-operator
      cassandra.datastax.com/prom-metrics: 'true'
  targetLabels:
    - cassandra.datastax.com/cluster
    - cassandra.datastax.com/datacenter`
    
 Could you please specify where we should include this relabelling part? It would be nice if this relabelling could be added somewhere over here:
 `            telemetry:
              prometheus:
                enabled: true
                commonLabels:
                  release: monitoring-platform
              mcac:
                enabled: false`

Thanks!!

**Comment by adejanovski** [comment]
@jpicara, I don't recommend doing this.
Instead you can use the updated dashboards from [this PR](https://github.com/k8ssandra/k8ssandra-operator/pull/936).

**Comment by jpicara** [comment]
Hi @adejanovski ,
Thanks for the response. I took the dashboards and they are working like a hell. However I would raise to following scenario where all the cassandra metrics are filling our Prometheus database. We have around 520 tables.
![image](https://user-images.githubusercontent.com/6992066/231434573-ab00ac53-e24b-4d03-913a-1a8ae65eedaa.png)
It means we are consuming around 30GB per day storing these metrics.
![image](https://user-images.githubusercontent.com/6992066/231435793-65504523-2d6a-4c7d-96ce-69db744e29ac.png)
Taking one sample I see hundreds of metrics with le (less or equal) per table
`org_apache_cassandra_metrics_table_cas_prepare_latency_bucket{cassandra_datastax_com_cluster="cluster", cassandra_datastax_com_datacenter="dc1", cluster="cluster", container="cassandra", datacenter="dc1", endpoint="metrics", exported_instance="X.X.X.X", host="65367fad-8b9e-4d89-ba7b-XXXXXX", instance="X.X.X.X:9000", job="cluster-dc1-all-pods-service", keyspace="bi_export", le="2759", namespace="platform", pod="cluster-dc1-default-sts-2", pod_name="cluster-dc1-default-sts-2", rack="default", service="cluster-dc1-all-pods-service", table="history"}`
Plus also quite many metrics for every single quantile. I would like to know if this is the expected behaviour.

With the mcac approach we could just modify the mcacmetricsfilters to allow or deny the metrics we want. Right now with the metric endpoint approach, Service Monitor is automatically created without (at least I cannot find anything) any way to perform some relabelling or even to drop the metrics for example coming with the name: `org.apache.cassandra.metrics.Table`

This is the automatically Serivce Monitor created:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    k8ssandra.io/resource-hash: QBE3Hqk8zb8XFEOHl9lpnWDplf3YpRVG47nV09xy5Dw=
  creationTimestamp: '2023-01-20T12:42:59Z'
  generation: 13
  labels:
    app.kubernetes.io/component: telemetry
    app.kubernetes.io/created-by: k8ssandracluster-controller
    app.kubernetes.io/managed-by: k8ssandra-operator
    app.kubernetes.io/part-of: k8ssandra
    k8ssandra.io/cluster-name: cluster
    k8ssandra.io/cluster-namespace: platform
    k8ssandra.io/datacenter: dc1
    release: monitoring-platform
  managedFields:
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:k8ssandra.io/resource-hash: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/created-by: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/part-of: {}
            f:k8ssandra.io/cluster-name: {}
            f:k8ssandra.io/cluster-namespace: {}
            f:k8ssandra.io/datacenter: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"84e1261a-8985-481d-bfd5-53e54fdd9475"}: {}
        f:spec:
          .: {}
          f:namespaceSelector:
            .: {}
            f:matchNames: {}
          f:selector: {}
          f:targetLabels: {}
      manager: manager
      operation: Update
      time: '2023-01-20T12:42:59Z'
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:release: {}
        f:spec:
          f:endpoints: {}
      manager: node-fetch
      operation: Update
      time: '2023-03-30T12:14:08Z'
  name: cluster-dc1-cass-servicemonitor
  namespace: platform
  ownerReferences:
    - apiVersion: cassandra.datastax.com/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: CassandraDatacenter
      name: dc1
      uid: 84e1261a-8985-481d-bfd5-53e54fdd9475
  resourceVersion: '51258098'
  uid: b5e08a8f-c1ae-42c7-963d-3b8d39daeef1
  selfLink: >-
    /apis/monitoring.coreos.com/v1/namespaces/platform/servicemonitors/cluster-dc1-cass-servicemonitor
spec:
  endpoints:
    - bearerTokenSecret:
        key: ''
      interval: 15s
      path: /metrics
      port: metrics
      scheme: http
      scrapeTimeout: 15s
  namespaceSelector:
    matchNames:
      - platform
  selector:
    matchExpressions:
      - key: cassandra.datastax.com/cluster
        operator: In
        values:
          - cluster
      - key: cassandra.datastax.com/datacenter
        operator: In
        values:
          - dc1
    matchLabels:
      app.kubernetes.io/managed-by: cass-operator
      cassandra.datastax.com/prom-metrics: 'true'
  targetLabels:
    - cassandra.datastax.com/cluster
    - cassandra.datastax.com/datacenter

```

Probably, I am missing something here. Otherwise this approach fills our Prometheus database. Could you please clarify or guide us on how to move forward with it?
Thanks in advance!

**Comment by adejanovski** [comment]
Hi, 

you can define relabeling rules that will be applied in the metrics endpoint directly and allow you to filter out metrics that you do not want to scrape. Check the `.spec.cassandra.telemetry.cassandra.relabels[index]` field in the CRD [here](https://docs.k8ssandra.io/reference/crd/releases/k8ssandra-operator-releases/k8ssandra-operator-crds-1.6/#k8ssandraclusterspeccassandratelemetrycassandrarelabelsindex).
We should probably document this...

**Comment by jpicara** [comment]
Hello,
Yes, probably document it could help other people to make it working as this is a quite new feature. I am trying to do it, and for sure I almost get it, but not for now. This is how I am trying to drop for example the following metric: `org_apache_cassandra_metrics_table_view_lock_acquire_time_bucket`

```
      cluster:
        enabled: true
        spec:
          cassandra:
            serverVersion: "3.11.13"
            config:
              cassandraYaml:
                num_tokens: 8
              jvmOptions:
                heapSize: 1Gi
            storageConfig:
              cassandraDataVolumeClaimSpec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi
            resources:
              requests:
                memory: 2Gi
            datacenters:
              - metadata:
                  name: dc1
                  services:
                    dcService:
                      annotations:
                        consul.hashicorp.com/service-port: native
                    allPodsService:
                      annotations:
                        consul.hashicorp.com/service-port: native
                size: 1
            telemetry:
              cassandra:
                relabels:
                  - action: drop
                    regex: org_apache_cassandra_metrics_table_view_lock_acquire_time_bucket
                    sourceLabels:
                      - __name__
              prometheus:
                enabled: true
                commonLabels:
                  release: monitoring-platform

```

However, it seems it does not have any effect inside the K8ssandraCluster and so that in the ServiceMonitor.

**Comment by jpicara** [comment]
Hi,
Btw, I am using the `docker.io/k8ssandra/k8ssandra-operator:v1.5.0` and it seems that you were pointing to a CRD released in the 1.6 operator version: https://docs.k8ssandra.io/reference/crd/releases/k8ssandra-operator-releases/k8ssandra-operator-crds-1.6/#k8ssandraclusterspeccassandratelemetrycassandrarelabelsindex, so this could be probably the issue at all, isnt it?
BR

**Comment by adejanovski** [comment]
Also make sure that you're running the last version for your Cassandra image (should be [this one](https://hub.docker.com/layers/k8ssandra/cass-management-api/3.11.13-v0.1.59/images/sha256-d3620b2227d98055d63ea354d000a9d8f6ffb1d91e8404508e749629f39e898e?context=explore) at least).

**Comment by jpicara** [comment]
Hi,
Thanks for confirming it. Indeed I was able to manage the upgrade and now we are running the needed versions.
I deployed it again and had the apply also this fix https://github.com/k8ssandra/k8ssandra-operator/issues/925 for the endpoint address.
So the specific code for this dropping metrics is most likely:
```
telemetry:
  cassandra:
    endpoint:
      address: "0.0.0.0"
    relabels:
    - action: drop
      regex: org_apache_cassandra_metrics_table_view_lock_acquire_time_bucket
      sourceLabels:
        - __name__
  prometheus:
    enabled: true
    commonLabels:
      release: monitoring-platform
    mcac:
      enabled: false
```
Then, Prometheus job is created automatically as per the ServiceMonitor.
![image](https://user-images.githubusercontent.com/6992066/233092564-e41246d5-a419-4bd2-9f54-a00ac1446285.png)
And yes, it modified the k8ssandraCluster CRD:
![image](https://user-images.githubusercontent.com/6992066/233094226-b2a3442e-c8c4-4d3d-9eca-75fab61fdb43.png)
However, these changes have not been applied to the ServiceMonitor and I still see the metric in Prometheus.
![image](https://user-images.githubusercontent.com/6992066/233094557-d72f4905-9721-4726-b7fe-a75b37e933b7.png)
Do you know what it is missing?
Thanks in advance for the support.

**Comment by burmanm** [comment]
Quickly looking, the metric you want to drop is: `org_apache_cassandra_metrics_table_view_lock_acquire_time`, the `_bucket` postfix is an indication to Prometheus that this is a Histogram.

**Comment by jpicara** [comment]
Hi,
Thanks for your response. However, I tried what you have proposed and Prometheus still scrapes the metric.

```
telemetry:
  cassandra:
    endpoint:
      address: "0.0.0.0"
    relabels:
    - action: drop
      regex: 'org_apache_cassandra_metrics_table_view_lock_acquire_time'
      sourceLabels:
        - __name__
```

Indeed I also test different metrics like the following one, but still can see the metric in Prometheus.
```
telemetry:
  cassandra:
    endpoint:
      address: "0.0.0.0"
    relabels:
    - action: drop
      regex: 'org_apache_cassandra_metrics_cache_capacity'
      sourceLabels:
        - __name__
```
So for sure I am doing something wrong even though I tested this out bunch of times.

**Comment by jpicara** [comment]
Alright. I made it working by the following code (in case that it can help someone who has the same issue)

```
telemetry:
  cassandra:
    endpoint:
      address: "0.0.0.0"
    relabels:
    - action: drop
      regex: ^org_apache_cassandra_metrics_table_cas_prepare_latency$|^org_apache_cassandra_metrics_table_cas_propose_latency$|^org_apache_cassandra_metrics_table_cas_commit_latency$|^org_apache_cassandra_metrics_table_view_read_time$|^org_apache_cassandra_metrics_table_view_lock_acquire_time$|^org_apache_cassandra_metrics_table_read_latency$|^org_apache_cassandra_metrics_table_coordinator_scan_latency$|^org_apache_cassandra_metrics_table_coordinator_read_latency$|^org_apache_cassandra_metrics_table_range_latency$|^org_apache_cassandra_metrics_table_write_latency$|^org_apache_cassandra_metrics_table_ss_tables_per_read$|^org_apache_cassandra_metrics_table_waiting_on_free_memtable_space$|^org_apache_cassandra_metrics_table_replica_filtering_protection_rows_cached_per_query$|^org_apache_cassandra_metrics_table_live_scanned$|^org_apache_cassandra_metrics_table_col_update_time_delta$
      sourceLabels:
        - __name__
  prometheus:
    enabled: true
    commonLabels:
      release: monitoring-platform
    mcac:
      enabled: false
```
Then, it updates the cluster-dc1-metrics-agent-config and the K8ssandraCluster crd. Metrics inside the regex expression are being now dropped properly.

However I realized the following scenario. What about is we would like to add more metrics inside the regex part? I tested this out and even though the cluster-dc1-metrics-agent-config and the K8ssandraCluster crd are updated with the new metrics, Prometheus still scrapes them. Is this the expected behaviour or it should be take it automatically? Does it mean we need to restart C* to apply the changes?
Note: Changes have been applied after restart the nodes but I do no know if this is what we should expect or it should be taken without restarting anything as configMap + CRD already had the changes.

**Comment by kirti-ranjan** [comment]
Hi, I have recently enabled the telemetry to use Prometheus & Grafana. But in my case it seems Prometheus is unable to reach the `cassandra-all-pods-service` on port `9000`. I did some test from within the Prometheus pod:
```
/prometheus $ telnet -a cassandra-new-dc1-all-pods-service.k8ssandra-cluster.svc 9000
telnet: can't connect to remote host (10.X.XX.XXXX): Connection refused
/prometheus $ telnet -a cassandra-new-dc1-stargate-service.k8ssandra-cluster.svc 8084
Connected to cassandra-new-dc1-stargate-service.k8ssandra-cluster.svc
```
Above you can see that connection was refused for Cassandra while for Stargate it was successful.

I am running K8ssandra in EKS cluster with VPC CNI. Below are the further details of K8ssandra Operator:
Cassandra Server Version: `4.0.8`
K8ssandra-Operator: `v1.6.1`
Cass-Operator: `v1.15.0`

K8ssandraCluster YAML Snippet:
```yaml
cassandra:
    clusterName: cassandra-new
    serverVersion: "4.0.8"
    softPodAntiAffinity: true
    telemetry:
      prometheus:
        enabled: true
      mcac:
        enabled: false
```
Prometheus Targets:
![Screenshot 2023-05-05 at 12 19 31](https://user-images.githubusercontent.com/37243448/236434305-204693a7-7a63-43dc-a475-3694f2e78e9a.png)

Appreciate the support here. Thanks in advance.

**Comment by agido-heppe** [comment]
Try to alter your deployment as follows:
```yaml
cassandra:
    clusterName: cassandra-new
    serverVersion: "4.0.8"
    softPodAntiAffinity: true
    telemetry:
      prometheus:
        enabled: true
      mcac:
        enabled: false
      cassandra:
        endpoint: "0.0.0.0"
 ```
Otherwise the metrics endpoint will be bound to localhost and not available for prometheus.

**Comment by kirti-ranjan** [comment]
Many thanks @agido-heppe . Really appreciate your quick response. The targets are now UP after adding the `.spec.cassandra.telemetry.cassandra.endpoint.address` and setting the value to `0.0.0.0`.

**Comment by eranbetzalel** [comment]
It seems to have stumbled upon a similar issue, but in my case the prometheus HTTP is not even up, although I've configured it in the telemetry configuration.

Have anyone experienced something similar or know how to deal or debug it?

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: cassandra-production
  namespace: k8ssandra-operator
spec:
  cassandra:
    serverVersion: "5.0.2"
    datacenters:
      - metadata:
          name: dc1
        ... snip ...
        telemetry:
          prometheus:
            enabled: true
          mcac:
            enabled: false
          cassandra:
            endpoint:
              address: "0.0.0.0"
              port: "prometheus"
```

It seems the prometheus server is not even up.

```
[cassandra@cassandra-production-dc1-r1-sts-3 /]$ ss -na
Netid      State          Recv-Q      Send-Q                 Local Address:Port                Peer Address:Port        Process      
nl         UNCONN         0           0                                  0:0                               *                         
nl         UNCONN         896         0                                  4:0                               *                         
nl         UNCONN         4352        0                                  4:595                             *                         
nl         UNCONN         0           0                                  6:0                               *                         
nl         UNCONN         0           0                                  9:0                               *                         
nl         UNCONN         0           0                                 10:0                               *                         
nl         UNCONN         0           0                                 12:0                               *                         
nl         UNCONN         0           0                                 15:0                               *                         
nl         UNCONN         0           0                                 16:0                               *                         
u_str      ESTAB          0           0                                  * 941263                         * 0                        
u_str      ESTAB          0           0                                  * 946389                         * 0                        
u_str      ESTAB          0           0                                  * 949439                         * 0                        
u_str      ESTAB          0           0                /tmp/cassandra.sock 950366                         * 945483                   
u_str      ESTAB          0           0                                  * 939205                         * 939204                   
u_str      LISTEN         0           1024              /tmp/oss-mgmt.sock 944462                         * 0                        
u_str      ESTAB          0           0                /tmp/cassandra.sock 943329                         * 939245                   
u_str      LISTEN         0           1024             /tmp/cassandra.sock 927739                         * 0                        
u_str      ESTAB          0           0                                  * 939204                         * 939205                   
u_str      ESTAB          0           0                                  * 945483                         * 950366                   
u_str      ESTAB          0           0                                  * 948273                         * 0                        
u_str      ESTAB          0           0                                  * 939245                         * 943329                   
tcp        LISTEN         0           512                    10.104.144.53:7000                     0.0.0.0:*                        
tcp        LISTEN         0           128                          0.0.0.0:8080                     0.0.0.0:*                        
tcp        LISTEN         0           50                         127.0.0.1:39083                    0.0.0.0:*                        
tcp        LISTEN         0           50                         127.0.0.1:7199                     0.0.0.0:*                        
tcp        LISTEN         0           1024                         0.0.0.0:9042                     0.0.0.0:*                        
tcp        ESTAB          0           0                      10.104.144.53:44720              10.104.149.16:7000                     
tcp        TIME-WAIT      0           0                      10.104.144.53:8080                10.104.144.1:52632                    
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.149.15:42892                    
tcp        ESTAB          0           0                      10.104.144.53:46890              10.104.149.16:7000                     
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:59136                    
tcp        ESTAB          0           0                      10.104.144.53:47646              10.104.149.14:7000                     
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:37766                    
tcp        ESTAB          0           0                      10.104.144.53:42458              10.104.144.54:7000                     
tcp        TIME-WAIT      0           0                      10.104.144.53:8080                10.104.144.1:50460                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080                10.104.144.1:59900                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:55192                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:55176                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:55160                    
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.149.14:47188                    
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.149.16:55992                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.50:53864                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080                10.104.144.1:50468                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:33448                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:55118                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:55084                    
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.144.52:57554                    
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.144.53:42172                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080                10.104.144.1:59902                    
tcp        ESTAB          0           0                      10.104.144.53:46670              10.104.144.52:7000                     
tcp        TIME-WAIT      0           0                      10.104.144.53:8080                10.104.144.1:51380                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:33422                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:55102                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:55138                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:33414                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080                10.104.144.1:42076                    
tcp        ESTAB          0           0                      10.104.144.53:46674              10.104.144.52:7000                     
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.144.54:53036                    
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.144.52:55582                    
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.144.54:53032                    
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.149.15:42888                    
tcp        ESTAB          0           0                      10.104.144.53:42470              10.104.144.54:7000                     
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.50:53856                    
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.149.16:55990                    
tcp        ESTAB          0           0                      10.104.144.53:34900              10.104.149.14:7000                     
tcp        TIME-WAIT      0           0                      10.104.144.53:8080                10.104.144.1:57486                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:33412                    
tcp        SYN-SENT       0           1                      10.104.144.53:47610              10.104.149.11:7000                     
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:33432                    
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.144.52:55572                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:55144                    
tcp        ESTAB          0           0                      10.104.144.53:60130              10.104.149.15:7000                     
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.144.54:33738                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:37754                    
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.149.15:44874                    
tcp        ESTAB          0           0                      10.104.144.53:36068              10.104.144.54:7000                     
tcp        ESTAB          0           0                      10.104.144.53:46896              10.104.149.16:7000                     
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:33408                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:55096                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:37742                    
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.149.14:33238                    
tcp        ESTAB          0           0                      10.104.144.53:34910              10.104.149.14:7000                     
tcp        ESTAB          0           0                      10.104.144.53:42172              10.104.144.53:7000                     
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:55126                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:37764                    
tcp        ESTAB          0           0                      10.104.144.53:60114              10.104.149.15:7000                     
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.149.14:33230                    
tcp        ESTAB          0           0                      10.104.144.53:60104              10.104.149.15:7000                     
tcp        ESTAB          0           0                      10.104.144.53:7000               10.104.149.16:51162                    
tcp        TIME-WAIT      0           0                      10.104.144.53:8080               10.104.130.51:59126                    
tcp        ESTAB          0           0                      10.104.144.53:47384              10.104.144.52:7000                     
```
