### ISSUE TITLE
Show resources created by the operator in ArgoCD

### ISSUE THREAD

**Issue by Mokto** [k8ssandra/k8ssandra-operator#952]
**What is missing?**
When using ArgoCD ideally we should see all resources created by the operator in argocd

**Why do we need it?**
Debugging

**Environment**

* K8ssandra Operator version:
1.5.1 

**Anything else we need to know?**:
Related to https://github.com/zalando/postgres-operator/issues/1766

https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#applications

Thanks!

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/K8OP-241) by [Unito](https://www.unito.io)
┆Issue Number: K8OP-241

**Comment by adejanovski** [comment]
I took a look at the linked conversation but don't think there's something we can do in the operator. There's a mention of placing owner references on objects, which is something we already do and yet ArgoCD 
Note that if it's a matter of placing labels on objects that the operator will create, you can do this by using [K8ssandraCluster.spec.cassandra.metadata](https://docs.k8ssandra.io/reference/crd/k8ssandra-operator-crds-latest/#k8ssandraclusterspeccassandrametadata) in your K8ssandraCluster definition.

I do not think it would be reasonable to add ArgoCD specific labels into the operator since this can be managed externally and would only create noise in our code and objects for folks not using ArgoCD for deployments.

Do you see anything generic that we could do to help ArgoCD here, aside from placing argo specific labels on objects?

**Comment by Mokto** [comment]
Just had a look at the issue myself and I think I found out why it's not working:
Yes, actually an ownerReference is set but it doesn't seem to be the proper one!

My cassandra cluster CRD:
![Screenshot 2023-06-07 at 16 15 16](https://github.com/k8ssandra/k8ssandra-operator/assets/5103928/c4bfbe97-9f39-47db-8ae7-a75dc61ea9a2)

The deployed STS:

<img width="379" alt="Screenshot 2023-06-07 at 16 15 20" src="https://github.com/k8ssandra/k8ssandra-operator/assets/5103928/f8740641-bcd6-489d-9235-5bbac69aac82">

**Comment by Mokto** [comment]
Ah, yeah, that's makes a lot of sense!

But then the fix is all about adding `ownerReferences` to the `CassandraDatacenter` object ?

I just checked, it's not there.

**Comment by adejanovski** [comment]
Sadly we can't do that because a CassandraDatacenter object can be created in a different namespace than its owning K8ssandraCluster object.
Quoting the [k8s official docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/#owner-references-in-object-specifications): 

> Note:
Cross-namespace owner references are disallowed by design. Namespaced dependents can specify cluster-scoped or namespaced owners. A namespaced owner must exist in the same namespace as the dependent. If it does not, the owner reference is treated as absent, and the dependent is subject to deletion once all owners are verified absent.

Sadly I don't think there's something we can do here due to our support of cluster scoped deployments 😕

**Comment by Mokto** [comment]
I think we can still add the owner and it just won't be recognized if it's part of a different namespace?

Or just add it conditionally if part of the same namespace.

**Comment by vavsab** [comment]
So bad not to have all the visibility due to one missing reference. Found a workaround:

Add `labels` and `annotations` from the example below:
```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: core-cassandra
spec:
  cassandra:
    serverVersion: "4.0.1"
    datacenters:
      - metadata:
          name: dc1
          labels:
            # Make CassandraDatacenter resource visible in ArgoCD
            argocd.argoproj.io/instance: cassandra
          annotations:
            # Avoid pruning CassandraDatacenter. 
            # We do not manage it directly.
            # We just want to see what is happening there. 
            argocd.argoproj.io/sync-options: Prune=false
            # Do not show out-of-sync on the app
            # You will still see out-of-sync on the resource :(
            argocd.argoproj.io/compare-options: IgnoreExtraneous
        size: 3
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: default
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 512M
        stargate:
          size: 1
          heapSize: 256M
```

You will still see trash bin on the resource but your app will stay in synced state 
![Image](https://github.com/user-attachments/assets/20a480cb-48c5-4b62-94de-d6a2ec49b748)

and even if you sync with prune it will not be removed

![Image](https://github.com/user-attachments/assets/088c7805-ef97-48b4-936a-d3d4bf521448)

Not perfect but gives much better visibility
