### ISSUE TITLE
DC-level annotations and labels are ignored

### ISSUE THREAD

**Issue by klamkma** [k8ssandra/k8ssandra-operator#969]
**What happened?**
I set 
```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: cluster
spec:
  cassandra:
    datacenters:
    - ....  
      metadata:
        name: some-name
        annotations:
          sidecar.istio.io/inject: "false"
```
But then generated CassandraDatacenter is having empty metadata.
```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: some-name
spec:
  podTemplateSpec:
    metadata: {}
```
**Did you expect to see something different?**
I expected to see my annotation in podTemplateSpec.
```
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: some-name
spec:
  podTemplateSpec:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
```

* K8ssandra Operator version:

docker.io/k8ssandra/k8ssandra-operator:v1.4.1

* Kubernetes version information:

v1.24.11

* K8ssandra Operator Logs:

No error in operator logs.

**Anything else we need to know?**:
Maybe I should set this annotation in a different way? 

Thank you!

**Comment by olim7t** [comment]
Hi @klamkma,

It looks like the DC-level labels and annotations are broken. We're going to look into that, in the meantime you can set them at the top-level (if using the same for all DCs works for you):

```yaml
spec:
  cassandra:
    metadata:
      labels:
        test-cassdc-label: "true"
      annotations:
        test-cassdc-annotation: "true"
      pods:
        labels:
          test-pod-label: "true"
        annotations:
          test-pod-annotation: "true"
    datacenters:
      ...
```

Also, note that what you set directly under `metadata` applies to the `CassandraDatacenter` itself. For the `podTemplateSpec`, you need to use `metadata.pods`.
